import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      
  pearchat/
│
├── config/
│   └── database.php          # Database configuration (auto-generated by install.php)
│
├── includes/
│   ├── auth.php              # Authentication class
│   └── encryption.php        # Encryption helper class
│
├── api/
│   ├── conversations.php     # API for conversations (GET, POST)
│   ├── messages.php          # API for messages (GET, POST)
│   └── users.php             # API for user search
│
├── admin/
│   └── index.php             # Admin dashboard
│
├── index.php                 # Login/Register page (main entry)
├── chat.php                  # Main chat interface
├── profile.php               # User profile page
├── settings.php              # User settings page
├── logout.php                # Logout handler
└── install.php               # Installation script (run once)

    </>
  );
}
