import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import SectionFrame from '../components/ui/SectionFrame';
import { WordReveal, CharSlideDown } from '../components/ui/TextAnimations';

gsap.registerPlugin(ScrollTrigger);

const FAQS = [
  {
    q: "Is this a subscription?",
    a: "No, Lumimotion is a one-time purchase. Once you buy a license, you get lifetime access to the current prompt library and all future updates."
  },
  {
    q: "Can I use these prompts for client work?",
    a: "Absolutely. The outputs generated by our prompts are entirely yours. You can use them for personal projects, commercial client work, and internal tools."
  },
  {
    q: "Do I need to know how to code?",
    a: "While basic knowledge of HTML/CSS or React helps, our prompts are engineered to instruct LLMs (like Claude or Gemini) to output complete, structured component code that you can copy and paste."
  },
  {
    q: "Which AI models work best?",
    a: "Our structural constraints are optimized primarily for Claude 3.5 Sonnet and Gemini 1.5 Pro, as they follow strict JSON-like parameters best. However, GPT-4o also produces excellent results."
  },
  {
    q: "How are the team licenses managed?",
    a: "The team license gives you a shared workspace link where up to 5 team members can access the prompt vault, share custom JSON parameter presets, and export prompt sequences."
  },
  {
    q: "Do you offer refunds?",
    a: "Due to the non-returnable nature of digital prompts and knowledge, we do not offer refunds. We recommend trying our free templates in the library first to ensure they fit your workflow."
  }
];

export default function PricingPage() {
  useEffect(() => {
    // Scroll to top on mount
    window.scrollTo(0, 0);

    const ctx = gsap.context(() => {
      // Set initial states
      gsap.set('.scroll-fade-in', { opacity: 0, y: 40, filter: 'blur(12px)' });

      // Staggered reveal for standard content
      ScrollTrigger.batch('.scroll-fade-in', {
        start: "top 85%",
        onEnter: batch => {
          gsap.to(batch, {
            opacity: 1,
            y: 0,
            filter: 'blur(0px)',
            duration: 0.8,
            stagger: 0.1,
            ease: "power3.out",
            overwrite: true
          });
        }
      });

      // Word reveal animations
      const revealSections = document.querySelectorAll('.reveal-section');
      revealSections.forEach(section => {
        const words = section.querySelectorAll('.gsap-word-reveal');
        if (words.length) {
          gsap.fromTo(words,
            { y: "100%", opacity: 0, filter: "blur(8px)" },
            {
              scrollTrigger: {
                trigger: section,
                start: "top 85%",
                toggleActions: "play none none reverse"
              },
              y: "0%",
              opacity: 1,
              filter: "blur(0px)",
              duration: 0.8,
              stagger: 0.04,
              ease: "power3.out"
            }
          );
        }
      });
    });

    return () => ctx.revert();
  }, []);

  return (
    <div className="flex flex-col w-full min-h-screen">
      
      {/* 1. PRICING HEADER & CARDS */}
      <SectionFrame className="pt-32 pb-24 px-6 bg-transparent relative z-10">
        <div className="max-w-6xl mx-auto">
          
          {/* Header */}
          <div className="mb-16 flex flex-col items-start max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
               <CharSlideDown text="Unlock All Access" delay={0.2} />
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter mb-6 text-white text-balance reveal-section">
              <WordReveal>One time payment.</WordReveal><br />
              <WordReveal>Lifetime access.</WordReveal>
            </h1>
            <p className="text-white/50 text-base md:text-lg text-pretty scroll-fade-in font-geist tracking-tight">
              Skip the subscription. Gain instant access to the entire vault of production-ready prompt structures and all future additions.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8">
            
            {/* Left Column: Vertically Stacked Cards */}
            <div className="lg:col-span-7 flex flex-col gap-6 lg:gap-8">
              
              {/* Card 1: Standard */}
              <div className="border border-white/10 bg-white/5 backdrop-blur-md p-8 md:p-10 flex flex-col md:flex-row gap-8 items-start hover:border-white/20 transition-all duration-300 scroll-fade-in">
                {/* Left part of card */}
                <div className="w-full md:w-1/2 flex flex-col h-full scroll-fade-in">
                  <h3 className="text-xl font-geist font-light text-white mb-2 tracking-tighter">Standard License</h3>
                  <p className="text-sm text-white/50 mb-8 font-geist tracking-tight">Perfect for solo designers and developers.</p>
                  
                  <div className="flex items-start gap-1 mb-8 md:mb-12">
                    <span className="text-xl text-white/50 mt-1">$</span>
                    <span className="text-5xl font-geist font-light tracking-tighter text-white">29</span>
                    <span className="text-xs text-white/40 self-end mb-2 ml-1 font-geist tracking-tight">/ one-time</span>
                  </div>
                  
                  <button className="w-full bg-white/10 border border-white/20 text-white py-3 text-sm hover:bg-white/20 transition-colors mt-auto font-geist tracking-tight font-medium">
                    Get Standard
                  </button>
                </div>
                
                {/* Right part of card: Features */}
                <div className="w-full md:w-1/2 flex flex-col gap-4 scroll-fade-in">
                  <div className="text-xs font-semibold uppercase tracking-widest text-white/40 mb-2 font-geist">Includes</div>
                  <ul className="flex flex-col gap-4 text-sm font-geist tracking-tight">
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Access to 42+ structured prompts</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>New templates added monthly</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Use for personal & commercial</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Lifetime updates included</span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Card 2: Team */}
              <div className="border border-[#c6f91f]/30 bg-[#c6f91f]/10 backdrop-blur-md p-8 md:p-10 flex flex-col md:flex-row gap-8 items-start relative overflow-hidden group scroll-fade-in">
                <div className="absolute top-0 right-0 w-64 h-64 bg-[#c6f91f]/20 rounded-full blur-[80px] pointer-events-none"></div>
                <div className="absolute top-0 right-0 px-3 py-1 bg-[#c6f91f] text-black text-[10px] font-bold uppercase tracking-widest">Most Popular</div>

                {/* Left part of card */}
                <div className="w-full md:w-1/2 flex flex-col h-full relative z-10 scroll-fade-in">
                  <h3 className="text-xl font-geist font-light text-white mb-2 tracking-tighter">Team License</h3>
                  <p className="text-sm text-white/60 mb-8 font-geist tracking-tight">For teams shipping products together.</p>
                  
                  <div className="flex items-start gap-1 mb-8 md:mb-12">
                    <span className="text-xl text-white/50 mt-1">$</span>
                    <span className="text-5xl font-geist font-light tracking-tighter text-white">99</span>
                    <span className="text-xs text-white/40 self-end mb-2 ml-1 font-geist tracking-tight">/ one-time</span>
                  </div>
                  
                  <button className="w-full bg-[#c6f91f] text-black py-3 text-sm hover:bg-[#aade17] transition-colors mt-auto shadow-[0_0_20px_rgba(198,249,31,0.2)] font-geist tracking-tight font-medium">
                    Get Team Access
                  </button>
                </div>
                
                {/* Right part of card: Features */}
                <div className="w-full md:w-1/2 flex flex-col gap-4 relative z-10 scroll-fade-in">
                  <div className="text-xs font-semibold uppercase tracking-widest text-[#c6f91f] mb-2 font-geist">Everything in Standard, plus:</div>
                  <ul className="flex flex-col gap-4 text-sm font-geist tracking-tight">
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Up to 5 team members</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Shared prompt workspace</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Custom JSON variables export</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Priority email support</span>
                    </li>
                  </ul>
                </div>
              </div>

            </div>

            {/* Right Column: Secondary CTA Panel */}
            <div className="lg:col-span-5 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in h-full">
              <div className="flashlight-content p-8 md:p-10 flex flex-col relative overflow-hidden group h-full">
                <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[120%] h-64 bg-[radial-gradient(ellipse_at_bottom,rgba(255,255,255,0.05)_0%,transparent_70%)] pointer-events-none transition-opacity group-hover:opacity-100 opacity-50"></div>
                
                <div className="w-12 h-12 rounded bg-white/10 border border-white/20 flex items-center justify-center mb-8 relative z-10 scroll-fade-in">
                  <iconify-icon icon="solar:buildings-2-linear" class="text-2xl text-white/70 group-hover:text-white transition-colors"></iconify-icon>
                </div>

                <h3 className="text-2xl font-geist font-light tracking-tighter text-white mb-4 relative z-10 scroll-fade-in">Enterprise Solutions</h3>
                <p className="text-sm text-white/60 leading-relaxed mb-10 relative z-10 text-pretty font-geist tracking-tight scroll-fade-in">
                  Need a dedicated prompt system modeled exactly to your company's internal UI library or design system? We can map our architecture directly to your proprietary components.
                </p>

                <div className="flex flex-col gap-6 mb-10 relative z-10">
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-white/30 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">Dedicated Designer</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">Work directly with our team to map specific variables to your design token structure.</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-white/30 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">CI/CD Integration</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">API access to the generated constraints for seamless automation pipelines.</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-[#c6f91f]/60 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">Unlimited Seats</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">Company-wide access and secure enterprise SSO configuration setup.</p>
                    </div>
                  </div>
                </div>

                <button className="mt-auto border border-white/20 bg-transparent text-white w-full py-3.5 text-sm hover:bg-white/10 hover:border-white/30 transition-all relative z-10 flex items-center justify-center gap-2 font-geist tracking-tight font-medium scroll-fade-in">
                  Contact Sales <iconify-icon icon="solar:arrow-right-linear" />
                </button>
              </div>
            </div>

          </div>
        </div>
      </SectionFrame>

      {/* 2. FAQ SECTION */}
      <SectionFrame className="py-24 px-6 bg-transparent relative z-10 border-none" noBorderBottom>
        <div className="max-w-4xl mx-auto flex flex-col">
          <div className="text-center mb-16 flex flex-col items-center">
            <h2 className="text-3xl md:text-4xl font-geist font-light tracking-tighter text-white mb-4 reveal-section">
               <WordReveal>Frequently asked questions</WordReveal>
            </h2>
            <p className="text-white/50 text-base font-geist tracking-tight scroll-fade-in">Everything you need to know about the product and billing.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-10">
            {FAQS.map((faq, i) => (
              <div key={i} className="flex flex-col scroll-fade-in">
                <h4 className="text-base text-white font-geist font-medium tracking-tight mb-3 flex items-start gap-3">
                  <iconify-icon icon="solar:question-circle-linear" class="text-[#c6f91f] mt-1 shrink-0" />
                  {faq.q}
                </h4>
                <p className="text-sm text-white/50 leading-relaxed font-geist tracking-tight pl-7">
                  {faq.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </SectionFrame>

      {/* 3. FOOTER */}
      <footer className="py-12 px-6 border-t border-white/10 bg-white/5 backdrop-blur-md relative z-10 mt-auto">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-12 md:gap-6 max-w-6xl mx-auto scroll-fade-in">
          <div className="col-span-1 md:col-span-2 flex flex-col items-start">
            <div className="flex items-center gap-2 mb-4">
              <iconify-icon icon="solar:layers-minimalistic-linear" class="text-xl text-[#c6f91f]" />
              <span className="font-geist tracking-tight font-medium text-sm text-white">Lumimotion</span>
            </div>
            <p className="text-xs text-white/50 max-w-xs font-geist tracking-tight">
              Premium, editorial, system-driven prompt templates for designers and developers.
            </p>
          </div>
          
          <div className="flex flex-col gap-3">
            <h4 className="text-xs font-geist tracking-tight font-medium text-white mb-2 uppercase tracking-widest">Platform</h4>
            <Link to="/library" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">Prompt Library</Link>
            <Link to="/pricing" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">Pricing</Link>
            <Link to="/" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">How it works</Link>
          </div>

          <div className="flex flex-col gap-3">
            <h4 className="text-xs font-geist tracking-tight font-medium text-white mb-2 uppercase tracking-widest">Legal</h4>
            <a href="#" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">Terms of Service</a>
            <a href="#" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">Privacy Policy</a>
            <a href="#" className="text-xs text-white/50 hover:text-white transition-colors font-geist tracking-tight">Contact</a>
          </div>
        </div>
        
        <div className="mt-16 pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4 scroll-fade-in">
          <p className="text-[10px] text-white/40 font-geist tracking-tight">© {new Date().getFullYear()} Lumimotion. All rights reserved.</p>
          <div className="flex gap-4">
            <a href="#" className="text-white/40 hover:text-white transition-colors"><iconify-icon icon="simple-icons:x" /></a>
            <a href="#" className="text-white/40 hover:text-white transition-colors"><iconify-icon icon="simple-icons:github" /></a>
          </div>
        </div>
      </footer>

    </div>
  );
}