export const projects = [
  {
    id: 1,
    title: "Lumen Capital",
    category: "Investor Deck",
    year: "2024",
    slides: 24,
    client: "Lumen Ventures",
    color: "#2BE0A8",
    accent: "#8A5BD6",
    description: "A bold Series B pitch deck balancing dense financials with cinematic typography. Built to convert in 12 minutes.",
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    tools: ["PowerPoint", "Figma", "Illustrator"],
  },
  {
    id: 2,
    title: "Nordic Bloom",
    category: "Brand Presentation",
    year: "2024",
    slides: 38,
    client: "Bloom Studio",
    color: "#8A5BD6",
    accent: "#2BE0A8",
    description: "Editorial-style brand book translated into a fully animated keynote with custom transitions.",
    cover: "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=1200&q=80",
    tools: ["Keynote", "After Effects"],
  },
  {
    id: 3,
    title: "Quantum Health",
    category: "Medical Report",
    year: "2023",
    slides: 52,
    client: "Quantum Bio",
    color: "#2AA9A6",
    accent: "#2BE0A8",
    description: "Complex clinical data visualized through layered diagrams and accessible color systems.",
    cover: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80",
    tools: ["PowerPoint", "Datawrapper"],
  },
  {
    id: 4,
    title: "Atlas Real Estate",
    category: "Sales Deck",
    year: "2024",
    slides: 18,
    client: "Atlas Group",
    color: "#2BE0A8",
    accent: "#8A5BD6",
    description: "Luxury property portfolio deck with full-bleed imagery and refined editorial pacing.",
    cover: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    tools: ["PowerPoint", "Photoshop"],
  },
  {
    id: 5,
    title: "Orbit Conference",
    category: "Keynote Talk",
    year: "2023",
    slides: 65,
    client: "Orbit Summit",
    color: "#8A5BD6",
    accent: "#2AA9A6",
    description: "High-impact stage deck designed for 4K LED walls — bold motion-friendly typography throughout.",
    cover: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&q=80",
    tools: ["Keynote", "Cinema 4D"],
  },
  {
    id: 6,
    title: "Tessera Fashion",
    category: "Lookbook Deck",
    year: "2024",
    slides: 30,
    client: "Tessera Studio",
    color: "#2AA9A6",
    accent: "#8A5BD6",
    description: "Seasonal collection lookbook reimagined as an interactive PPTX with grid-based storytelling.",
    cover: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&q=80",
    tools: ["PowerPoint", "InDesign"],
  },
  {
    id: 7,
    title: "Voltaic Energy",
    category: "Annual Report",
    year: "2023",
    slides: 84,
    client: "Voltaic Co.",
    color: "#2BE0A8",
    accent: "#2AA9A6",
    description: "Sustainability report translated into a presentation-first format for stakeholder roadshows.",
    cover: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&q=80",
    tools: ["PowerPoint", "Illustrator"],
  },
  {
    id: 8,
    title: "Pixel Pantry",
    category: "Product Launch",
    year: "2024",
    slides: 22,
    client: "Pantry Foods",
    color: "#8A5BD6",
    accent: "#2BE0A8",
    description: "Playful FMCG launch deck pairing illustration with hard data — built for press and retail buyers.",
    cover: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
    tools: ["PowerPoint", "Procreate"],
  },
  {
    id: 9,
    title: "Helix EdTech",
    category: "Pitch Deck",
    year: "2024",
    slides: 16,
    client: "Helix Labs",
    color: "#2AA9A6",
    accent: "#8A5BD6",
    description: "Seed-stage edtech pitch deck — clean, generous spacing, optimized for remote pitching.",
    cover: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80",
    tools: ["PowerPoint", "Figma"],
  },
  {
    id: 10,
    title: "Mira Hospitality",
    category: "Brand Guidelines",
    year: "2023",
    slides: 46,
    client: "Mira Hotels",
    color: "#2BE0A8",
    accent: "#8A5BD6",
    description: "Hospitality brand system presented across boutique hotel rollouts — print-quality slides.",
    cover: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    tools: ["Keynote", "InDesign"],
  },
];

export const services = [
  { icon: "solar:presentation-graph-linear", title: "Pitch Decks", desc: "Investor-ready storytelling in 10–25 slides." },
  { icon: "solar:slider-vertical-minimalistic-linear", title: "Keynote Talks", desc: "Stage decks built for live audiences." },
  { icon: "solar:chart-square-linear", title: "Data Reports", desc: "Complex data, clear visual systems." },
  { icon: "solar:palette-linear", title: "Brand Templates", desc: "Reusable PPTX systems for teams." },
];