import { Link } from 'react-router-dom';
import Reveal from '../ui/Reveal';

export default function Footer() {
  return (
    <footer className="w-full max-w-7xl border-x border-t border-white/10 relative overflow-hidden bg-black pt-24 pb-12 px-8 md:px-12 lg:px-20">
      
      {/* Radar Background */}
      <div className="absolute inset-0 z-[0] flex justify-center pointer-events-none overflow-hidden opacity-60 mix-blend-screen">
        <div className="relative w-[340px] h-[340px] md:w-[680px] md:h-[680px] radar-mask mt-12 md:mt-24 gs-radar">
          
          {/* Mathematical Grid Container */}
          <div id="radar-grid" className="absolute inset-0">
            {/* Concentric Circles */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[20%] h-[20%] rounded-full border border-[#4a3875]/40"></div>
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[40%] h-[40%] rounded-full border border-[#4a3875]/40"></div>
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[60%] h-[60%] rounded-full border border-[#4a3875]/40"></div>
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80%] h-[80%] rounded-full border border-[#4a3875]/40"></div>
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[100%] h-[100%] rounded-full border border-[#4a3875]/40"></div>

            {/* Horizontal Axis & Nodes */}
            <div className="absolute top-1/2 left-0 w-full h-[1px] bg-[#4a3875]/40 -translate-y-1/2 shadow-[0_0_10px_rgba(74,56,117,0.5)]">
              {/* Nodes generated by React to ensure perfect spacing relative to circles */}
              <div id="h-nodes" className="absolute inset-0">
                {[10, 20, 30, 40, 60, 70, 80, 90].map((pos) => (
                  <div 
                    key={pos} 
                    className="absolute top-1/2 w-1.5 h-1.5 bg-[#4a3875] rounded-full -translate-x-1/2 -translate-y-1/2 shadow-[0_0_5px_#4a3875]" 
                    style={{ left: `${pos}%` }}
                  ></div>
                ))}
              </div>
            </div>

            {/* Radial Lines (Angles 0, 30, 60, 120, 150) */}
            <div id="radial-lines" className="absolute inset-0">
              {[0, 30, 60, 120, 150].map((angle) => (
                <div 
                  key={angle} 
                  className="absolute top-0 left-1/2 w-[1px] h-full bg-[#4a3875]/20 -translate-x-1/2" 
                  style={{ transform: `rotate(${angle}deg)` }}
                ></div>
              ))}
            </div>
          </div>

          {/* Glowing Targets */}
          <div className="absolute top-[21%] left-[37.5%] w-2.5 h-2.5 rounded-full bg-[#b388ff] shadow-[0_0_15px_#7c4dff] target-node gs-target"></div>
          <div className="absolute top-[31%] right-[25%] w-3 h-3 rounded-full bg-[#b388ff] shadow-[0_0_20px_#7c4dff] target-node target-node-large gs-target"></div>
          <div className="absolute top-[49%] right-[19%] w-1.5 h-1.5 rounded-full bg-[#7c4dff] shadow-[0_0_10px_#7c4dff] opacity-60 gs-target"></div>

          {/* Center Hub */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-16 h-16 md:w-20 md:h-20 rounded-full center-hub flex items-center justify-center z-20 gs-center bg-black border border-[#4a3875]/60 shadow-[0_0_20px_rgba(74,56,117,0.3)]">
            <iconify-icon icon="solar:plain-bold" class="text-white text-2xl md:text-3xl -rotate-45 -ml-1 mt-1 drop-shadow-md"></iconify-icon>
          </div>

        </div>
        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/80 to-black/10"></div>
      </div>

      <div className="relative z-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12 lg:gap-8 mb-20">
        {/* Brand Column */}
        <Reveal className="lg:col-span-4 flex flex-col items-start">
          <Link to="/">
            <div className="text-4xl font-bold tracking-tighter text-transparent bg-clip-text bg-gradient-to-b from-white to-white/20 border border-white/10 px-4 py-1 rounded-sm mb-6 shadow-[inset_0_2px_10px_rgba(255,255,255,0.05)] cursor-pointer hover:border-white/20 transition-colors">
              NextGen
            </div>
          </Link>
          <p className="text-sm text-white/40 leading-relaxed max-w-xs mb-8">
            NextGen architects digital realities that transcend the screen. Building next-generation immersive experiences for visionary brands.
          </p>
          <div className="flex items-center gap-4 text-white/40">
            <a href="#" className="w-10 h-10 rounded-sm border border-white/10 flex items-center justify-center hover:bg-white/10 hover:text-white hover:scale-105 transition-all bg-black shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]">
              <iconify-icon icon="simple-icons:x"></iconify-icon>
            </a>
            <a href="#" className="w-10 h-10 rounded-sm border border-white/10 flex items-center justify-center hover:bg-white/10 hover:text-white hover:scale-105 transition-all bg-black shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]">
              <iconify-icon icon="simple-icons:instagram"></iconify-icon>
            </a>
            <a href="#" className="w-10 h-10 rounded-sm border border-white/10 flex items-center justify-center hover:bg-white/10 hover:text-white hover:scale-105 transition-all bg-black shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]">
              <iconify-icon icon="simple-icons:linkedin"></iconify-icon>
            </a>
            <a href="#" className="w-10 h-10 rounded-sm border border-white/10 flex items-center justify-center hover:bg-white/10 hover:text-white hover:scale-105 transition-all bg-black shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]">
              <iconify-icon icon="simple-icons:youtube"></iconify-icon>
            </a>
          </div>
        </Reveal>

        {/* Links Columns */}
        <Reveal delay={100} className="lg:col-span-2 flex flex-col gap-4">
          <h4 className="text-xs font-semibold tracking-widest text-white uppercase mb-2">Navigation</h4>
          <Link to="/" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Home</Link>
          <Link to="/studio" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Studio</Link>
          <Link to="/features" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Features</Link>
          <Link to="/work" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Selected Work</Link>
          <Link to="/pricing" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Pricing</Link>
          <Link to="/contact" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Contact</Link>
        </Reveal>

        <Reveal delay={200} className="lg:col-span-2 flex flex-col gap-4">
          <h4 className="text-xs font-semibold tracking-widest text-white uppercase mb-2">Expertise</h4>
          <Link to="#" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Spatial Computing</Link>
          <Link to="#" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">XR Experiences</Link>
          <Link to="#" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Virtual Production</Link>
          <Link to="#" className="text-sm text-white/40 hover:text-purple-400 hover:translate-x-1 transition-all w-fit">Game Development</Link>
        </Reveal>

        {/* Newsletter Column */}
        <Reveal delay={300} className="lg:col-span-4 flex flex-col lg:items-end text-left lg:text-right">
          <h4 className="text-3xl md:text-4xl font-semibold tracking-tighter text-white mb-4 leading-none">
            Start a<br/>Project
          </h4>
          <p className="text-sm text-white/40 mb-6 max-w-xs">
            Subscribe to our newsletter for insights on the future of interactive media.
          </p>
          <form className="flex w-full max-w-sm group" onSubmit={(e) => e.preventDefault()}>
            <input 
              type="email" 
              placeholder="Email address..." 
              className="flex-1 h-12 px-4 outline-none text-sm placeholder:text-white/20 rounded-l-sm transition-colors focus:bg-white/5"
              style={{ 
                background: '#000000', 
                border: '1px solid rgba(255,255,255,0.1)', 
                borderRight: 'none', 
                boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.5)' 
              }}
            />
            <button 
              type="submit" 
              className="h-12 px-6 rounded-r-sm text-xs font-medium tracking-wider uppercase text-white hover:brightness-110 transition-all border border-white/10 relative overflow-hidden"
              style={{ 
                background: 'linear-gradient(180deg, #5b21b6 0%, #3b0764 100%)',
                boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.1)' 
              }}
            >
              <span className="relative z-10">Join</span>
              <div className="absolute inset-0 bg-white/20 translate-y-[100%] group-hover:translate-y-0 transition-transform duration-300 ease-out"></div>
            </button>
          </form>
        </Reveal>
      </div>

      {/* Bottom Bar */}
      <Reveal delay={400} className="relative z-10 pt-8 border-t border-white/10 flex flex-col md:flex-row justify-between items-center gap-4 mb-8">
        <p className="text-xs text-white/40 tracking-wider">
          © {new Date().getFullYear()} NextGen Immersive. All rights reserved.
        </p>
        <div className="flex items-center gap-6 text-xs text-white/40 tracking-wider">
          <Link to="/" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link to="/" className="hover:text-white transition-colors">Terms of Service</Link>
        </div>
      </Reveal>

      {/* Footer Data */}
      <div className="absolute bottom-4 left-0 w-full px-8 md:px-12 lg:px-20 flex justify-between items-center text-[10px] md:text-xs font-mono text-white/30 gs-reveal pointer-events-none z-10">
        <div>SYS.OP.492</div>
        <div className="flex gap-4">
          <span>LAT: 45.91</span>
          <span>LNG: -12.44</span>
        </div>
        <div>STATUS: ONLINE</div>
      </div>
      
    </footer>
  );
}