import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2M6V79H761');

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      

<header className="sticky top-0 z-50 w-full border-b border-white/5 bg-zinc-950/60 backdrop-blur-xl">
<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
<div className="flex h-16 items-center justify-between">
<div className="flex items-center gap-2">
<div className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10 border border-white/10">
<iconify-icon className="text-white" height="18" icon="solar:box-linear" width="18"></iconify-icon>
</div>
<span className="text-base font-medium tracking-tighter text-white">MV</span>
</div>
<nav className="hidden md:flex items-center gap-8">
<a className="text-sm font-normal text-zinc-400 hover:text-white transition-colors" href="#">Features</a>
<a className="text-sm font-normal text-zinc-400 hover:text-white transition-colors" href="#">Gallery</a>
<a className="text-sm font-normal text-zinc-400 hover:text-white transition-colors" href="#">Pricing</a>
<a className="text-sm font-normal text-zinc-400 hover:text-white transition-colors" href="#">Docs</a>
</nav>
<div className="flex items-center gap-4">
<a className="hidden md:block text-sm font-normal text-zinc-400 hover:text-white transition-colors" href="#">Log in</a>
<a className="rounded-full bg-white px-4 py-2 text-sm font-medium text-zinc-950 hover:bg-zinc-200 transition-colors" href="#">
                        Start for free
                    </a>
</div>
</div>
</div>
</header>

<main className="flex-1">
<div className="relative overflow-hidden pt-24 pb-32">

<div className="absolute left-1/2 top-0 -translate-x-1/2 -z-10 h-[40rem] w-[80rem] opacity-20" style={{background: 'radial-gradient(ellipse at top, rgba(124, 58, 237, 0.4) 0%, transparent 70%)'}}></div>
<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center">
<div className="inline-flex items-center rounded-full border border-white/10 bg-white/5 px-3 py-1 mb-8 backdrop-blur-sm">
<span className="flex h-2 w-2 rounded-full bg-violet-500 mr-2"></span>
<span className="text-xs font-normal text-zinc-300">New: Hyper-realistic rendering engine v2.0</span>
</div>
<h1 className="mx-auto max-w-4xl text-5xl sm:text-7xl font-medium tracking-tighter text-transparent bg-clip-text bg-gradient-to-b from-white to-white/50 mb-6">
                    Beautiful 3D movies,<br/> generated by AI.
                </h1>
<p className="mx-auto max-w-2xl text-lg text-zinc-400 font-normal mb-10">
                    Turn your text prompts into stunning, moving 3D scenes in seconds. Completely free to start, beautifully designed for creators.
                </p>
<div className="flex flex-col sm:flex-row items-center justify-center gap-4">
<button className="w-full sm:w-auto rounded-full bg-white px-6 py-3 text-sm font-medium text-zinc-950 hover:bg-zinc-200 transition-colors flex items-center justify-center gap-2">
<iconify-icon height="18" icon="solar:magic-stick-3-linear" width="18"></iconify-icon>
                        Generate now
                    </button>
<button className="w-full sm:w-auto rounded-full border border-white/10 bg-white/5 px-6 py-3 text-sm font-medium text-white hover:bg-white/10 transition-colors flex items-center justify-center gap-2">
<iconify-icon height="18" icon="solar:play-circle-linear" width="18"></iconify-icon>
                        Watch showcase
                    </button>
</div>
</div>

<div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 mt-20">
<div className="rounded-2xl border border-white/10 bg-zinc-950/50 backdrop-blur-xl shadow-2xl overflow-hidden flex flex-col md:flex-row h-auto md:h-[32rem]">

<div className="w-full md:w-72 border-b md:border-b-0 md:border-r border-white/10 bg-zinc-900/20 p-6 flex flex-col gap-8">
<div>
<h3 className="text-sm font-medium text-white mb-4">Scene Setup</h3>
<div className="space-y-6">

<div className="space-y-2">
<label className="text-xs font-normal text-zinc-400">Environment</label>
<div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/5 px-3 py-2 cursor-pointer hover:bg-white/10 transition-colors">
<span className="text-sm text-zinc-300">Cyberpunk City</span>
<iconify-icon className="text-zinc-500" height="16" icon="solar:alt-arrow-down-linear" width="16"></iconify-icon>
</div>
</div>

<div className="flex items-center justify-between">
<label className="text-xs font-normal text-zinc-400">Ray Tracing</label>
<button className="relative inline-flex h-5 w-9 items-center rounded-full bg-violet-600 transition-colors focus:outline-none">
<span className="translate-x-5 inline-block h-3 w-3 transform rounded-full bg-white transition-transform"></span>
</button>
</div>
<div className="flex items-center justify-between">
<label className="text-xs font-normal text-zinc-400">Volumetric Fog</label>
<button className="relative inline-flex h-5 w-9 items-center rounded-full bg-zinc-700 transition-colors focus:outline-none">
<span className="translate-x-1 inline-block h-3 w-3 transform rounded-full bg-white transition-transform"></span>
</button>
</div>

<div className="space-y-3">
<div className="flex items-center justify-between">
<label className="text-xs font-normal text-zinc-400">Camera Speed</label>
<span className="text-xs text-zinc-500">1.5x</span>
</div>
<div className="relative h-1 w-full rounded-full bg-zinc-800">
<div className="absolute top-0 left-0 h-full w-[60%] rounded-full bg-violet-500"></div>
<div className="absolute top-1/2 left-[60%] h-3 w-3 -translate-y-1/2 -translate-x-1/2 rounded-full border-2 border-zinc-950 bg-white shadow"></div>
</div>
</div>
</div>
</div>
<div className="mt-auto">
<button className="w-full rounded-lg bg-white/10 py-2 text-sm font-medium text-white hover:bg-white/20 transition-colors border border-white/5">
                                Render Scene
                            </button>
</div>
</div>

<div className="flex-1 relative bg-zinc-950 flex items-center justify-center p-4">

<div className="relative w-full max-w-2xl aspect-video rounded-xl overflow-hidden border border-white/5 bg-zinc-900 shadow-2xl group cursor-pointer">
<div className="absolute inset-0 bg-gradient-to-br from-violet-500/20 via-transparent to-cyan-500/20 mix-blend-overlay"></div>

<div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48 rounded-full border border-white/10 bg-white/5 blur-xl"></div>
<div className="absolute top-1/3 left-1/3 w-32 h-32 rounded-lg border border-violet-500/30 bg-violet-500/10 rotate-12 backdrop-blur-md"></div>
<div className="absolute bottom-1/3 right-1/3 w-24 h-24 rounded-full border border-cyan-500/30 bg-cyan-500/10 -rotate-12 backdrop-blur-md"></div>

<div className="absolute inset-0 flex items-center justify-center bg-black/20 group-hover:bg-black/40 transition-colors">
<div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-white transform group-hover:scale-110 transition-transform">
<iconify-icon height="28" icon="solar:play-linear" width="28"></iconify-icon>
</div>
</div>

<div className="absolute bottom-0 left-0 w-full h-1 bg-zinc-800">
<div className="h-full w-1/3 bg-violet-500"></div>
</div>
</div>
</div>
</div>
</div>
</div>

<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-24 border-t border-white/5">
<div className="mb-16">
<h2 className="text-2xl sm:text-3xl font-medium tracking-tight text-white mb-4">Designed for the future of motion.</h2>
<p className="text-base text-zinc-400 max-w-2xl font-normal">Everything you need to create breathtaking 3D animations, bundled in an interface that gets out of your way.</p>
</div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-6">

<div className="rounded-2xl border border-white/5 bg-zinc-900/30 p-8 hover:bg-zinc-900/50 transition-colors">
<div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white">
<iconify-icon height="24" icon="solar:layers-minimalistic-linear" width="24"></iconify-icon>
</div>
<h3 className="text-lg font-medium text-white mb-2 tracking-tight">Beautiful Designs</h3>
<p className="text-sm text-zinc-400 font-normal leading-relaxed">Our AI models are trained on award-winning cinematography, ensuring perfect composition, lighting, and materials out of the box.</p>
</div>

<div className="rounded-2xl border border-white/5 bg-zinc-900/30 p-8 hover:bg-zinc-900/50 transition-colors">
<div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white">
<iconify-icon height="24" icon="solar:clapperboard-play-linear" width="24"></iconify-icon>
</div>
<h3 className="text-lg font-medium text-white mb-2 tracking-tight">Moving Masterpieces</h3>
<p className="text-sm text-zinc-400 font-normal leading-relaxed">Not just static images. Generate fully animated camera paths, dynamic character movements, and complex physics simulations.</p>
</div>

<div className="rounded-2xl border border-white/5 bg-zinc-900/30 p-8 hover:bg-zinc-900/50 transition-colors">
<div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white">
<iconify-icon height="24" icon="solar:tag-price-linear" width="24"></iconify-icon>
</div>
<h3 className="text-lg font-medium text-white mb-2 tracking-tight">Always Free</h3>
<p className="text-sm text-zinc-400 font-normal leading-relaxed">Start creating without a credit card. Generous daily quotas let you explore your creativity without restrictive paywalls.</p>
</div>
</div>
</div>
</main>

<footer className="border-t border-white/5 py-12 bg-zinc-950 mt-auto">
<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-6">
<div className="flex items-center gap-2">
<div className="flex h-6 w-6 items-center justify-center rounded border border-white/10 bg-white/5">
<iconify-icon className="text-white" height="14" icon="solar:box-linear" width="14"></iconify-icon>
</div>
<span className="text-sm font-medium tracking-tighter text-zinc-400">MV</span>
</div>
<div className="flex items-center gap-6">
<a className="text-xs font-normal text-zinc-500 hover:text-white transition-colors" href="#">Twitter</a>
<a className="text-xs font-normal text-zinc-500 hover:text-white transition-colors" href="#">GitHub</a>
<a className="text-xs font-normal text-zinc-500 hover:text-white transition-colors" href="#">Discord</a>
</div>
<p className="text-xs font-normal text-zinc-600">
                © 2024 MV Inc. All rights reserved.
            </p>
</div>
</footer>

    </>
  );
}
