import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



        lucide.createIcons();
    
    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      

<nav className="bg-[#0f172a] w-full h-14 flex items-center px-4 md:px-6 fixed top-0 z-50">
<a className="group flex items-center gap-2 text-slate-300 hover:text-white transition-colors text-sm font-medium" href="#">
<i className="w-4 h-4 text-slate-400 group-hover:text-white transition-colors" data-lucide="arrow-left"></i>
            Back to Home
        </a>
</nav>

<main className="max-w-3xl mx-auto px-6 pt-24 pb-24">

<header className="mb-12 border-b border-slate-100 pb-8">
<h1 className="text-4xl font-semibold text-slate-900 tracking-tight mb-3">Terms of Service</h1>
<p className="text-lg font-medium text-slate-900 mb-1">Fundable Investor System</p>
<div className="text-sm text-slate-500 space-y-1">
<p>Operated by PrimeSource Solutions LLC</p>
<p>Effective Date: [INSERT LAUNCH DATE]</p>
</div>
</header>

<div className="space-y-6 text-base leading-relaxed">
<p>
                Welcome to the Fundable Investor System (the "Service"), a digital product operated by PrimeSource Solutions LLC ("Company," "we," "us," or "our"), a limited liability company registered in Washington, D.C. By accessing or purchasing the Service, you ("User," "you," or "your") agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not access or use the Service.
            </p>
<p>
                Please read these Terms carefully before making a purchase or using any part of the Service.
            </p>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">1. Definitions</h2>
<ul className="list-disc pl-5 space-y-3 marker:text-slate-400">
<li className="pl-1">
<span className="font-semibold text-slate-900">"Service"</span> refers to the Fundable Investor System digital product, including the Funding Readiness Framework, Wizard Reference Guide, Automated Borrower Packet Wizard, and all bonus tools (Investor Document Checklist, Lender Conversation Prep Guide, Contractor Vetting Guide, and Renovation Cost Estimator), as well as any related content, materials, and updates provided through the website.
                    </li>
<li className="pl-1">
<span className="font-semibold text-slate-900">"Offering Memorandum"</span> refers to the PDF borrower presentation document generated by the Automated Borrower Packet Wizard based on information you provide.
                    </li>
<li className="pl-1">
<span className="font-semibold text-slate-900">"Presentation"</span> refers to one complete use of the Automated Borrower Packet Wizard resulting in one generated Offering Memorandum.
                    </li>
<li className="pl-1">
<span className="font-semibold text-slate-900">"Website"</span> refers to the Fundable Investor System website and all pages accessible through it behind the membership paywall.
                    </li>
</ul>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">2. Eligibility</h2>
<p>
                    You must be at least 18 years of age to purchase or use the Service. By purchasing or accessing the Service, you represent and warrant that you are at least 18 years old and have the legal capacity to enter into a binding agreement.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">3. Account Registration and Access</h2>
<p className="mb-4">To access the Service, you must create an account through our membership platform. You agree to:</p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">Provide accurate and complete information during registration</li>
<li className="pl-1">Maintain the security of your login credentials</li>
<li className="pl-1">Notify us immediately of any unauthorized access to your account</li>
<li className="pl-1">Not share your account credentials with any third party</li>
</ul>
<p>
                    You are responsible for all activity that occurs under your account. Your purchase grants access to one individual user only.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">4. Purchase and Payment</h2>
<p className="mb-4">
                    The Fundable Investor System is available for a one-time payment of $249 USD. This purchase includes lifetime access to the Service, including the Funding Readiness Framework, Wizard Reference Guide, Automated Borrower Packet Wizard (3 presentations included), and all bonus tools.
                </p>
<p className="mb-4">
                    All payments are processed securely through Stripe. By completing a purchase, you agree to Stripe's terms of service and authorize the charge to your selected payment method.
                </p>
<p>
                    Additional presentation packets may be purchased separately at the following prices: +1 Investor Packet for $79 USD, +2 Investor Packets for $139 USD, or +3 Investor Packets for $199 USD. Pricing for additional packets is subject to change without notice, though any price displayed at the time of your purchase will be honored.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">5. What Your Purchase Includes</h2>
<p className="mb-4">Your one-time purchase of $249 includes:</p>
<ul className="list-disc pl-5 space-y-3 marker:text-slate-400">
<li className="pl-1"><span className="font-semibold text-slate-900">Funding Readiness Framework:</span> An educational slide deck covering lender evaluation criteria, fundability concepts, and self-assessment guidance.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Wizard Reference Guide:</span> A step-by-step companion guide with field-by-field instructions, sample responses, and pro tips for completing the wizard.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Automated Borrower Packet Wizard (3 presentations):</span> A guided form that generates a professional Offering Memorandum in PDF format based on the information you provide.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Investor Document Checklist:</span> A reference checklist of documents lenders typically request, organized by category.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Lender Conversation Prep Guide:</span> A preparation guide for lender conversations.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Contractor Vetting Guide:</span> A reference guide with interview questions, red flags, and contract essentials for evaluating contractors.</li>
<li className="pl-1"><span className="font-semibold text-slate-900">Renovation Cost Estimator:</span> An interactive tool for organizing and estimating renovation costs by category.</li>
</ul>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">6. Refund Policy</h2>
<p className="mb-4">
                    We offer a full refund within fourteen (14) days of purchase, provided that the Automated Borrower Packet Wizard has not been used to generate a presentation. Once a presentation has been generated through the wizard, all sales are final and no refund will be issued, as the core deliverable of the Service has been produced.
                </p>
<p className="mb-4">
                    During the 14-day refund window, you have full access to the Funding Readiness Framework, Wizard Reference Guide, and all bonus tools to evaluate the Service before using the wizard.
                </p>
<p>
                    To request a refund, contact us at <a className="text-blue-600 hover:text-blue-700 hover:underline" href="#">info@fundableinvestor.com</a>. Refunds will be processed through Stripe to your original payment method within 5-10 business days.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">7. Intellectual Property</h2>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">7a. Company Ownership</h3>
<p className="mb-4">
                    The Fundable Investor System, including all educational content, frameworks, templates, wizard logic, form designs, slide decks, bonus tools, website design, branding, and all related materials are the exclusive intellectual property of PrimeSource Solutions LLC. All rights are reserved.
                </p>
<p className="mb-6">
                    You may not copy, reproduce, distribute, modify, reverse-engineer, resell, or create derivative works from any part of the Service, in whole or in part, without prior written consent from the Company.
                </p>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">7b. Your Generated Content</h3>
<p className="mb-4">
                    The Offering Memorandum generated through the wizard is created using your information and our proprietary template. You own the content you input into the wizard and the resulting Offering Memorandum document for your personal and professional use in presenting to lenders.
                </p>
<p>
                    However, the underlying template design, structure, formatting, and wizard logic remain the property of PrimeSource Solutions LLC. You may not extract, replicate, or redistribute the template structure for any purpose.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">8. Acceptable Use</h2>
<p className="mb-4">You agree to use the Service only for its intended purpose: preparing professional borrower presentation materials for use in real estate financing. You agree not to:</p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">Share, distribute, or resell the Service, any generated documents, or any component of the system to third parties</li>
<li className="pl-1">Use the Service to create materials for others on a commercial or for-profit basis</li>
<li className="pl-1">Attempt to extract, reverse-engineer, or replicate any templates, wizard logic, or proprietary processes</li>
<li className="pl-1">Use the Service for any unlawful, fraudulent, or misleading purpose</li>
<li className="pl-1">Provide false or misleading information in the wizard with the intent to deceive lenders</li>
<li className="pl-1">Share your account login credentials with any other person</li>
</ul>
<p>Violation of these terms may result in immediate termination of your access without refund.</p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">9. Important Disclaimers</h2>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">9a. Not Financial, Legal, or Investment Advice</h3>
<p className="mb-4">
                    The Fundable Investor System is an educational and organizational tool. It is not financial advice, legal advice, investment advice, or lending advice. Nothing in this Service should be interpreted as a recommendation to pursue any specific investment, financing arrangement, or transaction.
                </p>
<p className="mb-4">
                    The Company is not a financial advisor, lender, broker, attorney, or fiduciary. We do not evaluate the viability of your deals, the accuracy of your financial information, or the suitability of any lending product for your situation.
                </p>
<p className="mb-6">
                    You are solely responsible for your investment decisions, the accuracy of information you provide to lenders, and any outcomes resulting from your use of the Service. We strongly recommend consulting with qualified financial, legal, and tax professionals before making any investment or financing decisions.
                </p>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">9b. No Guarantee of Funding or Approval</h3>
<p className="mb-6">
<span className="font-semibold text-slate-900">The Fundable Investor System does not guarantee that you will receive financing, loan approval, or any particular outcome from any lender.</span> The Service is designed to help you organize and present your information professionally. Lending decisions are made solely by lenders based on their own criteria, and we have no control over or involvement in those decisions.
                </p>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">9c. No Guarantee of Accuracy</h3>
<p>
                    The Offering Memorandum and all other outputs generated by the Service are based entirely on information you provide. The Company does not verify, validate, or guarantee the accuracy, completeness, or reliability of any information you input or any document generated by the Service. You are solely responsible for ensuring all information presented to lenders is accurate and truthful.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">10. Limitation of Liability</h2>
<p className="mb-4">
                    To the maximum extent permitted by applicable law, PrimeSource Solutions LLC, its owners, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to:
                </p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">Loss of profits, revenue, or business opportunities</li>
<li className="pl-1">Loan denial, unfavorable lending terms, or any financing outcome</li>
<li className="pl-1">Errors or inaccuracies in generated documents based on information you provided</li>
<li className="pl-1">Unauthorized access to your account due to your failure to maintain login security</li>
<li className="pl-1">Any decision made by a lender based on materials generated through the Service</li>
</ul>
<p>
                    In no event shall the Company's total liability exceed the amount you paid for the Service ($249 USD).
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">11. Indemnification</h2>
<p className="mb-4">
                    You agree to indemnify, defend, and hold harmless PrimeSource Solutions LLC, its owners, officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorney's fees) arising out of or related to:
                </p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">Your use of the Service</li>
<li className="pl-1">Your violation of these Terms</li>
<li className="pl-1">Any information you provide through the Service</li>
<li className="pl-1">Any documents you present to lenders or third parties using materials generated by the Service</li>
<li className="pl-1">Any investment or financing decisions you make</li>
</ul>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">12. Third-Party Services</h2>
<p className="mb-4">The Service integrates with and relies on third-party platforms to operate, including:</p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">Stripe for payment processing</li>
<li className="pl-1">Outseta for account authentication and membership management</li>
<li className="pl-1">JotForm for the Automated Borrower Packet Wizard</li>
</ul>
<p>
                    Your use of these third-party services is subject to their respective terms of service and privacy policies. The Company is not responsible for the performance, availability, or security of third-party services, and any disruptions or issues caused by third-party platforms are outside of our control.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">13. Service Availability and Modifications</h2>
<p className="mb-4">
                    We strive to maintain continuous access to the Service but do not guarantee uninterrupted availability. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.
                </p>
<p className="mb-4">
                    We reserve the right to modify, update, or discontinue any aspect of the Service at any time. If we make material changes that reduce the core functionality you purchased, we will make reasonable efforts to notify you. The addition of new features or content does not obligate us to maintain those features indefinitely.
                </p>
<p>
                    "Lifetime access" means access for the operational life of the Service. In the unlikely event the Service is permanently discontinued, we will provide a minimum of 90 days advance notice and make reasonable efforts to allow you to download any previously generated documents before access ends.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">14. Termination</h2>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">14a. Termination by Company</h3>
<p className="mb-4">
                    We reserve the right to suspend or terminate your access to the Service at any time if you violate these Terms or engage in fraudulent activity, or misuse the Service. In the event of termination for cause, no refund will be issued.
                </p>
<h3 className="text-lg font-medium text-slate-900 mt-6 mb-3">14b. Account Closure by You</h3>
<p className="mb-4">
                    You may request to close your account at any time by contacting us at <a className="text-blue-600 hover:text-blue-700 hover:underline" href="#">info@fundableinvestor.com</a>. Please note that account closure is different from a refund request:
                </p>
<ul className="list-disc pl-5 space-y-2 mb-4 marker:text-slate-400">
<li className="pl-1">
<span className="font-semibold text-slate-900">If within the 14-day refund window and the wizard has not been used:</span> You may request both a refund and account closure. Your access will be removed and your $249 will be refunded to your original payment method within 5-10 business days.
                    </li>
<li className="pl-1">
<span className="font-semibold text-slate-900">If the 14-day refund window has passed or the wizard has been used:</span> You may request account closure, but no refund will be issued. Your login access will be removed and your account data will be deleted within 30 days.
                    </li>
</ul>
<p>
                    In either case, we recommend downloading any generated Offering Memorandum documents before requesting account closure, as they will no longer be accessible after your account is removed.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">15. Governing Law and Dispute Resolution</h2>
<p className="mb-4">
                    These Terms shall be governed by and construed in accordance with the laws of the District of Columbia, without regard to its conflict of law provisions.
                </p>
<p className="mb-4">
                    Any disputes arising out of or related to these Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration administered in Washington, D.C. in accordance with the rules of the American Arbitration Association. Each party shall bear its own costs of arbitration.
                </p>
<p>
                    You agree that any dispute resolution proceedings will be conducted on an individual basis and not as part of a class, consolidated, or representative action.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">16. Changes to These Terms</h2>
<p className="mb-4">
                    We reserve the right to update or modify these Terms at any time. If we make material changes, we will notify you by email or by posting a notice on the Website. Your continued use of the Service after such changes constitutes acceptance of the updated Terms.
                </p>
<p>
                    We encourage you to review these Terms periodically. The date of the most recent update will always be displayed at the top of this page.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">17. Severability</h2>
<p>
                    If any provision of these Terms is found to be unenforceable or invalid by a court of competent jurisdiction, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">18. Entire Agreement</h2>
<p>
                    These Terms, together with our Privacy Policy, constitute the entire agreement between you and PrimeSource Solutions LLC regarding your use of the Fundable Investor System and supersede any prior agreements or understandings.
                </p>
</section>

<section>
<h2 className="text-xl font-semibold text-slate-900 tracking-tight mt-10 mb-4">19. Contact Information</h2>
<p className="mb-6">
                    If you have questions about these Terms, please contact us at:
                </p>
<div className="bg-slate-50 p-8 rounded-md border border-slate-100">
<p className="font-semibold text-slate-900 mb-2">PrimeSource Solutions LLC</p>
<div className="text-sm text-slate-600 space-y-1">
<a className="text-blue-600 hover:text-blue-700 hover:underline block mb-2" href="#">info@fundableinvestor.com</a>
<p>1717 N Street NW, STE #1</p>
<p>Washington, DC 20036</p>
</div>
</div>
</section>
</div>
</main>


    </>
  );
}
