import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2M6V79H761');



        lucide.createIcons();
    
    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      

<nav className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
<a className="font-serif text-3xl tracking-tight text-[#272125]" href="#">Oatmeal.</a>
<div className="hidden md:flex items-center gap-8">
<a className="text-base font-medium text-[#272125] hover:opacity-70 transition-opacity" href="#">Pricing</a>
<a className="text-base font-medium text-[#272125] hover:opacity-70 transition-opacity" href="#">About</a>
<a className="text-base font-medium text-[#272125] hover:opacity-70 transition-opacity" href="#">Docs</a>
</div>
<div className="flex items-center gap-4">
<a className="text-base font-medium text-[#272125] hover:opacity-70 transition-opacity hidden sm:block" href="#">Log in</a>
<a className="bg-[#272125] text-white px-5 py-2.5 rounded-full text-base font-medium hover:bg-[#272125]/90 transition-colors" href="#">Get started</a>
</div>
</nav>

<div className="max-w-[90rem] mx-auto px-4 sm:px-6 pt-4 pb-20">
<div className="relative bg-[#7A6470] rounded-[2rem] overflow-hidden pt-20 px-8 lg:px-20 min-h-[600px] flex flex-col lg:flex-row items-center lg:items-start isolate">

<div className="absolute inset-0 bg-[#2C2428] -z-20"></div>

<div className="absolute inset-0 grain-overlay opacity-30 mix-blend-overlay -z-10 pointer-events-none"></div>
<div className="w-full lg:w-1/2 flex flex-col items-center text-center lg:items-start lg:text-left pt-10 lg:pt-20 pb-20 lg:pb-32 z-10">
<a className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/5 px-4 py-1.5 text-sm font-medium text-white/90 hover:bg-white/10 transition-colors mb-8" href="#">
<span>Oatmeal raises 80M Series A funding</span>
<span className="w-px h-4 bg-white/20"></span>
<span className="flex items-center gap-1">Learn more <i className="w-3.5 h-3.5" data-lucide="chevron-right" strokeWidth="1.5"></i></span>
</a>
<h1 className="font-serif text-5xl sm:text-6xl lg:text-7xl leading-[1.05] tracking-tight text-white mb-6 max-w-2xl">
                    Customer support that feels like a conversation.
                </h1>
<p className="text-lg text-white/80 mb-10 max-w-lg font-light leading-relaxed">
                    Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.
                </p>
<form className="flex items-center w-full max-w-md bg-white/10 backdrop-blur-sm border border-white/10 rounded-full p-1.5 focus-within:ring-2 focus-within:ring-white/30 transition-all">
<input className="flex-1 bg-transparent border-none text-white placeholder:text-white/50 px-4 text-base font-medium focus:outline-none focus:ring-0" placeholder="Enter your email" type="email"/>
<button className="bg-white text-[#272125] px-6 py-3 rounded-full text-base font-medium hover:bg-white/90 transition-colors whitespace-nowrap flex items-center gap-2" type="submit">
                        Request invite <i className="w-4 h-4" data-lucide="arrow-right" strokeWidth="1.5"></i>
</button>
</form>
</div>
<div className="w-full lg:w-1/2 flex justify-center lg:justify-end lg:absolute lg:right-0 lg:bottom-0 lg:translate-y-16 lg:translate-x-12 z-10 mt-12 lg:mt-0">

<div className="w-full max-w-2xl bg-white rounded-t-2xl shadow-2xl overflow-hidden border border-black/10 flex text-sm flex-col sm:flex-row h-[500px]">

<div className="w-full sm:w-56 bg-[#FCFAFB] border-r border-black/5 p-4 flex flex-col gap-6 hidden sm:flex">
<div className="flex items-center justify-between border border-black/10 rounded-lg p-2 bg-white">
<span className="flex items-center gap-2 font-medium"><div className="w-5 h-5 bg-[#272125] rounded flex items-center justify-center text-white text-xs">C</div> CloudStar</span>
<i className="w-4 h-4 text-black/40" data-lucide="chevron-down" strokeWidth="1.5"></i>
</div>
<div className="flex items-center gap-3 px-2 text-black/60 font-medium">
<i className="w-4 h-4" data-lucide="search" strokeWidth="1.5"></i> Search <span className="ml-auto text-xs border border-black/10 rounded px-1.5 py-0.5">⌘K</span>
</div>
<div className="space-y-1 mt-2">
<div className="flex items-center gap-3 px-2 py-1.5 bg-black/5 rounded-md font-medium text-[#272125]">
<i className="w-4 h-4" data-lucide="inbox" strokeWidth="1.5"></i> My Inbox <span className="ml-auto text-xs text-black/50">6</span>
</div>
<div className="flex items-center gap-3 px-2 py-1.5 font-medium text-black/60">
<i className="w-4 h-4" data-lucide="user" strokeWidth="1.5"></i> Unassigned <span className="ml-auto text-xs text-black/50">10</span>
</div>
<div className="flex items-center gap-3 px-2 py-1.5 font-medium text-black/60">
<i className="w-4 h-4" data-lucide="clock" strokeWidth="1.5"></i> Assigned <span className="ml-auto text-xs text-black/50">3</span>
</div>
<div className="flex items-center gap-3 px-2 py-1.5 font-medium text-black/60">
<i className="w-4 h-4" data-lucide="file-text" strokeWidth="1.5"></i> Drafts <span className="ml-auto text-xs text-black/50">1</span>
</div>
<div className="flex items-center gap-3 px-2 py-1.5 font-medium text-black/60 mt-4">
<i className="w-4 h-4" data-lucide="archive" strokeWidth="1.5"></i> Archived
                            </div>
<div className="flex items-center gap-3 px-2 py-1.5 font-medium text-black/60">
<i className="w-4 h-4" data-lucide="alert-octagon" strokeWidth="1.5"></i> Spam
                            </div>
</div>
<div className="mt-4">
<div className="text-xs font-medium text-black/40 px-2 mb-2">Buckets</div>
<div className="space-y-2 text-black/60 font-medium px-2">
<div>Support requests</div>
<div>Bug reports</div>
<div>Feature requests</div>
<div>Internal</div>
</div>
</div>
</div>

<div className="flex-1 bg-white p-6 overflow-hidden flex flex-col gap-6">
<div className="font-medium text-base pb-4 border-b border-black/5">Your Inbox</div>

<div className="space-y-1 cursor-pointer">
<div className="flex justify-between items-start">
<div className="font-medium text-[#272125]">Trouble connecting Slack integration</div>
<div className="text-xs text-black/40">6h ago</div>
</div>
<div className="text-black/60 line-clamp-1 leading-relaxed">Our team is trying to connect Slack with CloudStar, but the authorization process fails wit...</div>
<div className="flex items-center gap-1.5 text-xs text-black/50 mt-2">
<div className="w-4 h-4 rounded-full bg-black/20 overflow-hidden"><img alt="" className="w-full h-full object-cover" src="https://assets.tailwindplus.com/avatars/10.webp?size=160"/></div>
                                Peter is responding...
                            </div>
</div>

<div className="space-y-1 cursor-pointer relative">
<div className="absolute -left-3 top-1.5 w-1.5 h-1.5 rounded-full bg-blue-500"></div>
<div className="flex justify-between items-start">
<div className="font-medium text-[#272125]">Missing files in shared workspace</div>
<div className="text-xs text-black/40">6h ago</div>
</div>
<div className="text-black/60 line-clamp-2 leading-relaxed">Yesterday I uploaded a set of project files to our shared workspace. Today, two of the files are no...</div>
<div className="flex items-center gap-1.5 text-xs text-black/50 mt-2">
<div className="w-4 h-4 rounded-full bg-black/20 overflow-hidden"><img alt="" className="w-full h-full object-cover grayscale" src="https://assets.tailwindplus.com/avatars/10.webp?size=160"/></div>
<span className="font-medium text-black/80">Alex</span> responded 5m ago
                            </div>
</div>

<div className="space-y-1 cursor-pointer">
<div className="flex justify-between items-start">
<div className="font-medium text-[#272125]">Billing discrepancy on latest invoice</div>
<div className="text-xs text-black/40">8h ago</div>
</div>
<div className="text-black/60 line-clamp-2 leading-relaxed">Our invoice for this month shows 10 Pro licenses, but we only have 8 active users. Can you review...</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div className="max-w-7xl mx-auto px-6 pb-24 pt-8">
<div className="flex flex-wrap justify-center md:justify-between items-center gap-10 opacity-70 grayscale">
<img alt="Quirk" className="h-6" src="https://assets.tailwindplus.com/logos/10.svg?color=black&amp;height=32"/>
<img alt="Concise" className="h-6" src="https://assets.tailwindplus.com/logos/11.svg?color=black&amp;height=32"/>
<img alt="Anomaly" className="h-6" src="https://assets.tailwindplus.com/logos/12.svg?color=black&amp;height=32"/>
<img alt="Pine Labs" className="h-6" src="https://assets.tailwindplus.com/logos/13.svg?color=black&amp;height=32"/>
<img alt="Orbital" className="h-6" src="https://assets.tailwindplus.com/logos/8.svg?color=black&amp;height=32"/>
<img alt="Artifact" className="h-6" src="https://assets.tailwindplus.com/logos/9.svg?color=black&amp;height=32"/>
</div>
</div>

<div className="max-w-7xl mx-auto px-6 py-20">
<div className="max-w-2xl mb-16">
<h2 className="font-serif text-4xl sm:text-5xl leading-[1.1] tracking-tight text-[#272125] mb-6">
                Everything you need to deliver personal, organized, and delightful support.
            </h2>
<p className="text-lg text-[#272125]/70 mb-6 leading-relaxed font-light">
                Work smarter, reply faster, and keep every customer conversation right where it belongs — in one simple inbox, where you can ignore it.
            </p>
<a className="inline-flex items-center gap-1.5 text-base font-medium text-[#272125] hover:opacity-70 transition-opacity" href="#">
                See how it works <i className="w-4 h-4" data-lucide="arrow-right" strokeWidth="1.5"></i>
</a>
</div>
<div className="grid md:grid-cols-3 gap-6">

<div className="bg-[#EFECEE] rounded-3xl p-2 pb-8 border border-black/[0.03]">
<div className="rounded-2xl overflow-hidden bg-white mb-6 aspect-[4/3] border border-black/5 relative">
<img alt="Shared Inbox" className="w-full h-full object-cover" src="https://assets.tailwindplus.com/screenshots/1.webp?left=1200&amp;top=736&amp;color=mauve"/>
</div>
<div className="px-6">
<h3 className="text-lg font-medium text-[#272125] mb-2 tracking-tight">Shared Inbox</h3>
<p className="text-base text-[#272125]/70 leading-relaxed font-light">Manage support emails together in real time — no more support email hot potato.</p>
</div>
</div>

<div className="bg-[#EFECEE] rounded-3xl p-2 pb-8 border border-black/[0.03]">
<div className="rounded-2xl overflow-hidden bg-white mb-6 aspect-[4/3] border border-black/5 relative">
<img alt="Collision Detection" className="w-full h-full object-cover object-left" src="https://assets.tailwindplus.com/screenshots/1.webp?left=1800&amp;top=736&amp;color=mauve"/>
</div>
<div className="px-6">
<h3 className="text-lg font-medium text-[#272125] mb-2 tracking-tight">Collision Detection</h3>
<p className="text-base text-[#272125]/70 leading-relaxed font-light">See when a teammate is replying before you hit send. Goodbye duplicate replies.</p>
</div>
</div>

<div className="bg-[#EFECEE] rounded-3xl p-2 pb-8 border border-black/[0.03]">
<div className="rounded-2xl overflow-hidden bg-white mb-6 aspect-[4/3] border border-black/5 relative">
<img alt="Inbox Agent" className="w-full h-full object-cover object-left-top" src="https://assets.tailwindplus.com/screenshots/1.webp?right=1200&amp;bottom=736&amp;color=mauve"/>
</div>
<div className="px-6">
<h3 className="text-lg font-medium text-[#272125] mb-2 tracking-tight">Inbox Agent</h3>
<p className="text-base text-[#272125]/70 leading-relaxed font-light">Get valuable context without having to read through your customer's angry emails.</p>
</div>
</div>
</div>
</div>

<div className="relative py-24 overflow-hidden">
<div className="max-w-7xl mx-auto px-6 relative z-10">
<div className="max-w-2xl">
<div className="text-sm font-medium text-[#272125]/60 uppercase tracking-wider mb-4">Built for scale</div>
<h2 className="font-serif text-4xl sm:text-5xl leading-[1.1] tracking-tight text-[#272125] mb-6">
                    The inbox powering customer conversations everywhere.
                </h2>
<p className="text-lg text-[#272125]/70 leading-relaxed font-light mb-16 max-w-xl">
                    Oatmeal helps teams deliver personal, organized, and fast customer support across the world. From small startups to enterprise teams, we process millions of messages each month — using a massive network of low wage workers stationed around the globe.
                </p>
</div>
<div className="flex flex-col sm:flex-row gap-12 sm:gap-24">
<div className="flex flex-col border-l border-black/10 pl-6">
<div className="text-4xl font-medium tracking-tight text-[#272125] mb-2">2M+</div>
<div className="text-base text-[#272125]/70 max-w-[200px] leading-relaxed font-light">Emails manually processed every week across thousands of teams.</div>
</div>
<div className="flex flex-col border-l border-black/10 pl-6">
<div className="text-4xl font-medium tracking-tight text-[#272125] mb-2">99.98%</div>
<div className="text-base text-[#272125]/70 max-w-[200px] leading-relaxed font-light">Uptime — because your customers never stop complaining.</div>
</div>
</div>
</div>

<div className="absolute bottom-0 left-0 w-full h-[300px] -z-10 pointer-events-none opacity-20">
<svg className="w-full h-full text-[#272125]" preserveaspectratio="none" viewbox="0 0 1000 300">

<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="100" x2="100" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="200" x2="200" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="300" x2="300" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="400" x2="400" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="500" x2="500" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="600" x2="600" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="700" x2="700" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="800" x2="800" y1="0" y2="300"></line>
<line stroke="currentColor" stroke-dasharray="4 4" strokeWidth="1" x1="900" x2="900" y1="0" y2="300"></line>

<path d="M0,280 C200,280 400,200 600,150 C800,100 900,50 1000,20" fill="none" stroke="currentColor" strokeWidth="2"></path>
</svg>
</div>
</div>

<div className="max-w-5xl mx-auto px-6 py-32 text-center">
<h2 className="font-serif text-3xl sm:text-4xl lg:text-[2.75rem] leading-[1.15] tracking-tight text-[#272125] mb-12">
            “Oatmeal has completely transformed our customer support operations. The blend of AI efficiency and human empathy has allowed us to provide exceptional service while significantly reducing costs.”
        </h2>
<div className="flex flex-col items-center gap-4">
<img alt="Jordan Rogers" className="w-14 h-14 rounded-full object-cover" src="https://assets.tailwindplus.com/avatars/10.webp?size=160"/>
<div>
<div className="font-medium text-[#272125] text-base">Jordan Rogers</div>
<div className="text-base text-[#272125]/60 font-light">Founder at Anomaly</div>
</div>
</div>
</div>

<div className="max-w-7xl mx-auto px-6 py-24 border-t border-black/[0.05]">
<div className="grid md:grid-cols-2 gap-12 lg:gap-24">
<div>
<h2 className="font-serif text-4xl sm:text-5xl leading-[1.1] tracking-tight text-[#272125]">
                    Questions &amp; Answers
                </h2>
</div>
<div className="divide-y divide-black/10 border-t border-black/10 -mt-2">
<div className="py-6 flex justify-between items-center cursor-pointer group">
<span className="text-lg text-[#272125] font-light group-hover:opacity-70 transition-opacity">Do I need a credit card to start the free trial?</span>
<i className="w-5 h-5 text-black/40" data-lucide="plus" strokeWidth="1.5"></i>
</div>
<div className="py-6 flex justify-between items-center cursor-pointer group">
<span className="text-lg text-[#272125] font-light group-hover:opacity-70 transition-opacity">Can my whole team use the same inbox?</span>
<i className="w-5 h-5 text-black/40" data-lucide="plus" strokeWidth="1.5"></i>
</div>
<div className="py-6 flex justify-between items-center cursor-pointer group">
<span className="text-lg text-[#272125] font-light group-hover:opacity-70 transition-opacity">Is the AI agent actually a bunch of people in India?</span>
<i className="w-5 h-5 text-black/40" data-lucide="plus" strokeWidth="1.5"></i>
</div>
<div className="py-6 flex justify-between items-center cursor-pointer group">
<span className="text-lg text-[#272125] font-light group-hover:opacity-70 transition-opacity">Does Oatmeal replace my email client?</span>
<i className="w-5 h-5 text-black/40" data-lucide="plus" strokeWidth="1.5"></i>
</div>
</div>
</div>
</div>

<div className="max-w-7xl mx-auto px-6 py-24 border-t border-black/[0.05]">
<h2 className="font-serif text-4xl sm:text-5xl leading-[1.1] tracking-tight text-[#272125] mb-16">
            Pricing to fit your business needs.
        </h2>
<div className="grid md:grid-cols-3 gap-6">

<div className="bg-[#F0EDEF] rounded-3xl p-8 flex flex-col h-full border border-black/[0.03]">
<div className="mb-8">
<h3 className="text-2xl font-medium tracking-tight text-[#272125] mb-2">Starter</h3>
<div className="flex items-baseline gap-1 mb-4">
<span className="text-3xl font-medium tracking-tight text-[#272125]">$12</span>
<span className="text-base text-[#272125]/60">/mo</span>
</div>
<p className="text-base text-[#272125]/70 font-light leading-relaxed">Small teams getting started with shared inboxes</p>
</div>
<ul className="space-y-4 mb-10 flex-1">
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Shared inbox for up to 2 mailboxes
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Tagging &amp; assignment
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Private notes
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Automatic replies
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Email support
                    </li>
</ul>
<button className="w-full bg-[#E5E0E3] text-[#272125] py-3 rounded-full text-base font-medium hover:bg-[#DCD6D9] transition-colors border border-black/[0.05]">
                    Start free trial
                </button>
</div>

<div className="bg-[#EAE6E8] rounded-3xl p-8 flex flex-col h-full border border-black/[0.05] relative shadow-sm">
<div className="absolute top-8 right-8 bg-black/10 text-[#272125] text-xs font-medium px-2.5 py-1 rounded-full">
                    Most popular
                </div>
<div className="mb-8 pr-24">
<h3 className="text-2xl font-medium tracking-tight text-[#272125] mb-2">Growth</h3>
<div className="flex items-baseline gap-1 mb-4">
<span className="text-3xl font-medium tracking-tight text-[#272125]">$49</span>
<span className="text-base text-[#272125]/60">/mo</span>
</div>
<p className="text-base text-[#272125]/70 font-light leading-relaxed">Growing teams needing collaboration and insights</p>
</div>
<ul className="space-y-4 mb-10 flex-1">
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Everything in Starter
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Inbox Agent
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Unlimited mailboxes
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Collision detection
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Snippets and templates
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Reporting dashboard
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Slack integration
                    </li>
</ul>
<button className="w-full bg-[#272125] text-white py-3 rounded-full text-base font-medium hover:bg-[#272125]/90 transition-colors shadow-md">
                    Start free trial
                </button>
</div>

<div className="bg-[#F0EDEF] rounded-3xl p-8 flex flex-col h-full border border-black/[0.03]">
<div className="mb-8">
<h3 className="text-2xl font-medium tracking-tight text-[#272125] mb-2">Pro</h3>
<div className="flex items-baseline gap-1 mb-4">
<span className="text-3xl font-medium tracking-tight text-[#272125]">$299</span>
<span className="text-base text-[#272125]/60">/mo</span>
</div>
<p className="text-base text-[#272125]/70 font-light leading-relaxed">Support-focused organizations and larger teams</p>
</div>
<ul className="space-y-4 mb-10 flex-1">
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Everything in Growth
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Custom roles &amp; permissions
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> Automation engine
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> API access
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> SLA tracking
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> SSO support
                    </li>
<li className="flex items-start gap-3 text-base text-[#272125]/80 font-light">
<i className="w-5 h-5 text-black/40 mt-0.5 shrink-0" data-lucide="check" strokeWidth="1.5"></i> SOC 2 compliance
                    </li>
</ul>
<button className="w-full bg-[#E5E0E3] text-[#272125] py-3 rounded-full text-base font-medium hover:bg-[#DCD6D9] transition-colors border border-black/[0.05]">
                    Start free trial
                </button>
</div>
</div>
</div>

<div className="max-w-4xl mx-auto px-6 py-32 text-center border-t border-black/[0.05]">
<h2 className="font-serif text-4xl sm:text-5xl leading-[1.1] tracking-tight text-[#272125] mb-6">
            Ready to make customer support feel simple again?
        </h2>
<p className="text-lg text-[#272125]/70 mb-10 leading-relaxed font-light max-w-2xl mx-auto">
            Join hundreds of teams using Oatmeal to deliver faster, friendlier email support — using a massive network of low wage workers stationed around the globe
        </p>
<div className="flex flex-col sm:flex-row items-center justify-center gap-4">
<a className="w-full sm:w-auto bg-[#272125] text-white px-8 py-3 rounded-full text-base font-medium hover:bg-[#272125]/90 transition-colors shadow-md text-center" href="#">
                Start free trial
            </a>
<a className="w-full sm:w-auto px-8 py-3 rounded-full text-base font-medium text-[#272125] hover:bg-black/5 transition-colors flex items-center justify-center gap-2" href="#">
                Book a demo <i className="w-4 h-4" data-lucide="chevron-right" strokeWidth="1.5"></i>
</a>
</div>
</div>

<footer className="bg-[#EFECEE] border-t border-black/[0.05] pt-20 pb-12 mt-10">
<div className="max-w-7xl mx-auto px-6">
<div className="grid grid-cols-2 md:grid-cols-5 gap-8 mb-20">
<div>
<div className="text-base font-medium text-[#272125] mb-6">Product</div>
<ul className="space-y-4">
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Features</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Pricing</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Integrations</a></li>
</ul>
</div>
<div>
<div className="text-base font-medium text-[#272125] mb-6">Company</div>
<ul className="space-y-4">
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">About</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Careers</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Blog</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Press Kit</a></li>
</ul>
</div>
<div>
<div className="text-base font-medium text-[#272125] mb-6">Resources</div>
<ul className="space-y-4">
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Help Center</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">API Docs</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Status</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Contact</a></li>
</ul>
</div>
<div>
<div className="text-base font-medium text-[#272125] mb-6">Legal</div>
<ul className="space-y-4">
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Privacy Policy</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Terms of Service</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">Security</a></li>
</ul>
</div>
<div>
<div className="text-base font-medium text-[#272125] mb-6">Connect</div>
<ul className="space-y-4">
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">X</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">GitHub</a></li>
<li><a className="text-base text-[#272125]/60 hover:text-[#272125] transition-colors font-light" href="#">YouTube</a></li>
</ul>
</div>
</div>
<div className="text-base text-[#272125]/50 font-light">
                © 2025 Oatmeal, Inc.
            </div>
</div>
</footer>


    </>
  );
}
