import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    const originalAddEventListener = document.addEventListener;
    const originalWindowAddEventListener = window.addEventListener;
    
    document.addEventListener = function(event, callback, options) {
      if (event === 'DOMContentLoaded') {
        setTimeout(() => {
          try { callback(new Event('DOMContentLoaded')); } catch (e) { console.error(e); }
        }, 0);
      } else {
        originalAddEventListener.call(document, event, callback, options);
      }
    };
    
    window.addEventListener = function(event, callback, options) {
      if (event === 'load') {
        setTimeout(() => {
          try { callback(new Event('load')); } catch (e) { console.error(e); }
        }, 0);
      } else {
        originalWindowAddEventListener.call(window, event, callback, options);
      }
    };
    
    let onloadHandler = null;
    try {
      Object.defineProperty(window, 'onload', {
        set: function(fn) {
          onloadHandler = fn;
          setTimeout(() => {
            try { if (typeof fn === 'function') fn(); } catch (e) { console.error(e); }
          }, 0);
        },
        get: function() { return onloadHandler; },
        configurable: true
      });
    } catch (e) {}
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



tailwind.config = {
theme: {
extend: {
fontFamily: {
sans: ['Inter', 'sans-serif'],
},
colors: {
neutral: {
850: '#1f1f1f',
950: '#0a0a0a',
}
},
backgroundImage: {
'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
}
}
}
}

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
    
    return () => {
      document.addEventListener = originalAddEventListener;
      window.addEventListener = originalWindowAddEventListener;
      try { delete window.onload; } catch (e) {}
    };
  }, []);

  return (
    <>
      

<nav className="fixed top-0 w-full z-50 border-b border-white/5 glass">
<div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
<a className="flex items-center gap-2 group" href="#">
<div className="w-6 h-6 bg-white rounded-full flex items-center justify-center text-neutral-950">
<iconify-icon icon="lucide:aperture" strokeWidth="1.5" width="16"></iconify-icon>
</div>
<span className="text-white font-semibold tracking-tight text-sm group-hover:opacity-80 transition-opacity">LUMINA</span>
</a>
<div className="hidden md:flex items-center gap-8 text-sm font-medium text-neutral-400">
<a className="hover:text-white transition-colors" href="#work">Work</a>
<a className="hover:text-white transition-colors" href="#process">Process</a>
<a className="hover:text-white transition-colors" href="#solutions">Solutions</a>
<a className="hover:text-white transition-colors" href="#pricing">Pricing</a>
</div>
<div className="flex items-center gap-4">
<a className="hidden md:block text-sm text-neutral-400 hover:text-white transition-colors" href="#">Log in</a>
<a className="bg-white text-neutral-950 px-4 py-2 rounded-full text-xs font-semibold tracking-tight hover:bg-neutral-200 transition-colors flex items-center gap-2" href="#">
                    Start Project
                    <iconify-icon icon="lucide:arrow-right" strokeWidth="1.5" width="14"></iconify-icon>
</a>
</div>
</div>
</nav>

<header className="relative pt-32 pb-20 md:pt-48 md:pb-32 overflow-hidden">

<div className="absolute inset-0 hero-glow pointer-events-none"></div>
<div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[400px] bg-indigo-500/20 blur-[100px] rounded-full pointer-events-none opacity-20 mix-blend-screen"></div>
<div className="max-w-5xl mx-auto px-6 relative z-10 text-center">
<div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium text-indigo-300 mb-8 animate-fade-in-up">
<span className="relative flex h-2 w-2">
<span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
<span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500"></span>
</span>
                The Future of Advertising is Generative
            </div>
<h1 className="text-5xl md:text-7xl lg:text-8xl font-semibold text-white tracking-tighter leading-[1.1] mb-8 text-glow">
                Cinematic ads, <br/>
<span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-200 via-white to-indigo-200">generated by AI.</span>
</h1>
<p className="text-lg md:text-xl text-neutral-400 max-w-2xl mx-auto mb-10 leading-relaxed font-light">
                We craft award-winning storytelling and visual effects using proprietary AI models. High production value, fraction of the time.
            </p>
<div className="flex flex-col md:flex-row items-center justify-center gap-4">
<button className="h-12 px-8 rounded-full bg-white text-neutral-950 font-medium text-sm hover:bg-neutral-200 transition-all flex items-center gap-2">
<iconify-icon icon="lucide:play-circle" strokeWidth="1.5" width="18"></iconify-icon>
                    Watch Showreel
                </button>
<button className="h-12 px-8 rounded-full bg-neutral-900 border border-neutral-800 text-white font-medium text-sm hover:bg-neutral-800 transition-all flex items-center gap-2">
                    Book a Demo
                </button>
</div>
</div>

<div className="mt-20 max-w-6xl mx-auto px-6">
<div className="relative rounded-xl border border-white/10 bg-neutral-900/50 overflow-hidden aspect-video shadow-2xl shadow-indigo-500/10 group">

<div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&amp;w=2564&amp;auto=format&amp;fit=crop')] bg-cover bg-center opacity-40 group-hover:scale-105 transition-transform duration-700 ease-out"></div>
<div className="absolute inset-0 bg-gradient-to-t from-neutral-950 via-neutral-950/20 to-transparent"></div>
<div className="absolute inset-0 flex items-center justify-center">
<div className="w-20 h-20 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center cursor-pointer hover:scale-110 transition-transform">
<iconify-icon className="text-white ml-1" icon="lucide:play" strokeWidth="1.5" width="32"></iconify-icon>
</div>
</div>
<div className="absolute bottom-0 left-0 p-8">
<div className="text-xs font-mono text-indigo-400 mb-2">GENERATED IN 12s</div>
<div className="text-white font-medium text-xl tracking-tight">Project: Nebula One</div>
<div className="text-neutral-400 text-sm">Client: Space Xperience</div>
</div>
</div>
</div>
</header>

<section className="py-12 border-y border-white/5 bg-neutral-950">
<div className="max-w-7xl mx-auto px-6">
<p className="text-center text-xs text-neutral-500 mb-8 tracking-widest uppercase font-medium">Powering stories for innovative brands</p>
<div className="flex flex-wrap justify-center items-center gap-12 md:gap-20 opacity-50 grayscale hover:grayscale-0 transition-all duration-500">

<span className="text-xl font-bold tracking-tighter text-white">ACME<span className="text-indigo-500">.ai</span></span>
<span className="text-xl font-semibold tracking-tight text-white flex items-center gap-1"><div className="w-4 h-4 rounded-full bg-white"></div>Sphère</span>
<span className="text-xl font-medium tracking-widest text-white uppercase">Vortex</span>
<span className="text-xl font-bold italic tracking-tight text-white">Hyperion</span>
<span className="text-xl font-semibold tracking-tight text-white flex items-center gap-1"><iconify-icon icon="lucide:hexagon" width="20"></iconify-icon> Block</span>
</div>
</div>
</section>

<section className="py-24 relative" id="solutions">
<div className="max-w-7xl mx-auto px-6">
<div className="mb-16 md:mb-24">
<h2 className="text-3xl md:text-5xl font-semibold text-white tracking-tighter mb-6">Built for the modern <br/>marketing stack.</h2>
<p className="text-neutral-400 text-lg max-w-xl">We replace expensive production crews with neural networks, delivering Hollywood-grade commercials in days, not months.</p>
</div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-6">

<div className="group p-8 rounded-2xl bg-neutral-900/30 border border-white/5 hover:border-white/10 transition-all hover:bg-neutral-900/50">
<div className="w-12 h-12 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400 mb-6 group-hover:text-indigo-300 transition-colors">
<iconify-icon icon="lucide:wand-2" strokeWidth="1.5" width="24"></iconify-icon>
</div>
<h3 className="text-xl text-white font-medium mb-3 tracking-tight">Generative Scripting</h3>
<p className="text-sm text-neutral-400 leading-relaxed">
                        Our LLMs analyze your brand voice to generate compelling scripts, storyboards, and shot lists instantly.
                    </p>
</div>

<div className="group p-8 rounded-2xl bg-neutral-900/30 border border-white/5 hover:border-white/10 transition-all hover:bg-neutral-900/50">
<div className="w-12 h-12 rounded-lg bg-purple-500/10 flex items-center justify-center text-purple-400 mb-6 group-hover:text-purple-300 transition-colors">
<iconify-icon icon="lucide:video" strokeWidth="1.5" width="24"></iconify-icon>
</div>
<h3 className="text-xl text-white font-medium mb-3 tracking-tight">AI Video Synthesis</h3>
<p className="text-sm text-neutral-400 leading-relaxed">
                        Create photorealistic video content from text prompts. No cameras, actors, or locations required.
                    </p>
</div>

<div className="group p-8 rounded-2xl bg-neutral-900/30 border border-white/5 hover:border-white/10 transition-all hover:bg-neutral-900/50">
<div className="w-12 h-12 rounded-lg bg-pink-500/10 flex items-center justify-center text-pink-400 mb-6 group-hover:text-pink-300 transition-colors">
<iconify-icon icon="lucide:mic-2" strokeWidth="1.5" width="24"></iconify-icon>
</div>
<h3 className="text-xl text-white font-medium mb-3 tracking-tight">Neural Audio</h3>
<p className="text-sm text-neutral-400 leading-relaxed">
                        Professional voiceovers in any language and custom sound design generated specifically for your cut.
                    </p>
</div>
</div>
</div>
</section>

<section className="py-24 bg-neutral-900/20 border-t border-white/5" id="work">
<div className="max-w-7xl mx-auto px-6">
<div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
<div>
<h2 className="text-3xl md:text-4xl font-semibold text-white tracking-tighter mb-2">Selected Works</h2>
<p className="text-neutral-400 text-sm">Curated AI-generated campaigns.</p>
</div>
<a className="text-sm font-medium text-white flex items-center gap-2 hover:opacity-70 transition-opacity" href="#">
                    View all projects <iconify-icon icon="lucide:arrow-right" strokeWidth="1.5" width="16"></iconify-icon>
</a>
</div>
<div className="grid grid-cols-1 md:grid-cols-2 gap-8">

<div className="group relative aspect-[4/3] overflow-hidden rounded-xl border border-white/5">
<div className="absolute inset-0 bg-neutral-800 animate-pulse"></div> 

<div className="absolute inset-0 bg-gradient-to-br from-indigo-900/40 to-black/80"></div>
<div className="absolute inset-0 p-8 flex flex-col justify-end">
<div className="transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
<h3 className="text-2xl text-white font-medium tracking-tight mb-1">Neon Drift</h3>
<p className="text-neutral-400 text-sm opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-75">Automotive Commercial • Gen-2</p>
</div>
</div>
</div>

<div className="group relative aspect-[4/3] overflow-hidden rounded-xl border border-white/5">
<div className="absolute inset-0 bg-neutral-800 animate-pulse"></div>
<div className="absolute inset-0 bg-gradient-to-br from-purple-900/40 to-black/80"></div>
<div className="absolute inset-0 p-8 flex flex-col justify-end">
<div className="transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
<h3 className="text-2xl text-white font-medium tracking-tight mb-1">Eco Future</h3>
<p className="text-neutral-400 text-sm opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-75">Sustainability Campaign • Midjourney + Pika</p>
</div>
</div>
</div>
</div>
</div>
</section>

<section className="py-24 relative overflow-hidden">

<div className="absolute top-1/2 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-white/10 to-transparent"></div>
<div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-12 text-center relative z-10">
<div>
<div className="text-4xl md:text-5xl font-semibold text-white tracking-tighter mb-2">10x</div>
<div className="text-sm font-medium text-indigo-400 uppercase tracking-wide">Faster Delivery</div>
<p className="text-xs text-neutral-500 mt-2">Compared to traditional agencies</p>
</div>
<div>
<div className="text-4xl md:text-5xl font-semibold text-white tracking-tighter mb-2">1/5</div>
<div className="text-sm font-medium text-indigo-400 uppercase tracking-wide">The Cost</div>
<p className="text-xs text-neutral-500 mt-2">Budget efficiency maximized</p>
</div>
<div>
<div className="text-4xl md:text-5xl font-semibold text-white tracking-tighter mb-2">8k</div>
<div className="text-sm font-medium text-indigo-400 uppercase tracking-wide">Resolution</div>
<p className="text-xs text-neutral-500 mt-2">Upscaled for cinema displays</p>
</div>
</div>
</section>

<section className="py-24 bg-neutral-900/10" id="process">
<div className="max-w-4xl mx-auto px-6">
<h2 className="text-3xl font-semibold text-white tracking-tighter text-center mb-16">From Concept to Render</h2>
<div className="space-y-12">

<div className="flex gap-6">
<div className="flex flex-col items-center">
<div className="w-8 h-8 rounded-full border border-indigo-500/50 bg-indigo-500/10 text-indigo-400 flex items-center justify-center text-xs font-bold">1</div>
<div className="flex-1 w-[1px] bg-white/10 my-2"></div>
</div>
<div className="pb-8">
<h4 className="text-lg text-white font-medium mb-2">Prompt Engineering</h4>
<p className="text-neutral-400 text-sm leading-relaxed max-w-lg">We translate your marketing goals into complex prompt chains optimized for the latest video generation models.</p>
</div>
</div>

<div className="flex gap-6">
<div className="flex flex-col items-center">
<div className="w-8 h-8 rounded-full border border-white/10 bg-white/5 text-neutral-400 flex items-center justify-center text-xs font-bold">2</div>
<div className="flex-1 w-[1px] bg-white/10 my-2"></div>
</div>
<div className="pb-8">
<h4 className="text-lg text-white font-medium mb-2">Generation &amp; Iteration</h4>
<p className="text-neutral-400 text-sm leading-relaxed max-w-lg">Generating hundreds of variations. We curate the best shots, consistent characters, and perfect lighting.</p>
</div>
</div>

<div className="flex gap-6">
<div className="flex flex-col items-center">
<div className="w-8 h-8 rounded-full border border-white/10 bg-white/5 text-neutral-400 flex items-center justify-center text-xs font-bold">3</div>
</div>
<div>
<h4 className="text-lg text-white font-medium mb-2">Post-Production</h4>
<p className="text-neutral-400 text-sm leading-relaxed max-w-lg">Upscaling, color grading, motion interpolation, and lip-syncing to ensure broadcast quality.</p>
</div>
</div>
</div>
</div>
</section>

<section className="py-32 relative overflow-hidden">
<div className="absolute inset-0 bg-gradient-to-b from-transparent to-indigo-900/10 pointer-events-none"></div>
<div className="max-w-3xl mx-auto px-6 text-center relative z-10">
<h2 className="text-4xl md:text-5xl font-semibold text-white tracking-tighter mb-6">Ready to tell your story?</h2>
<p className="text-neutral-400 mb-10 text-lg">Join the forward-thinking companies transforming their advertising with Lumina AI.</p>
<div className="flex flex-col sm:flex-row items-center justify-center gap-4">
<input className="w-full sm:w-auto h-12 px-6 rounded-full bg-white/5 border border-white/10 text-white placeholder-neutral-500 text-sm focus:outline-none focus:border-indigo-500/50 focus:bg-white/10 transition-all min-w-[280px]" placeholder="enter your email" type="email"/>
<button className="w-full sm:w-auto h-12 px-8 rounded-full bg-white text-neutral-950 font-semibold text-sm hover:bg-neutral-200 transition-colors">
                    Get Started
                </button>
</div>
<p className="mt-6 text-xs text-neutral-600">No credit card required for consultation.</p>
</div>
</section>

<footer className="border-t border-white/5 py-16 bg-neutral-950">
<div className="max-w-7xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-10">
<div className="col-span-2 md:col-span-1">
<a className="flex items-center gap-2 mb-6" href="#">
<div className="w-5 h-5 bg-neutral-800 rounded-full flex items-center justify-center text-white">
<iconify-icon icon="lucide:aperture" strokeWidth="1.5" width="12"></iconify-icon>
</div>
<span className="text-white font-semibold tracking-tight text-sm">LUMINA</span>
</a>
<p className="text-neutral-500 text-xs leading-relaxed max-w-xs">
                    Pioneering the intersection of artificial intelligence and cinematic advertising.
                </p>
<div className="flex gap-4 mt-6">
<a className="text-neutral-500 hover:text-white transition-colors" href="#"><iconify-icon icon="lucide:twitter" width="16"></iconify-icon></a>
<a className="text-neutral-500 hover:text-white transition-colors" href="#"><iconify-icon icon="lucide:instagram" width="16"></iconify-icon></a>
<a className="text-neutral-500 hover:text-white transition-colors" href="#"><iconify-icon icon="lucide:linkedin" width="16"></iconify-icon></a>
</div>
</div>
<div>
<h4 className="text-white text-sm font-medium mb-4">Product</h4>
<ul className="space-y-2 text-xs text-neutral-500">
<li><a className="hover:text-indigo-400 transition-colors" href="#">AI Video</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">ScriptGen</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Voice Synthesis</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Pricing</a></li>
</ul>
</div>
<div>
<h4 className="text-white text-sm font-medium mb-4">Company</h4>
<ul className="space-y-2 text-xs text-neutral-500">
<li><a className="hover:text-indigo-400 transition-colors" href="#">About</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Blog</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Careers</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Contact</a></li>
</ul>
</div>
<div>
<h4 className="text-white text-sm font-medium mb-4">Legal</h4>
<ul className="space-y-2 text-xs text-neutral-500">
<li><a className="hover:text-indigo-400 transition-colors" href="#">Privacy Policy</a></li>
<li><a className="hover:text-indigo-400 transition-colors" href="#">Terms of Service</a></li>
</ul>
</div>
</div>
<div className="max-w-7xl mx-auto px-6 mt-16 pt-8 border-t border-white/5 flex flex-col md:flex-row justify-between items-center text-xs text-neutral-600">
<p>© 2024 Lumina AI Agency. All rights reserved.</p>
<div className="flex items-center gap-2 mt-4 md:mt-0">
<div className="w-2 h-2 rounded-full bg-green-500"></div>
<span>Systems Operational</span>
</div>
</div>
</footer>

    </>
  );
}
