import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



        const { useState, useEffect, useMemo, useRef } = React;
        const { motion, AnimatePresence } = window.Motion;

        // --- Assets: Music & Real Images ---
        
        const musicTracks = [
            { title: "Focus Flow", url: "https://cdn.pixabay.com/audio/2022/05/27/audio_1808fbf07a.mp3" }, // Calm Piano
            { title: "Ambient Nature", url: "https://cdn.pixabay.com/audio/2022/10/05/audio_686121251c.mp3" }, // Soft Ambient
            { title: "Study Lo-Fi", url: "https://cdn.pixabay.com/audio/2021/11/01/audio_00fa5593f3.mp3" } // Chill
        ];

        // Real images from Unsplash (IDs for stability)
        const images = {
            world: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
            europe: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?auto=format&fit=crop&w=800&q=80",
            dike: "https://images.unsplash.com/photo-1605218427306-635ba2439af2?auto=format&fit=crop&w=800&q=80", // Dutch landscape
            randstad: "https://images.unsplash.com/photo-1562095648-5c4251786576?auto=format&fit=crop&w=800&q=80", // Utrecht/City
            binnenhof: "https://images.unsplash.com/photo-1596464679469-2f2220c36782?auto=format&fit=crop&w=800&q=80", // Den Haag
            port: "https://images.unsplash.com/photo-1574768565175-167ce914dc08?auto=format&fit=crop&w=800&q=80", // Rotterdam Port
            highway: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80", // Car/Road
            william: "https://images.unsplash.com/photo-1555819206-8153d100787e?auto=format&fit=crop&w=800&q=80", // Generic Historical Painting look
            voc: "https://images.unsplash.com/photo-1616787884488-812a64736f8a?auto=format&fit=crop&w=800&q=80", // Old Ship
            nightwatch: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/The_Night_Watch_-_Rembrandt_-_Rijksmuseum.jpg/800px-The_Night_Watch_-_Rembrandt_-_Rijksmuseum.jpg", // Actual Nightwatch (Public Domain fallback)
            rotterdam40: "https://images.unsplash.com/photo-1572957934661-d7a6b3252553?auto=format&fit=crop&w=800&q=80", // Old building/War concept
            anne: "https://images.unsplash.com/photo-1588665792945-8c0353c7cb3e?auto=format&fit=crop&w=800&q=80", // Book/Diary
            kingqueen: "https://images.unsplash.com/photo-1591544225992-04e4c361906a?auto=format&fit=crop&w=800&q=80", // Orange theme
            pm: "https://images.unsplash.com/photo-1555848962-6e79363ec58f?auto=format&fit=crop&w=800&q=80", // Suit/Politics
        };

        // --- Data: KNS Questions (with real images) ---
        const knsRaw = [
            ["In welk deel van de wereld ligt Nederland?", ["Azië", "Europa", "Afrika"], 1, images.world],
            ["Welk land ligt ten zuiden van Nederland?", ["Duitsland", "Frankrijk", "België"], 2, images.europe],
            ["Welk land ligt ten oosten van Nederland?", ["Engeland", "Duitsland", "België"], 1, images.europe],
            ["Welk land is groter dan Nederland?", ["Marokko", "Luxemburg", "Monaco"], 0, null],
            ["Wat betekent 'Nederland'?", ["Rijk land", "Laag land", "Water land"], 1, images.dike],
            ["Wat zie je op de foto?", ["Een berg", "Een dijk", "Een brug"], 1, images.dike],
            ["Welke stad ligt in de Randstad?", ["Maastricht", "Groningen", "Utrecht"], 2, images.randstad],
            ["Wat is de hoofdstad van Nederland?", ["Den Haag", "Rotterdam", "Amsterdam"], 2, images.randstad],
            ["In welke stad zit de regering?", ["Amsterdam", "Den Haag", "Utrecht"], 1, images.binnenhof],
            ["Waar ligt de grootste zeehaven?", ["Amsterdam", "Rotterdam", "IJmuiden"], 1, images.port],
            ["Zijn de wegen in Nederland druk of rustig?", ["Rustig", "Druk"], 1, images.highway],
            ["Wie ziet u op het plaatje?", ["Rembrandt", "Willem van Oranje", "Erasmus"], 1, images.william],
            ["Waren de VOC-schepen voor de handel of voor de visvangst?", ["Voor de visvangst", "Voor de handel", "Voor vakantie"], 1, images.voc],
            ["Wie schilderde de Nachtwacht?", ["Van Gogh", "Rembrandt", "Mondriaan"], 1, images.nightwatch],
            ["Welke stad is in 1940 gebombardeerd?", ["Utrecht", "Rotterdam", "Amsterdam"], 1, images.rotterdam40],
            ["Waarom is Anne Frank beroemd?", ["Ze was een koningin", "Ze schreef een dagboek", "Ze was een schilder"], 1, images.anne],
            ["Wie zijn dit?", ["De premier en zijn vrouw", "De koning en koningin", "Twee acteurs"], 1, images.kingqueen],
            ["Wie is de baas van de regering?", ["De koning", "De minister-president", "De burgemeester"], 1, images.pm],
            ["Is Nederland een democratie?", ["Ja", "Nee"], 0, images.binnenhof],
            ["Mag je discrimineren in Nederland?", ["Ja", "Nee"], 1, null]
        ];

        const knsData = knsRaw.map((item, id) => ({
            id: id + 1,
            q: item[0],
            a: item[1],
            c: item[2],
            img: item[3]
        }));

        // --- Data: Speaking Full Lists ---

        const speakingP1Raw = `Bij wie gaat u wonen in Nederland?
Hoe bent u hier gekomen?
Hoe gaat het met u?
Hoe gaat u naar uw werk?
Hoe laat begint u met werken?
Hoe laat gaat u 's avonds naar bed?
Hoe laat is het nu?
Hoe laat stopt u met werken?
Hoe laat wordt u 's ochtends wakker?
Hoe reist u meestal?
Hoe vaak bent u al in Nederland geweest?
Hoe vaak eet u op een dag?
Hoe vaak kijkt u tv?
Hoe vaak luistert u naar de radio?
Hoeveel broers en zussen hebt u?
Hoeveel dagen in de week werkt u?
Hoeveel jaar school hebt u gehad?
Hoeveel kinderen hebt u?
Hoeveel talen spreekt u?
In wat voor huis gaat u wonen in Nederland?
In welk land bent u geboren?
In welke plaats gaat u wonen in Nederland?
Met hoeveel mensen werkt u?
Naar welke muziek luistert u graag?
Op welke dagen werkt u?
Van welke muziek houdt u?
Waar bent u geboren?
Waar doet u boodschappen?
Waar heeft u Nederlands geleerd?
Waar woont u?
Waar woont uw familie?
Waarom leert u Nederlands?
Waarom wilt u naar Nederland?
Wanneer bent u blij?
Wanneer bent u geboren?
Wanneer doet u boodschappen?
Wanneer geeft u een feest?
Wanneer wilt u naar Nederland gaan?
Wat doet u graag buiten?
Wat doet u graag met uw familie?
Wat doet u graag met uw vrienden?
Wat doet u in het weekend?
Wat doet u in uw vrije tijd?
Wat doet u op een feestdag?
Wat drinkt u graag?
Wat eet u op een feest?
Wat eet u 's avonds?
Wat eet u 's ochtends?
Wat gaat u morgen doen?
Wat gaat u vandaag eten?
Wat hebt u geleerd op school?
Wat hebt u gisteren gedaan?
Wat hebt u gisteren gegeten?
Wat is uw adres?
Wat is uw telefoonnummer?
Wat kookt u graag?
Wat vindt u van de Nederlandse taal?
Wat vindt u van Nederland?
Wat vindt u van Nederlandse mensen?
Wat vindt u van uw huis?
Wat voor kleren draagt u vaak?
Wat voor kleren vindt u mooi?
Wat voor weer is het vandaag?
Wat voor werk wilt u doen?
Wat wilt u graag leren in Nederland?
Welk cadeau geeft u graag aan iemand?
Welk eten koopt u vaak?
Welk feest vindt u leuk?
Welk fruit eet u graag?
Welke dag is het vandaag?
Welke dieren vindt u leuk?
Welke groente eet u vaak?
Welke kleur vindt u mooi?
Welke maand is het nu?
Welke sport doet u?
Welke talen spreekt u?
Wie helpt u met Nederlands leren?
Wie wonen bij u in huis?`;

        const speakingP2Raw = `’s Avonds doe ik mijn ring af. Ik leg mijn ring altijd...
Aaliyah pakt eerst een kopje koffie. Daarna gaat ze...
Aaron gaat donderdag op reis. Hij vindt dat...
Aaron is dokter. Hij werkt...
Aaron is schilder. Hij schildert meestal...
Abdul stuurt zijn familie elke week een e-mail. Hij schrijft dan over...
Abel is op school. Hij heeft...
Achmed is klaar met school. Hij gaat...
Adam is aan het koken. Hij maakt...
Ahmed brengt zijn zoon naar het vliegveld. Zijn zoon gaat...
Aiden is bij de bakker. Hij wil...
Alec gaat naar school. Hij wil graag...
Alex gaat altijd met de trein. Ik ga graag met...
Alex is ziek. Hij heeft pijn aan...
Alex wil nieuwe schoenen. Hij gaat naar...
Ali kan niet goed lopen. Hij heeft pijn aan zijn...
Ali werkt in een fabriek. Hij wil...
Alice werkt in een ziekenhuis. Zij is daar...
Amel sport graag. Sporten is...
Ana is niet blij met haar huis. Ze vindt haar huis...
Ananda is aan het koken. Ze maakt...
Andres werkt op het land. Het werk is...
Anisa maakt huiswerk op de computer. Ze doet dat...
Anna is bij de dokter. Ze krijgt...
Anna’s huis is te klein. Ze wil snel...
Anna wast de paprika. Ze gaat…
Arif wacht op de bus. De bus komt...
Arjun moet elke dag reizen naar zijn werk. Hij werkt in...
Arnold is schoonmaker. Hij werkt in...
Ayla eet haar ontbijt snel op. Ze heeft...
Aziz loopt elke dag. Hij loopt naar...
Barry is geslaagd voor zijn examen. Hij krijgt...
Bart gaat bijna elke dag met de auto. Hij rijdt dan naar...
Berat geeft les. Hij vertelt over...
Bilal gaat naar de bioscoop. Hij gaat met zijn...
Bob houdt niet van zwemmen. Hij gaat liever...
Brenda doet een opleiding. Ze moet iedere avond...
Brian fietst naar zijn werk. Hij gaat liever niet…
Cai werkt met hout. Hij maakt...
Carla drinkt een glas water. Ze doet dat...
Carlos gaat vroeg slapen. Hij is...
Carlos is vrij. Hij gaat...
Carlos maakt muziek. Hij doet dat...
Carmen eet elke dag een banaan. Soms eet ze ook...
Caro eet vaak appels. Zij houdt ook van…
Caro gaat vaak met de bus naar school. Soms gaat ze...
Chen verkoopt bloemen. Ze doet dat...
Chris heeft een computer. Hij gebruikt de computer om te...
Chris neemt zijn pillen. Hij heeft pijn in zijn...
Christina belt met haar moeder. Ze praten over...
Christo heeft dorst. Hij drinkt een glas...
Claire kijk uit het raam. Ze kijkt naar...
Claire leert Nederlands. Ze vindt Nederlands...
Dael heeft veel geld. Hij werkt...
Dafne kan goed zingen. Ze kan ook goed...
Daniël heeft pijn aan zijn kies. Hij gaat naar...
Daniëlle gaat studeren. Ze pakt haar...
Dany heeft hoofdpijn. Ze wil...
Dario zit op school. Hij maakt een...
Dave is niet blij met zijn haar. Zijn haar is...
Dave lust geen koffie. Hij drinkt liever...
Dave werkt in een café. Hij moet daar...
David en Maria rijden naar de stad. Ze zoeken...
David heeft een boot. Hij gebruikt de boot om te...
David is dik. Hij eet elke dag...
David werkt in een ziekenhuis. Hij is...
De auto van Leah is kapot. Ze brengt de auto naar...
De baas van Patrick is boos. Patrick vindt dat...
De broer van Souad heeft een baby gekregen. Souad is...
De bus is vaak te laat. Paul vindt dat...
De bus rijdt langzaam. Lia wil...
De dochter van Sophia kijkt veel tv. Ze kan beter gaan...
De dokter praat met Sofia. De dokter geeft Sofia...
De familie Wang woont in een leuke straat. Zij wonen naast...
De kinderen lezen samen. In het boek staat...
De klas is leeg. Iedereen is...
De koning is op het nieuws. Hij vertelt over...
De les begint om 11 uur. Hetty gaat...
De les is afgelopen. We willen nu...
De man belt in de auto. Dat is...
De stoel is kapot. Jaimy gaat de stoel...
De trein is vol. Hanna moet...
De zoon van Samira gaat naar school. Samira vindt dat...
Debra zit op school. Ze maakt veel…
Die sinaasappel is oud. Je moet de sinaasappel...
Diego houdt van koken. Hij kookt graag voor...
Dimitri werkt in een garage. Hij maakt...
Dina wast haar handen. Haar handen zijn…
Dunya gaat naar een feest. Het feest is van haar...
Dylan is bij de tandarts. Dat is...
Edgar en Joko koken samen. Ze doen dat...
Een mug heeft mij geprikt. Nu krijg ik...
Eliza is morgen jarig. Haar vader…
Ella bakt koekjes. Ze bakt de koekjes voor...
Emma doet een opleiding. Dat is...
Emma schrijft alles op. Daarna gaat ze...
Emma wast haar handen. Ze gaat...
Er is ingebroken bij Ben. Hij belt naar...
Er komen nieuwe huizen in onze buurt. Ik vind dat...
Er ligt rommel op straat. Dat is...
Esma wil lerares worden. Zij gaat...
Esra is ziek. Ze vindt dat...
Fanya is op de markt. Ze zoekt...
Farid is zanger. Hij moet vandaag...
Fatima koopt een fiets. Ze gaat met de fiets naar…
Fausia stapt uit de boot. Ze loopt naar...
Felipe houdt van lezen. Hij koopt elke maand...
Felix gaat elke dag zwemmen. Soms gaat hij ook...
Fico woont ver van zijn werk. Hij moet elke dag...
Filip maakt de badkamer schoon. Hij vindt dat...
Filiz koopt een nieuwe jas. Ze koopt ook...
Finn kijkt nu televisie. Hij gaat straks...
Franco gaat verhuizen. Zijn nieuwe huis heeft een...
Frank leest de krant. Hij leest over..
Fred gaat naar school. Hij heeft les tot...
Gabriel maakt een opdracht. Hij doet dat...
Gary leest zijn dochter voor. Lezen is...
Gary woont bij het strand. Hij wil het liefst...
Gina kijkt vaak televisie. Ze houdt van programma's over...
Grace houdt niet van groente. Ze vindt dat...
Halil rijdt in een vrachtwagen. Hij vindt dat...
Han heeft zijn diploma gehaald. Hij gaat nu...
Hannah eet graag vis. Ze haalt die vis...
Hannah leert Nederlands. Ze leert ook...
Hannah maakt haar huis schoon. Ze doet dat...
Harold is niet alleen. Hij heeft...
Harry is gevallen. Hij heeft...
Hassan maakt zijn brommer. Het wiel is...
Hassan werkt in een restaurant. Hij leert daar...
Het bord van Sahid is gevallen. Sahid is...
Het eten is heel warm! Je moet...
Het fruit is op. Ik ga nu naar...
Het huis van Tania is heel groot. Haar huis heeft...
Het is donker. Ik reis dan liever niet met...
Het is druk in de stad. Er zijn veel...
Het is druk op de weg. Emir vindt dat...
Het is druk op het station. Er zijn veel...
Het is koud in het huis van Faiz. Hij wil...
Het is slecht weer. Gaan we met de...?
Het is stil in de klas. De leerlingen...
Het is warm vandaag. Ana wil...
Het is zondag. Eva gaat op zondag altijd naar...
Het regent al de hele dag. William wil...
Het regent onderweg. Marta wil...
Het vliegveld is ver weg. We gaan naar het vliegveld met...
Hetty is klaar met koken. Ze roept...
Hiba houdt van katten. Ze houdt niet van…
Hue wil naar de markt. Ze gaat...
Ibrahim heeft een kar met spullen. Hij brengt de spullen...
Iedereen is blij. Het is...
Ik ben op zoek naar het treinstation. Kunt u mij...
Ik ben ziek. Ik ga morgen niet...
Ik drink geen alcohol. Ik drink wel graag...
Ik eet graag brood. Ik houd niet van...
Ik eet nooit druiven. Ik vind druiven...
Ik eet nooit kip. Dat vind ik...
Ik ga een taart maken. Wil jij...?
Ik ga morgen brood kopen. Brood koop ik meestal...
Ik ga naar de huisarts. Hij geeft mij...
Ik ga naar mijn zus. Mijn zus woont...
Ik ga straks naar Hamza. Hij is...
Ik ga vaak met de bus. Ik ga dan naar...
Ik heb deze krant gelezen. Wil jij de krant nu..?
Ik heb een computer met internet. Die gebruik ik...
Ik heb een nieuwe tafel gekocht. Wil jij mijn oude tafel...?
Ik heb geen auto. Een auto is...
Ik heb soep gemaakt. Wil jij mijn soep...?
Ik heb wortels gekocht. Ik koop de wortels voor...
Ik houd van tekenen. Ik teken...
Ik lees het nieuws op mijn telefoon. Mijn man leest het nieuws...
Ik lees vaak. Ik lees graag...
Ik wil zieke mensen helpen. Ik vind dat...
Imani vindt school leuk. Zij houdt van...
In de stad rijden veel brommers. Ik vind dat...
In een grote stad wonen veel mensen. Ik vind dat...
In het eten zitten pepers. Ik vind dat...
Inez en Luis bouwen een huis. Het huis heeft nog geen...
Inez gaat naar een concert. Ze gaat...
Is dat boek leuk? Ik wil het boek ook graag...
Isa heeft pauze. Ze belt met haar...
Isabel speelt graag met haar pop. Soms speelt ze ook met...
Ismet heeft groenten in zijn tuin. Hij gaat de groenten...
Ivan is niet blij met zijn werk. Hij vindt zijn werk te...
Iwan wil gezond zijn. Hij drinkt geen...
Jack koopt tomaten. Hij koopt ook...
Jack wil de muziek niet horen. Hij vindt de muziek...
Jacques is leraar. Hij geeft...
Jada maakt pannenkoeken voor haar familie. Zij doet dat...
Jafar houdt niet van dansen. Hij vindt dansen...
Jakob zoekt een taxi. Hij wil...
Jamal heeft een nieuwe scooter. Hij kan nu...
Jamal woont in een flatgebouw. Hij wil graag...
Jamila maakt kleding. Die kleding is voor...
Jan heeft zijn arm gebroken. Hij moet nu...
Janek heeft koorts. Zijn moeder geeft hem...
Janine leert Nederlands. Ze praat met de lerares over...
Jara is zwanger. Ze krijgt...
Jasmine gaat naar het ziekenhuis. In het ziekenhuis zijn...
Jason gaat graag naar school. Hij kan goed...
Jessie houdt van muziek. Ze speelt graag...
Jessie moet langer werken vandaag. Ze mag pas om acht uur...
Jessy koopt een kaartje. Ze gaat…
Jie is op de markt. Hij ziet...
Jim gaat naar het strand. Het is daar...
Jim heeft haast. Hij moet snel naar...
Jim staat voor de school. Hij wacht op…
Jing maakt de borden schoon. Daarna gaat ze...
Joel heeft een vieze keuken. Hij moet...
Johan heeft veel boeken. Hij houdt van…
Johanna doet suiker in haar koffie. Suiker is...
John en zijn dochter bakken samen taart. Ze vinden dat...
John houdt van paarden. Hij vindt paarden...
John woont bij een bos. Hij gaat daar elk weekend...
Johnny is moe. Hij wil...
Johnny is vrij op zaterdag. Hij gaat...
Jonas werkt altijd buiten. Dat is...
Josh heeft de hele dag gelopen. Hij wil nu...
Josh koopt een krant in de winkel. Hij koopt ook...
Judy leest een tijdschrift. Soms leest ze ook...
Julio gaat verhuizen. Hij moet...
Karim heeft pijn in zijn rug. Hij moet...
Karim leest het weerbericht. Het weer wordt...
Karima gaat naar de dokter. Ze voelt zich...
Karin kijkt naar het journaal. Ze doet dat...
Karl gaat met zijn dochter naar de dierentuin. Ze kijken naar...
Katya volgt een opleiding. Ze wil...
Kay zoekt een nieuw huis. Hij vindt zijn oude huis...
Kei eet 's avonds met zijn familie. Dat vindt hij...
Kenji rookt al twintig jaar sigaretten. Dat is...
Kenny zoekt op internet. Hij zoekt naar...
Kevin eet een salade met paprika. In de salade zit ook...
Kevin heeft huiswerk. Hij moet veel...
Kevin werkt in een restaurant. Hij maakt vandaag...
Kevin zit in de klas. Hij heeft een vraag over...
Khalid is visser. Na het werk is hij vaak...
Kris werkt in de tuin. Hij doet dat…
Kun je mij een lepel geven? Ik wil...
Kun je mij naar het station brengen. Ik moet op tijd...
Kwasi is chauffeur. Hij rijdt...
Laila moet elke dag vroeg opstaan. Soms is ze...
Laiqa werkt elke dag buiten. Ze houdt van...
Laura heeft veel collega's. Ze gaan samen...
Lea eet graag in een restaurant. Ze vindt dat...
Lea gaat naar haar kleinzoon. Ze geeft hem...
Lea is in het ziekenhuis. Ze wil...
Lei speelt op straat. Dat is...
Leon is verkouden. Hij moet...
Leon speelt gitaar. Hij doet dat...
Leyla slaapt samen met haar zus in een kamer. Zij vinden dat...
Li en Chen gaan iets drinken. Ze drinken...
Lia wil meer geld voor haar werk. Dan kan ze...
Liam kan niet goed zien. Hij moet...
Lily gaat elke dinsdag sporten. Ze eet daarna altijd...
Lin zoekt werk. Ze gaat naar...
Ling wil iets eten. Ze eet liever geen...
Linn heeft niet goed geslapen. Ze blijft...
Liyen gaat vanavond koken. Ze gaat eerst...
Lizzie en haar moeder gaan met het vliegtuig. Lizzie vindt dat...
Loes is ziek. Zij gaat vandaag…
Louis gaat op de scooter naar zijn werk. Hij doet dat...
Louis gebruikt de computer. Hij wil...
Lucia heeft haar been gebroken. Nu kan ze niet...
Lucia wil nieuw werk. Ze vindt haar oude werk...
Madee heeft een auto. Ze gaat met de auto naar...
Mae heeft een nieuwe auto. Ze kan nu...
Mag ik jouw brommer lenen? Mijn brommer is...
Mai kijkt niet naar het nieuws. Ze vindt het nieuws...
Maja maakt soep. De soep is...
Malik gaat vandaag niet sporten. Hij heeft geen...
Malik heeft een nieuwe bank gekocht. De oude bank was...
Mandy eet vaak chips als ze een film kijkt. Ze eet soms ook...
Manuel is buschauffeur. Hij rijdt...
Marco heeft zin in koffie. Hij wil ook...
Marco is ziek. Hij belt...
Maria heeft griep. Ze moet...
Maria kan goed koken. Ze kookt meestal...
Maria leest een boek. Ze vindt het...
Maria leest op zondag de krant. Ze leest soms...
Mariam praat met de leraar. Mariam praat ook met haar...
Martin eet elke ochtend een ei. Zijn vrouw eet meestal...
Martin stelt een vraag aan de docent. De vraag gaat over...
Maryam kookt voor Dina. Maryam maakt...
Masha kan vandaag zitten in de bus. Soms moet ze...
Max draagt een helm op zijn werk. Dat moet van zijn...
Max voetbalt graag. Voetballen is…
Maya doet de gordijnen dicht. Ze gaat...
Megan gaat vandaag verhuizen. Ze woont straks...
Melissa wacht op het station. Ze wacht op haar...
Mevrouw Perez heeft geen auto meer. Nu moet ze...
Mia maakt zelf kleren. Vandaag maakt ze een...
Mia moet snel naar huis. Ze gaat met de...
Michael houdt niet van tennis. Hij houdt meer van...
Michelle kijkt vaak films. Ze houdt van films over...
Michelle maakt huiswerk. Ze vindt het huiswerk...
Miguel stopt met werken. Hij is...
Mijn auto is kapot. Nu moet ik...
Mijn baas fietst elke dag. Ik doe dat...
Mijn benzine is op. Nu moet ik...
Mijn broer houdt niet van varen. Hij wordt altijd ziek op...
Mijn broer zingt veel. Hij is...
Mijn buurman maakt graag muziek. Dat vind ik...
Mijn opa gaat elke dag wandelen. Dat is...
Mijn opa zit op de bank. Hij kijkt naar...
Mijn telefoon is kapot. Nu kan ik niet...
Mijn trein vertrekt over een half uur. Ik ga nu...
Mijn vader heeft een paard. Hij gaat...
Mijn vader loopt met een stok. Mijn vader is...
Mijn vader luistert graag naar het nieuws. Hij luistert ook naar...
Mijn zus rijdt altijd hard. Ik vind dat...
Mike heeft pijn aan zijn been. Hij heeft ook pijn aan zijn...
Mina werkt bij de supermarkt. Ze werkt daar…
Ming rijdt vaak op zijn scooter. Hij wil niet...
Mira heeft zin in koffie. Ze drinkt koffie met...
Mo en zijn familie spelen een spel. Daarna gaan ze...
Mo zit aan tafel. Hij schrijft een brief aan zijn...
Mohammed maakt auto’s. Dat vindt hij...
Monica maakt graag foto's. Ze maakt het liefst foto's van...
Monica wil graag een huis met een tuin. Ze vindt dat...
Myra en Liz gaan naar een café. Ze willen graag...
Nadia heeft kip gekocht. Ze gaat de kip eerst...
Naima wil kapper worden. Ze leert...
Nancy en Oscar zitten in de bioscoop. Ze vinden de film...
Nasir zoekt een nieuw huis. Hij wil een huis met...
Nasira woont bij de supermarkt. Ze woont ook bij...
Nick wil naar zijn familie. Hij reist met...
Nick zoekt werk. Hij wil graag werken bij...
Nicole gaat naar de tandarts. Ze heeft pijn aan haar...
Nikki zoekt een nieuw huis. Ze wil graag...
Nina speelt in de tuin. Ze speelt met...
Noah leest een bericht in de krant. Het bericht gaat over...
Noor werkt in een winkel. Ze verkoopt broeken en ook...
Nora en Souffian wonen in een dorp. Ze wonen liever...
Odara ruimt het huis op. Ze legt de kleren...
Olga is ziek. Ze moet...
Omar koopt vis. Hij koopt ook...
Omid leest 's ochtends altijd eerst de krant. Daarna gaat hij...
Ons dak is kapot. Wij moeten...
Orma heeft leuke buren. Ze gaat met haar buren...
Pablo gaat vaak met de trein. Hij gaat dan naar...
Pablo speelt gitaar. Hij oefent...
Pari gaat elke dag met de bus. Vandaag gaat ze...
Pascal vindt zijn werk moeilijk. Hij wil...
Paul gaat vroeg naar bed. Hij moet morgen...
Paul heeft honger. Zijn moeder geeft hem...
Paul viert zijn verjaardag. Hij is...
Paula heeft een brief gekregen. De brief is van...
Pedro doet de lamp aan. Het is...
Pedro woont op een boerderij. Hij heeft daar...
Peter maakt machines. Hij werkt vaak...
Peter speelt met zijn zoon. Ze zijn...
Philip fietst op de weg. De weg is...
Philippa zit in de tuin. Ze zit ook vaak...
Pia woont naast een park. Ze gaat daar...
Priya doet een opleiding. Later wordt ze...
Priya maakt saus. Haar dochters willen...
Quito eet vandaag niet thuis. Hij eet...
Rachel zingt vaak alleen. Soms zingt ze ook...
Rafael heeft een telefoon. Hij belt elke dag met zijn...
Raheem heeft een fijn huis. Hij woont daar met...
Rahime heeft Nederlandse les. Ze vindt haar docent...
Rasha werkt op een kantoor. Het kantoor is...
Remi werkt op de markt. Hij verkoopt…
Rhonda is haar sleutel kwijt. Nu moet ze...
Rico eet vaak snoep. Snoep is slecht voor...
Rico krijgt een prik. Hij is...
Rima en haar dochter zijn in de keuken. Haar dochter wil...
Robin loopt snel naar school. Hij is...
Romeo werkt op een school. Hij geeft les aan...
Roy wil zijn vriend spreken. Hij gaat...
Ryan heeft weinig geld. Hij werkt...
Ryan wil een film zien. Hij gaat naar...
Sabir heeft een nieuwe baan. Hij werkt bij...
Saïd heeft vakantie. Hij gaat...
Saïd is te laat op zijn werk. Zijn baas is...
Salih is bakker. Hij werkt meestal...
Salim snijdt de uien. Zijn vrouw gaat...
Sam is vandaag op school. Hij gaat straks naar…
Sam loopt het lokaal uit. Hij gaat...
Samir is te laat voor de trein. Hij moet nu...
Samira heeft een gesprek met haar baas. Ze praten over...
Samira gaat naar haar ouders. Ze gaan samen...
Samira heeft pijn aan haar rug. Ze kan niet goed...
Samuel heeft vandaag les. Hij gaat morgen...
Samuel praat met zijn baas. Hij vraagt...
Samuel vindt de pauze leuk. Hij gaat dan...
Sandra moet vandaag veel doen. Ze moet...
Sanne kan niet goed koken. Het eten is...
Sara lacht. Zij is…
Sara praat met haar buurvrouw. Ze praten over...
Sarah is nooit ziek. Zij voelt zich altijd...
Sari zoekt een cursusboek. Ze gaat naar...
Sarina reist met de bus. Zij gaat naar…
Sasha eet niet altijd thuis. Ze gaat vaak naar...
Sasha gaat naar de bioscoop. Ze kijkt...
Sasha heeft een hond. Ze heeft ook...
Savita gaat solliciteren. Ze wil...
Scott doet een opleiding. Hij vindt leren...
Selim kan zijn broer niet bellen. Hij stuurt zijn broer een...
Shaila draagt een rugzak naar school. In de rugzak zit...
Shanna heeft haar diploma. Ze is...
Shing heeft zijn arm gebroken. Hij mag niet...
Shun wil niet eten. Hij wil liever...
Siham volgt een cursus. Ze leert...
Simon bouwt een huis. Het huis wordt..
Simon wil leraar worden. Hij moet veel...
Simone leest graag een krant. Ze koopt hem...
Sita bakt een taart. Haar kinderen vinden…
Sita geeft taart aan haar opa. Hij vindt dat...
Sjaak werkt in een fabriek. Daar werkt hij...
Sonia zit in de bus. Ze gaat naar...
Sonya houdt van muziek. Ze luistert...
Sophia houdt van rijst. Ze kookt dat...
Sophie is vaak in het bos. Ze kijkt graag naar...
Sou eet graag maïs. Ze eet maïs meestal met...
Souad koopt bananen op de markt. Ze koopt ook...
Stanley wil een groter huis. Hij wil ook...
Stefan belt met zijn zus. Zijn zus is...
Stefana vindt wandelen leuk. Ze doet dat...
Stephan moet sporten van de dokter. Hij gaat...
Steven is in het ziekenhuis. Hij gaat morgen...
Sven komt uit het ziekenhuis. Hij is...
Sylvia is kapper. Ze moet vandaag veel...
Tamal moet remmen. Hij ziet een...
Tanya is bakker. Ze verkoopt...
Tara wil een motor kopen. Een motor is...
Tara zoekt werk. Ze kijkt in...
Tariq eet alleen. Hij vindt dat...
Tess eet veel fruit. Fruit is...
Thirza wil later in het ziekenhuis werken. Ze moet eerst...
Thomas ligt in het ziekenhuis. Hij vindt dat...
Tim drinkt graag koffie. Hij drinkt liever koffie dan…
Tim is jarig. Zijn zus geeft hem een...
Tirza koopt een nieuw bed. Ze koopt ook...
Tony eet brood. Hij eet het brood met...
Tuan zit op school. Hij heeft volgende week...
Veel mensen praten in de les. Nena vindt dat...
Vera doet suiker in haar thee. Haar thee wordt zo...
Victor heeft een nieuw huis. Hij gaat morgen...
Wayan drinkt koffie met zijn buurman. Hij vindt dat...
We gaan mijn broer ophalen. Hij heeft geen...
Wij willen wat leuks doen. We gaan...
Wil je mijn huis zien? Ik woon hier...
Wil jij op mijn kinderen passen? Ik ga vanavond...
William neemt een drankje. Dat helpt tegen...
Xuan is in de supermarkt. Ze wil...
Yaira werkt bij een apotheek. Ze werkt daar...
Younes heeft veel vrienden. Hij gaat vaak met ze naar...
Yun eet 's ochtends niet veel. Ze eet dan alleen...
Yvonne doet haar spullen in dozen. Zij gaat morgen…
Zarina moet de vis eerst schoonmaken. Daarna gaat ze hem...
Zina kookt met veel kruiden. Zo wordt haar eten...
Zola maakt het huis schoon. Ze doet dat...`;

        const speakingP1Data = speakingP1Raw.split('\n').filter(l => l.trim().length > 0).map(q => ({ q, a: "Geef een persoonlijk antwoord." }));
        const speakingP2Data = speakingP2Raw.split('\n').filter(l => l.trim().length > 0).map(s => ({ s, a: "Maak de zin logisch af." }));

        // --- Colors ---
        const colors = {
            orange: "text-[#FF4F00]",
            bgOrange: "bg-[#FF4F00]",
            blue: "text-[#1E3A8A]", 
            bgBlue: "bg-[#1E3A8A]",
        };

        // --- Components ---

        const Icon = ({ icon, className }) => (
            <iconify-icon icon={icon} class={className} width="24" stroke-width="1.5"></iconify-icon>
        );

        const Button = ({ children, onClick, variant = 'primary', className = '', icon, disabled }) => {
            const base = "w-full py-4 rounded-xl font-medium tracking-tight flex items-center justify-center gap-3 transition-all active:scale-[0.98]";
            const styles = variant === 'primary' 
                ? `${colors.bgBlue} text-white shadow-lg shadow-blue-900/10 hover:bg-blue-900` 
                : variant === 'secondary'
                ? "bg-white border border-slate-200 text-slate-700 hover:bg-slate-50"
                : `${colors.bgOrange} text-white shadow-lg shadow-orange-500/20 hover:bg-orange-600`;
            
            const disabledStyles = disabled ? "opacity-50 cursor-not-allowed active:scale-100" : "";

            return (
                <button onClick={onClick} disabled={disabled} class={`${base} ${styles} ${disabledStyles} ${className}`}>
                    {icon && <Icon icon={icon} />}
                    {children}
                </button>
            );
        };

        const Card = ({ children, className = '' }) => (
            <div class={`bg-white rounded-2xl border border-slate-100 shadow-sm ${className}`}>
                {children}
            </div>
        );

        const ProgressBar = ({ current, total, color = 'bg-slate-900' }) => {
            const width = Math.min(100, (current / total) * 100);
            return (
                <div class="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                    <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${width}%` }}
                        class={`h-full ${color}`}
                    />
                </div>
            );
        };

        const MusicPlayer = () => {
            const [isPlaying, setIsPlaying] = useState(false);
            const [currentTrackIndex, setCurrentTrackIndex] = useState(0);
            const [volume, setVolume] = useState(0.5);
            const [isExpanded, setIsExpanded] = useState(false);
            const audioRef = useRef(null);

            useEffect(() => {
                if (audioRef.current) {
                    audioRef.current.volume = volume;
                    if (isPlaying) {
                        const playPromise = audioRef.current.play();
                        if (playPromise !== undefined) {
                            playPromise.catch(error => console.log("Auto-play prevented"));
                        }
                    } else {
                        audioRef.current.pause();
                    }
                }
            }, [isPlaying, volume, currentTrackIndex]);

            const nextTrack = () => setCurrentTrackIndex((prev) => (prev + 1) % musicTracks.length);

            return (
                <div class="fixed bottom-6 right-6 z-50">
                    <audio 
                        ref={audioRef} 
                        src={musicTracks[currentTrackIndex].url} 
                        loop
                        onEnded={nextTrack}
                    />
                    
                    <AnimatePresence>
                        {isExpanded && (
                            <motion.div 
                                initial={{ opacity: 0, scale: 0.9, y: 10 }}
                                animate={{ opacity: 1, scale: 1, y: 0 }}
                                exit={{ opacity: 0, scale: 0.9, y: 10 }}
                                class="absolute bottom-16 right-0 bg-white border border-slate-200 shadow-xl rounded-2xl p-4 w-64 mb-2"
                            >
                                <div class="flex items-center justify-between mb-3">
                                    <span class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Achtergrondmuziek</span>
                                    <button onClick={nextTrack} class="text-xs text-blue-600 hover:text-blue-800 font-medium">Volgende Track</button>
                                </div>
                                <p class="text-sm font-medium text-slate-900 mb-3 truncate">🎵 {musicTracks[currentTrackIndex].title}</p>
                                
                                <div class="flex items-center gap-2 mb-1">
                                    <Icon icon="solar:volume-small-linear" className="text-slate-400" />
                                    <input 
                                        type="range" 
                                        min="0" max="1" step="0.01" 
                                        value={volume}
                                        onChange={(e) => setVolume(parseFloat(e.target.value))}
                                        class="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                                    />
                                    <Icon icon="solar:volume-loud-linear" className="text-slate-400" />
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>

                    <button 
                        onClick={() => isExpanded ? setIsExpanded(false) : (isPlaying ? setIsExpanded(true) : (setIsPlaying(true) || setIsExpanded(true)))}
                        class={`h-12 w-12 rounded-full shadow-lg flex items-center justify-center transition-all duration-300 ${isPlaying ? 'bg-blue-900 text-white scale-105' : 'bg-white text-slate-600 border border-slate-200 hover:scale-105'}`}
                    >
                        <Icon icon={isPlaying ? "solar:music-note-slider-bold" : "solar:music-note-linear"} className="text-xl" />
                    </button>
                    {isExpanded && (
                         <button 
                            onClick={() => setIsPlaying(!isPlaying)}
                            class="absolute -top-1 -right-1 h-5 w-5 bg-slate-900 text-white rounded-full text-xs flex items-center justify-center border-2 border-white"
                        >
                            <Icon icon={isPlaying ? "solar:pause-bold" : "solar:play-bold"} />
                        </button>
                    )}
                </div>
            );
        };

        // --- Views ---

        const Dashboard = ({ onNavigate, stats }) => {
            return (
                <div class="p-6 h-full flex flex-col max-w-md mx-auto">
                    <header class="mb-8 mt-4">
                        <h1 class={`text-xl font-semibold tracking-tight ${colors.blue}`}>Inburgering A1</h1>
                        <p class="text-slate-500 text-sm">Officiële Oefensuite</p>
                    </header>

                    <div class="flex-1 space-y-6 overflow-y-auto pb-6 no-scrollbar">
                        <section>
                            <h2 class="text-xs font-semibold text-slate-400 mb-3 uppercase tracking-wider">Modules</h2>
                            
                            {/* KNS Card */}
                            <motion.div whileTap={{ scale: 0.98 }} onClick={() => onNavigate('kns-menu')} class="cursor-pointer group">
                                <Card className="p-5 border-l-4 border-l-[#1E3A8A] hover:shadow-lg transition-all relative overflow-hidden">
                                    <div class="absolute top-0 right-0 p-4 opacity-5 group-hover:scale-110 transition-transform duration-500">
                                        <Icon icon="solar:book-2-linear" className="text-6xl text-[#1E3A8A]" />
                                    </div>
                                    <div class="flex items-start justify-between mb-4">
                                        <div class={`p-3 rounded-xl bg-blue-50 ${colors.blue}`}>
                                            <Icon icon="solar:book-2-linear" />
                                        </div>
                                    </div>
                                    <h3 class="text-lg font-semibold text-slate-900 mb-1">KNS</h3>
                                    <p class="text-sm text-slate-500 mb-4">Kennis van de Nederlandse Maatschappij</p>
                                    <ProgressBar current={stats.kns} total={knsData.length} color={colors.bgBlue} />
                                    <div class="mt-2 text-xs text-slate-400 font-medium">{stats.kns}/{knsData.length} Beheerst</div>
                                </Card>
                            </motion.div>

                            {/* Speaking Card */}
                            <motion.div whileTap={{ scale: 0.98 }} onClick={() => onNavigate('speaking-menu')} class="cursor-pointer group mt-4">
                                <Card className="p-5 border-l-4 border-l-[#FF4F00] hover:shadow-lg transition-all relative overflow-hidden">
                                     <div class="absolute top-0 right-0 p-4 opacity-5 group-hover:scale-110 transition-transform duration-500">
                                        <Icon icon="solar:chat-round-dots-linear" className="text-6xl text-[#FF4F00]" />
                                    </div>
                                    <div class="flex items-start justify-between mb-4">
                                        <div class={`p-3 rounded-xl bg-orange-50 ${colors.orange}`}>
                                            <Icon icon="solar:pen-new-linear" />
                                        </div>
                                    </div>
                                    <h3 class="text-lg font-semibold text-slate-900 mb-1">Spreken & Schrijven</h3>
                                    <p class="text-sm text-slate-500 mb-4">Vragen en aanvulzinnen (Complete lijst)</p>
                                    <ProgressBar current={stats.speaking} total={100} color={colors.bgOrange} />
                                    <div class="mt-2 text-xs text-slate-400 font-medium">{stats.speaking} Oefeningen Gedaan</div>
                                </Card>
                            </motion.div>
                        </section>
                    </div>
                </div>
            );
        };

        const KNSGame = ({ mode, onBack, onComplete }) => {
            const [index, setIndex] = useState(0);
            const [selected, setSelected] = useState(null); 
            const [score, setScore] = useState(0);
            const [showFeedback, setShowFeedback] = useState(false);
            const [isFinished, setIsFinished] = useState(false);
            const [timer, setTimer] = useState(0); // Seconds

            const currentQ = knsData[index];

            useEffect(() => {
                let interval;
                if (mode === 'exam' && !isFinished) {
                    interval = setInterval(() => setTimer(t => t + 1), 1000);
                }
                return () => clearInterval(interval);
            }, [mode, isFinished]);

            const handleAnswer = (choiceIdx) => {
                if (showFeedback && mode === 'practice') return;
                
                setSelected(choiceIdx);
                
                if (mode === 'practice') {
                    setShowFeedback(true);
                    if (choiceIdx === currentQ.c) setScore(s => s + 1);
                }
            };

            const handleNext = () => {
                // In Exam mode, score is calculated on 'Next' to prevent changing answer
                if (mode === 'exam') {
                    if (selected === currentQ.c) setScore(s => s + 1);
                }

                if (index < knsData.length - 1) {
                    setIndex(i => i + 1);
                    setSelected(null);
                    setShowFeedback(false);
                } else {
                    // Final Question logic
                    if (mode === 'exam' && selected === currentQ.c) setScore(s => s + 1);
                    setIsFinished(true);
                    onComplete(score + (mode === 'practice' && selected === currentQ.c ? 0 : 0));
                }
            };

            const formatTime = (s) => {
                const mins = Math.floor(s / 60);
                const secs = s % 60;
                return `${mins}:${secs.toString().padStart(2, '0')}`;
            };

            if (isFinished) {
                const passed = (score / knsData.length) >= 0.7; // 70% to pass
                return (
                    <div class="p-6 h-full flex flex-col justify-center items-center max-w-md mx-auto text-center">
                        <div class={`w-24 h-24 rounded-full flex items-center justify-center mb-6 ${passed ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'}`}>
                            <Icon icon={passed ? "solar:cup-star-linear" : "solar:close-circle-linear"} className="text-5xl" />
                        </div>
                        <h2 class="text-2xl font-semibold tracking-tight text-slate-900 mb-2">
                            {passed ? "Geslaagd!" : "Niet geslaagd"}
                        </h2>
                        <p class="text-slate-500 mb-8">{passed ? "Gefeliciteerd, u kent de stof goed." : "Blijf oefenen om te slagen."}</p>
                        
                        <div class="grid grid-cols-2 gap-4 w-full mb-8">
                            <div class="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm">
                                <p class="text-xs text-slate-400 uppercase font-medium">Score</p>
                                <p class={`text-2xl font-semibold ${passed ? 'text-green-600' : 'text-slate-900'}`}>{score}/{knsData.length}</p>
                            </div>
                            <div class="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm">
                                <p class="text-xs text-slate-400 uppercase font-medium">Tijd</p>
                                <p class="text-2xl font-semibold text-slate-900">{formatTime(timer)}</p>
                            </div>
                        </div>
                        <Button onClick={onBack}>Terug naar Dashboard</Button>
                    </div>
                );
            }

            return (
                <div class="p-6 h-full flex flex-col max-w-md mx-auto">
                    {/* Header */}
                    <div class="flex items-center justify-between mb-4">
                        <button onClick={onBack} class="p-2 -ml-2 text-slate-400 hover:text-slate-600">
                            <Icon icon="solar:arrow-left-linear" />
                        </button>
                        
                        {mode === 'exam' && (
                            <div class="flex items-center gap-2 px-3 py-1 bg-slate-100 rounded-full">
                                <Icon icon="solar:clock-circle-linear" className="text-slate-500" />
                                <span class="text-sm font-medium text-slate-700 font-mono">{formatTime(timer)}</span>
                            </div>
                        )}
                        
                        <span class="text-sm font-medium text-slate-500">
                            Vraag {index + 1} <span class="text-slate-300">/ {knsData.length}</span>
                        </span>
                    </div>

                    {/* Progress */}
                    <div class="mb-6">
                        <ProgressBar current={index + 1} total={knsData.length} color={mode === 'exam' ? colors.bgOrange : colors.bgBlue} />
                    </div>

                    {/* Question Content */}
                    <div class="flex-1 overflow-y-auto no-scrollbar pb-4">
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -20 }}
                            transition={{ duration: 0.3 }}
                        >
                            {/* Realistic Image */}
                            {currentQ.img && (
                                <div class="mb-6 rounded-2xl overflow-hidden border border-slate-200 shadow-sm relative group">
                                    <div class="absolute inset-0 bg-slate-200 animate-pulse z-0"></div>
                                    <img 
                                        src={currentQ.img} 
                                        alt="Situatie" 
                                        class="w-full h-56 object-cover relative z-10" 
                                        loading="lazy"
                                    />
                                    {mode === 'practice' && <div class="absolute top-2 right-2 bg-black/50 backdrop-blur text-white text-[10px] px-2 py-1 rounded">Voorbeeld</div>}
                                </div>
                            )}

                            <h2 class="text-xl font-semibold tracking-tight text-slate-900 mb-6 leading-relaxed">
                                {currentQ.q}
                            </h2>

                            <div class="space-y-3">
                                {currentQ.a.map((ans, idx) => {
                                    let stateStyle = "bg-white border-slate-200 text-slate-700 hover:border-blue-300";
                                    
                                    if (mode === 'practice' && showFeedback) {
                                        if (idx === currentQ.c) stateStyle = "bg-green-50 border-green-500 text-green-700";
                                        else if (selected === idx) stateStyle = "bg-red-50 border-red-500 text-red-700";
                                        else stateStyle = "bg-white border-slate-100 text-slate-400 opacity-50";
                                    } else if (selected === idx) {
                                        stateStyle = `${colors.bgBlue} border-transparent text-white shadow-md`;
                                    }

                                    return (
                                        <button
                                            key={idx}
                                            onClick={() => handleAnswer(idx)}
                                            disabled={showFeedback}
                                            class={`w-full p-4 rounded-xl border-2 text-left transition-all duration-200 flex items-center gap-4 ${stateStyle}`}
                                        >
                                            <div class={`w-6 h-6 rounded-full border flex items-center justify-center text-xs flex-shrink-0 font-bold
                                                ${selected === idx || (showFeedback && idx === currentQ.c) ? 'border-current' : 'border-slate-300 text-slate-400'}
                                            `}>
                                                {String.fromCharCode(65 + idx)}
                                            </div>
                                            <span class="font-medium text-sm">{ans}</span>
                                        </button>
                                    )
                                })}
                            </div>
                        </motion.div>
                    </div>

                    {/* Footer Action */}
                    <div class="mt-4 pt-4 border-t border-slate-100 bg-slate-50">
                        <Button 
                            onClick={handleNext} 
                            disabled={selected === null}
                            className={selected === null ? 'opacity-50 cursor-not-allowed' : ''}
                        >
                            {index === knsData.length - 1 ? "Examen Afronden" : "Volgende Vraag"}
                        </Button>
                    </div>
                </div>
            );
        };

        const SpeakingWriting = ({ data, title, onBack, onComplete, part }) => {
            const [index, setIndex] = useState(0);
            const [inputValue, setInputValue] = useState("");
            const [stage, setStage] = useState('input'); // input, checked
            
            const item = data[index];
            const isPart2 = part === 2;

            const checkAnswer = () => {
                if (!inputValue.trim()) return;
                setStage('checked');
            };

            const handleNext = () => {
                setStage('input');
                setInputValue("");
                if (index < data.length - 1) {
                    setIndex(i => i + 1);
                } else {
                    onComplete();
                }
            };

            return (
                <div class="p-6 h-full flex flex-col max-w-md mx-auto relative">
                     {/* Header */}
                     <div class="flex items-center justify-between mb-8 z-10">
                        <div class="flex items-center gap-2">
                             <button onClick={onBack} class="p-2 -ml-2 text-slate-400 hover:text-slate-600">
                                <Icon icon="solar:arrow-left-linear" />
                            </button>
                            <span class="text-sm font-medium text-slate-500">
                                {index + 1} / {data.length}
                            </span>
                        </div>
                    </div>

                    <div class="flex-1 overflow-y-auto no-scrollbar">
                        <div class="bg-white border border-slate-200 rounded-3xl shadow-sm p-6 mb-6 relative overflow-hidden">
                             <div class="absolute top-0 right-0 p-4 opacity-5">
                                <Icon icon={isPart2 ? "solar:pen-new-linear" : "solar:chat-line-linear"} className="text-8xl text-black" />
                            </div>
                            
                            <p class="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                                {isPart2 ? "Maak de zin af" : "Geef antwoord"}
                            </p>
                            
                            <h3 class="text-xl font-semibold tracking-tight text-slate-900 leading-snug">
                                {isPart2 ? item.s : item.q}
                            </h3>
                        </div>

                        <div class="space-y-4">
                            <label class="block text-sm font-medium text-slate-700 ml-1">
                                {isPart2 ? "Maak de zin compleet:" : "Schrijf uw antwoord:"}
                            </label>
                            
                            <textarea 
                                value={inputValue}
                                onChange={(e) => setStage('input') || setInputValue(e.target.value)}
                                placeholder="Typ hier..."
                                disabled={stage === 'checked'}
                                class="w-full p-4 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none text-slate-900 min-h-[120px] resize-none shadow-sm transition-shadow"
                            ></textarea>
                            
                            {stage === 'checked' && (
                                <motion.div 
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    class="bg-blue-50 border border-blue-200 rounded-xl p-4 flex gap-3 items-start"
                                >
                                    <Icon icon="solar:info-circle-linear" className="text-blue-600 mt-0.5" />
                                    <div>
                                        <p class="text-xs text-blue-700 font-bold uppercase mb-1">Instructie</p>
                                        <p class="text-slate-700 text-sm">Dit is een open oefening. Controleer zelf of uw zin logisch is en correct Nederlands gebruikt.</p>
                                    </div>
                                </motion.div>
                            )}
                        </div>
                    </div>

                    <div class="mt-6 pt-4 border-t border-slate-100">
                        {stage === 'input' ? (
                            <Button onClick={checkAnswer} disabled={!inputValue.trim()} variant="primary">
                                Controleer
                            </Button>
                        ) : (
                            <Button onClick={handleNext} variant="primary">
                                {index === data.length - 1 ? "Klaar" : "Volgende"}
                            </Button>
                        )}
                    </div>
                </div>
            );
        };

        const Menu = ({ title, options, onBack }) => (
             <div class="p-6 h-full flex flex-col max-w-md mx-auto">
                 <div class="flex items-center justify-between mb-10 mt-4">
                    <div class="flex items-center">
                        <button onClick={onBack} class="p-2 -ml-2 text-slate-400 hover:text-slate-600 mr-4">
                            <Icon icon="solar:arrow-left-linear" />
                        </button>
                        <h1 class="text-2xl font-semibold tracking-tight text-slate-900">{title}</h1>
                    </div>
                 </div>

                 <div class="space-y-4">
                    {options.map((opt, i) => (
                        <motion.div 
                            key={i}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                        >
                            <Card className="p-0 overflow-hidden cursor-pointer group hover:border-blue-200 transition-colors">
                                <button onClick={opt.action} class="w-full text-left p-6 flex items-center justify-between">
                                    <div class="flex items-center gap-4">
                                        <div class={`w-12 h-12 rounded-xl flex items-center justify-center ${opt.bg} ${opt.color}`}>
                                            <Icon icon={opt.icon} />
                                        </div>
                                        <div>
                                            <h3 class="font-semibold text-slate-900">{opt.label}</h3>
                                            <p class="text-sm text-slate-500">{opt.desc}</p>
                                        </div>
                                    </div>
                                    <Icon icon="solar:alt-arrow-right-linear" className="text-slate-300 group-hover:text-slate-600" />
                                </button>
                            </Card>
                        </motion.div>
                    ))}
                 </div>
             </div>
        );

        // --- Main App ---

        const App = () => {
            const [view, setView] = useState('dashboard');
            const [stats, setStats] = useState({ kns: 0, speaking: 0 });

            useEffect(() => {
                const saved = localStorage.getItem('dutch_a1_stats_v2');
                if (saved) setStats(JSON.parse(saved));
            }, []);

            const updateStats = (category, count) => {
                const newStats = { ...stats, [category]: Math.max(stats[category], count) };
                setStats(newStats);
                localStorage.setItem('dutch_a1_stats_v2', JSON.stringify(newStats));
                setView('dashboard');
            };

            const renderView = () => {
                switch(view) {
                    case 'dashboard':
                        return <Dashboard onNavigate={setView} stats={stats} />;
                    
                    case 'kns-menu':
                        return <Menu 
                            title="KNS Examen"
                            onBack={() => setView('dashboard')}
                            options={[
                                { label: "Oefenmodus", desc: "Feedback na elke vraag", icon: "solar:check-read-linear", bg: "bg-blue-50", color: colors.blue, action: () => setView('kns-practice') },
                                { label: "Examenmodus", desc: "Tijdslimiet, officiële stijl", icon: "solar:stopwatch-linear", bg: "bg-orange-50", color: colors.orange, action: () => setView('kns-exam') }
                            ]}
                        />;
                    
                    case 'kns-practice':
                        return <KNSGame mode="practice" onBack={() => setView('kns-menu')} onComplete={(s) => updateStats('kns', s)} />;
                    
                    case 'kns-exam':
                        return <KNSGame mode="exam" onBack={() => setView('kns-menu')} onComplete={(s) => updateStats('kns', s)} />;

                    case 'speaking-menu':
                        return <Menu 
                            title="Spreken & Schrijven"
                            onBack={() => setView('dashboard')}
                            options={[
                                { label: "Deel 1: Vragen", desc: "Beantwoord persoonlijke vragen", icon: "solar:chat-line-linear", bg: "bg-blue-50", color: colors.blue, action: () => setView('speaking-p1') },
                                { label: "Deel 2: Zinnen", desc: "Maak de zinnen logisch af", icon: "solar:pen-new-linear", bg: "bg-orange-50", color: colors.orange, action: () => setView('speaking-p2') }
                            ]}
                        />;

                    case 'speaking-p1':
                        return <SpeakingWriting 
                            data={speakingP1Data} 
                            title="Spreken Deel 1" 
                            part={1}
                            onBack={() => setView('speaking-menu')}
                            onComplete={() => updateStats('speaking', stats.speaking + 1)} 
                        />;
                    
                    case 'speaking-p2':
                        return <SpeakingWriting 
                            data={speakingP2Data} 
                            title="Spreken Deel 2" 
                            part={2}
                            onBack={() => setView('speaking-menu')}
                            onComplete={() => updateStats('speaking', stats.speaking + 1)}
                        />;

                    default:
                        return <Dashboard onNavigate={setView} stats={stats} />;
                }
            };

            return (
                <div class="h-full w-full font-sans text-base">
                    <MusicPlayer />
                    <AnimatePresence mode="wait">
                        <motion.div 
                            key={view}
                            initial={{ opacity: 0, x: 10 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -10 }}
                            transition={{ duration: 0.2 }}
                            class="h-full w-full"
                        >
                            {renderView()}
                        </motion.div>
                    </AnimatePresence>
                </div>
            );
        };

        const root = ReactDOM.createRoot(document.getElementById('root'));
        root.render(<App />);
    
    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      
<div className="h-full w-full" id="root"></div>


    </>
  );
}
