import React, { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import SectionFrame from '../components/ui/SectionFrame'
import LandingHero from '../components/hero/LandingHero'
import PromptCard from '../components/library/PromptCard'
import { WordReveal, CharSlideDown } from '../components/ui/TextAnimations'
import SharedFooter from '../components/layout/SharedFooter'

gsap.registerPlugin(ScrollTrigger)

const PREVIEW_PROMPTS = [
  {
    id: 1,
    title: 'B2B SaaS Dashboard',
    category: 'Dashboard',
    desc: 'Structured system for complex data tables, metric cards, and sidebar navigation.',
    image: 'https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/decb0ab1-7420-4c4c-b697-91e7e54b28e5_1600w.png',
    tools: ['claude', 'googlegemini'],
    locked: false
  },
  {
    id: 2,
    title: 'Fintech Mobile App',
    category: 'Mobile',
    desc: 'Transaction history, wallet balance interactions, and quick send actions.',
    image: 'https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/4536c204-9af4-4506-a136-7afb73bba7a4_1600w.png',
    tools: ['claude', 'openai'],
    locked: false
  },
  {
    id: 3,
    title: 'WebGL Marketing Hero',
    category: 'Hero',
    desc: 'Cinematic 3D hero section prompts with scroll-triggered animation structures.',
    image: 'https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/b8c88cbb-e881-4280-842d-ecafc3670d74_1600w.png',
    tools: ['claude'],
    locked: true
  },
  {
    id: 4,
    title: 'E-commerce Checkout',
    category: 'Web',
    desc: 'High-converting multi-step checkout flow with order summary and payment forms.',
    image: 'https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/84b886a3-f823-458a-b79b-2b2818dfcdca_1600w.png',
    tools: ['googlegemini', 'openai'],
    locked: true
  },
  {
    id: 5,
    title: 'AI Chat Interface',
    category: 'Component',
    desc: 'Conversational UI patterns, typing indicators, and structured message blocks.',
    image: 'https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/05d6b211-9e83-488c-8f3f-42a77b8e9532_1600w.png',
    tools: ['claude', 'googlegemini', 'openai'],
    locked: true
  },
  {
    id: 6,
    title: 'Editorial Blog Layout',
    category: 'Web',
    desc: 'Typography-heavy editorial design with pull quotes and reading progress.',
    image: 'https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=800&q=80',
    tools: ['claude'],
    locked: true
  }
];

const FAQS = [
  {
    q: "Is this a subscription?",
    a: "No, Lumimotion is a one-time purchase. Once you buy a license, you get lifetime access to the current prompt library and all future updates."
  },
  {
    q: "Can I use these prompts for client work?",
    a: "Absolutely. The outputs generated by our prompts are entirely yours. You can use them for personal projects, commercial client work, and internal tools."
  },
  {
    q: "Do I need to know how to code?",
    a: "While basic knowledge of HTML/CSS or React helps, our prompts are engineered to instruct LLMs (like Claude or Gemini) to output complete, structured component code that you can copy and paste."
  },
  {
    q: "Which AI models work best?",
    a: "Our structural constraints are optimized primarily for Claude 3.5 Sonnet and Gemini 1.5 Pro, as they follow strict JSON-like parameters best. However, GPT-4o also produces excellent results."
  },
  {
    q: "How are the team licenses managed?",
    a: "The team license gives you a shared workspace link where up to 5 team members can access the prompt vault, share custom JSON parameter presets, and export prompt sequences."
  },
  {
    q: "Do you offer refunds?",
    a: "Due to the non-returnable nature of digital prompts and knowledge, we do not offer refunds. We recommend trying our free templates in the library first to ensure they fit your workflow."
  }
];

export default function LandingPage() {
  useEffect(() => {
    const ctx = gsap.context(() => {
      
      gsap.set('.hero-anim-item', { opacity: 0, y: 40, filter: 'blur(12px)' })
      gsap.set('.scroll-fade-in', { opacity: 0, y: 40, filter: 'blur(12px)' })

      gsap.to('.hero-anim-item', {
        opacity: 1,
        y: 0,
        filter: 'blur(0px)',
        duration: 1.2,
        stagger: 0.15,
        ease: 'power3.out',
        delay: 0.1
      })

      const revealSections = document.querySelectorAll('.reveal-section')
      revealSections.forEach(section => {
        const words = section.querySelectorAll('.gsap-word-reveal')
        if (words.length) {
          gsap.fromTo(words,
            { y: "100%", opacity: 0, filter: "blur(8px)" },
            {
              scrollTrigger: {
                trigger: section,
                start: "top 85%",
                toggleActions: "play none none reverse"
              },
              y: "0%",
              opacity: 1,
              filter: "blur(0px)",
              duration: 0.8,
              stagger: 0.04,
              ease: "power3.out"
            }
          )
        }
      })

      ScrollTrigger.batch('.scroll-fade-in', {
        start: "top 85%",
        onEnter: batch => {
          gsap.to(batch, {
            opacity: 1,
            y: 0,
            filter: 'blur(0px)',
            duration: 0.8,
            stagger: 0.1,
            ease: "power3.out",
            overwrite: true
          })
        },
        onLeaveBack: batch => {
          gsap.to(batch, {
            opacity: 0,
            y: 40,
            filter: 'blur(12px)',
            duration: 0.5,
            ease: "power2.in",
            overwrite: true
          })
        }
      })
    })

    return () => ctx.revert();
  }, [])

  return (
    <div className="flex flex-col w-full">
      
      {/* 1. HERO SECTION */}
      <LandingHero />

      {/* 2. HOW IT WORKS */}
      <SectionFrame id="how-it-works" className="py-24 px-6 bg-transparent relative z-10">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16">
            <div className="flex flex-col items-start w-full md:w-1/2">
              <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
                <CharSlideDown text="Simple 4-Step Process" delay={0.2} />
              </div>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter text-white text-balance reveal-section">
                <WordReveal>How Lumimotion</WordReveal><br />
                <WordReveal>works.</WordReveal>
              </h2>
            </div>
            
            <div className="flex flex-col items-start md:items-end w-full md:w-1/2 text-left md:text-right">
              <p className="text-base md:text-lg text-white/50 text-pretty scroll-fade-in font-geist tracking-tight mb-8 max-w-md">
                Generate stunning, production-ready interfaces in minutes with our structured prompt system. No prompt-engineering experience required.
              </p>
              <div className="scroll-fade-in">
                <Link to="/library" className="bg-[#c6f91f] text-black px-6 py-3 text-sm hover:bg-[#aade17] transition-all inline-flex items-center gap-2 font-geist tracking-tight font-semibold shadow-[0_0_20px_rgba(198,249,31,0.2)]">
                  Start Building <iconify-icon icon="solar:arrow-right-linear" />
                </Link>
              </div>
            </div>
          </div>

          {/* New 4-Step Grid */}
          <div className="overflow-hidden bg-[#070A0D]/80 border-white/10 border rounded-none shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] scroll-fade-in">
            <div className="grid grid-cols-1 md:grid-cols-2">
              
              {/* Step 01 */}
              <div className="group min-h-[480px] overflow-hidden transition-colors hover:bg-white/[0.035] md:border-r border-white/10 border-b pt-7 pr-7 pb-7 pl-7 relative scroll-fade-in">
                <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_25%_0%,rgba(198,249,31,0.10),transparent_34%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

                <div className="relative mb-7 flex items-start gap-5">
                  <div className="inline-flex shrink-0 rounded-md border border-[#c6f91f]/35 bg-[#c6f91f]/5 px-4 py-2 text-xs font-mono font-medium uppercase tracking-widest text-[#c6f91f]">
                    Step 01
                  </div>

                  <div>
                    <h3 className="text-2xl font-geist font-light tracking-tight text-white">
                      Choose Your System
                    </h3>
                    <p className="mt-2 max-w-md text-base leading-relaxed tracking-tight text-white/50 font-geist">
                      Pick from our library of structural UI patterns or import your own context to start building.
                    </p>
                  </div>
                </div>

                <div className="relative grid overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2">
                  <div className="bg-[#090b0f]/90 p-5">
                    <div className="mb-4 text-xs font-mono tracking-widest text-white/65">Library</div>

                    <div className="space-y-2">
                      <div className="flex items-center gap-3 rounded-lg border border-[#c6f91f]/45 bg-[#c6f91f]/10 p-3 shadow-[0_0_18px_rgba(198,249,31,0.08)]">
                        <div className="flex h-8 w-8 items-center justify-center rounded-md bg-[#c6f91f] text-black">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                            <rect width="7" height="7" x="3" y="3" rx="1"></rect>
                            <rect width="7" height="7" x="14" y="3" rx="1"></rect>
                            <rect width="7" height="7" x="14" y="14" rx="1"></rect>
                            <rect width="7" height="7" x="3" y="14" rx="1"></rect>
                          </svg>
                        </div>
                        <div>
                          <div className="text-sm font-mono text-white">Dashboard OS</div>
                          <div className="text-xs font-geist tracking-tight text-white/40">Analytics &amp; metrics layout</div>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 rounded-lg bg-white/[0.035] p-3 ring-1 ring-white/10">
                        <div className="flex h-8 w-8 items-center justify-center rounded-md bg-white/10 text-white/65">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                            <rect width="14" height="20" x="5" y="2" rx="2"></rect>
                            <path d="M12 18h.01"></path>
                          </svg>
                        </div>
                        <div>
                          <div className="text-sm font-mono text-white/80">Mobile App</div>
                          <div className="text-xs font-geist tracking-tight text-white/40">Mobile-first layout</div>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 rounded-lg bg-white/[0.035] p-3 ring-1 ring-white/10">
                        <div className="flex h-8 w-8 items-center justify-center rounded-md bg-white/10 text-white/65">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                            <circle cx="12" cy="12" r="9"></circle>
                            <circle cx="12" cy="12" r="3"></circle>
                          </svg>
                        </div>
                        <div>
                          <div className="text-sm font-mono text-white/80">Landing Page</div>
                          <div className="text-xs font-geist tracking-tight text-white/40">Marketing &amp; conversion</div>
                        </div>
                      </div>

                      <div className="flex items-center justify-between rounded-lg bg-white/[0.025] px-3 py-3 text-sm font-mono text-white/70 ring-1 ring-white/10">
                        Browse all systems
                        <span className="text-white/40">→</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex min-h-64 flex-col bg-[#090b0f]/90 p-5 sm:border-l sm:border-white/10">
                    <div className="mb-4 text-xs font-mono tracking-widest text-white/65">Import Context</div>
                    <div className="flex flex-1 flex-col items-center justify-center rounded-lg border border-dashed border-white/20 bg-white/[0.025] p-6 text-center transition-colors group-hover:border-[#c6f91f]/40">
                      <svg xmlns="http://www.w3.org/2000/svg" className="mb-4 h-12 w-12 text-[#c6f91f]" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M12 13v8"></path>
                        <path d="M4 14.9A7 7 0 1 1 15.7 8h1.8a4.5 4.5 0 0 1 2.5 8.2"></path>
                        <path d="m8 17 4-4 4 4"></path>
                      </svg>
                      <div className="text-sm font-mono text-white/80">Drop files here</div>
                      <div className="mt-1 text-xs font-geist tracking-tight text-white/40">or click to browse</div>
                      <div className="mt-5 flex flex-wrap justify-center gap-2">
                        <span className="rounded-md border border-white/10 px-3 py-1 text-xs font-mono text-white/45">.json</span>
                        <span className="rounded-md border border-white/10 px-3 py-1 text-xs font-mono text-white/45">.txt</span>
                        <span className="rounded-md border border-white/10 px-3 py-1 text-xs font-mono text-white/45">.md</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Step 02 */}
              <div className="group relative min-h-[480px] overflow-hidden border-b border-white/10 bg-white/[0.025] p-7 transition-colors hover:bg-white/[0.035] scroll-fade-in">
                <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_25%_0%,rgba(198,249,31,0.10),transparent_34%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

                <div className="relative mb-7 flex items-start gap-5">
                  <div className="inline-flex shrink-0 rounded-md border border-[#c6f91f]/35 bg-[#c6f91f]/5 px-4 py-2 text-xs font-mono font-medium uppercase tracking-widest text-[#c6f91f]">
                    Step 02
                  </div>

                  <div>
                    <h3 className="text-2xl font-geist font-light tracking-tight text-white">
                      Configure Parameters
                    </h3>
                    <p className="mt-2 max-w-md text-base leading-relaxed tracking-tight text-white/50 font-geist">
                      Inject your brand, theme, and requirements using structured JSON variables.
                    </p>
                  </div>
                </div>

                <div className="relative overflow-hidden rounded-xl border border-white/10 bg-[#090b0f]/90">
                  <div className="grid bg-white/[0.025] sm:grid-cols-[1fr_0.9fr]">
                    <div className="border-b border-white/10 sm:border-b-0 sm:border-r sm:border-white/10">
                      <div className="flex items-center gap-3 border-b border-white/10 px-5 py-3">
                        <span className="text-sm font-mono text-white">variables.json</span>
                        <span className="h-2 w-2 rounded-full bg-[#c6f91f] shadow-[0_0_10px_rgba(198,249,31,0.5)]"></span>
                      </div>

                      <div className="space-y-1 p-5 font-mono text-sm leading-relaxed">
                        <div><span className="mr-3 text-white/25">1</span><span className="text-white/80">{'{'}</span></div>
                        <div>
                          <span className="mr-3 text-white/25">2</span><span className="text-sky-300">"theme_mode"</span><span className="text-white/55">: </span>
                          <span className="text-[#c6f91f]">"dark"</span><span className="text-white/55">,</span></div>
                        <div>
                          <span className="mr-3 text-white/25">3</span><span className="text-sky-300">"accent_hex"</span><span className="text-white/55">: </span>
                          <span className="text-[#c6f91f]">"#c6f91f"</span><span className="text-white/55">,</span></div>
                        <div>
                          <span className="mr-3 text-white/25">4</span><span className="text-sky-300">"font_family"</span><span className="text-white/55">: </span>
                          <span className="text-[#c6f91f]">"Inter"</span><span className="text-white/55">,</span></div>
                        <div>
                          <span className="mr-3 text-white/25">5</span><span className="text-sky-300">"radius"</span><span className="text-white/55">: </span>
                          <span className="text-[#c6f91f]">12</span><span className="text-white/55">,</span></div>
                        <div>
                          <span className="mr-3 text-white/25">6</span><span className="text-sky-300">"density"</span><span className="text-white/55">: </span>
                          <span className="text-[#c6f91f]">"comfortable"</span></div>
                        <div><span className="mr-3 text-white/25">7</span><span className="text-white/80">{'}'}</span></div>
                      </div>
                    </div>

                    <div className="space-y-4 p-5">
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm font-mono text-white/70">theme_mode</span>
                        <div className="flex min-w-32 items-center justify-between rounded-md bg-white/[0.035] px-3 py-2 text-sm font-geist text-white/80 ring-1 ring-white/10">
                          dark
                          <span className="text-white/45">⌄</span>
                        </div>
                      </div>

                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm font-mono text-white/70">accent_hex</span>
                        <div className="flex min-w-32 items-center justify-between rounded-md bg-white/[0.035] px-3 py-2 text-sm font-geist text-white/80 ring-1 ring-white/10">
                          #c6f91f
                          <span className="h-4 w-4 rounded bg-[#c6f91f]"></span>
                        </div>
                      </div>

                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm font-mono text-white/70">font_family</span>
                        <div className="flex min-w-32 items-center justify-between rounded-md bg-white/[0.035] px-3 py-2 text-sm font-geist text-white/80 ring-1 ring-white/10">
                          Inter
                          <span className="text-white/45">⌄</span>
                        </div>
                      </div>

                      <div className="flex items-center gap-4 pt-1">
                        <span className="text-sm font-mono text-white/70">radius</span>
                        <div className="h-1 flex-1 rounded-full bg-white/10">
                          <div className="relative h-1 w-3/5 rounded-full bg-[#c6f91f]">
                            <span className="absolute right-0 top-1/2 h-4 w-4 -translate-y-1/2 rounded-full border border-white/30 bg-white shadow-sm"></span>
                          </div>
                        </div>
                        <span className="text-sm font-mono text-white/70">12</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between border-t border-white/10 px-5 py-3">
                    <div className="flex items-center gap-2 text-sm font-mono text-[#c6f91f]">
                      <span>✓</span>
                      JSON is valid
                    </div>
                    <div className="h-1 w-20 rounded-full bg-gradient-to-r from-[#c6f91f]/20 to-[#c6f91f]"></div>
                  </div>
                </div>
              </div>

              {/* Step 03 */}
              <div className="group relative min-h-[480px] overflow-hidden bg-white/[0.025] p-7 transition-colors hover:bg-white/[0.035] md:border-r md:border-white/10 scroll-fade-in">
                <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_25%_0%,rgba(198,249,31,0.10),transparent_34%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

                <div className="relative mb-7 flex items-start gap-5">
                  <div className="inline-flex shrink-0 rounded-md border border-[#c6f91f]/35 bg-[#c6f91f]/5 px-4 py-2 text-xs font-mono font-medium uppercase tracking-widest text-[#c6f91f]">
                    Step 03
                  </div>

                  <div>
                    <h3 className="text-2xl font-geist font-light tracking-tight text-white">
                      Preview &amp; Refine
                    </h3>
                    <p className="mt-2 max-w-md text-base leading-relaxed tracking-tight text-white/50 font-geist">
                      Review structural constraints and preview iterations to ensure pixel-perfect fidelity.
                    </p>
                  </div>
                </div>

                <div className="relative overflow-hidden rounded-xl border border-white/10 bg-[#090b0f]/90">
                  <div className="flex items-center justify-between border-b border-white/10 px-5 py-3">
                    <span className="text-sm font-mono text-white/75">Constraint Check</span>
                    <span className="text-sm font-mono text-[#c6f91f]">All checks passed</span>
                  </div>

                  <div className="grid sm:grid-cols-[0.78fr_1.22fr]">
                    <div className="space-y-4 border-b border-white/10 p-5 sm:border-b-0 sm:border-r sm:border-white/10">
                      <div className="flex items-center gap-3 text-sm font-geist tracking-tight text-white/70">
                        <span className="text-[#c6f91f]">✓</span> Layout Structure
                      </div>
                      <div className="flex items-center gap-3 text-sm font-geist tracking-tight text-white/70">
                        <span className="text-[#c6f91f]">✓</span> Spacing Scale
                      </div>
                      <div className="flex items-center gap-3 text-sm font-geist tracking-tight text-white/70">
                        <span className="text-[#c6f91f]">✓</span> Color Contrast
                      </div>
                      <div className="flex items-center gap-3 text-sm font-geist tracking-tight text-white/70">
                        <span className="text-[#c6f91f]">✓</span> Responsive Rules
                      </div>
                    </div>

                    <div className="p-5">
                      <div className="mb-4 grid grid-cols-2 gap-4">
                        <div>
                          <div className="mb-2 text-sm font-mono text-white/60">Current</div>
                          <div className="aspect-[4/3] rounded-lg bg-white/[0.035] p-3 ring-1 ring-white/10">
                            <div className="mb-3 h-3 w-1/2 rounded bg-[#c6f91f]/60"></div>
                            <div className="grid h-24 grid-cols-3 gap-2">
                              <div className="rounded bg-white/10"></div>
                              <div className="rounded bg-white/10"></div>
                              <div className="rounded bg-[#c6f91f]/20"></div>
                            </div>
                            <div className="mt-3 h-2 w-full rounded bg-white/10"></div>
                          </div>
                        </div>

                        <div>
                          <div className="mb-2 text-sm font-mono text-white/60">Preview</div>
                          <div className="aspect-[4/3] rounded-lg bg-[#c6f91f]/5 p-3 ring-1 ring-[#c6f91f]/35 shadow-[0_0_20px_rgba(198,249,31,0.05)]">
                            <div className="mb-3 h-3 w-2/3 rounded bg-[#c6f91f]"></div>
                            <div className="grid h-24 grid-cols-3 gap-2">
                              <div className="rounded bg-white/10"></div>
                              <div className="rounded bg-[#c6f91f]/25"></div>
                              <div className="rounded bg-white/10"></div>
                            </div>
                            <div className="mt-3 h-2 w-4/5 rounded bg-white/15"></div>
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center justify-between rounded-lg bg-white/[0.025] px-5 py-4 ring-1 ring-white/10">
                        <span className="text-sm font-mono text-white/65">Confidence Score</span>
                        <span className="text-base font-mono text-[#c6f91f]">96%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Step 04 */}
              <div className="group relative min-h-[480px] overflow-hidden bg-white/[0.025] p-7 transition-colors hover:bg-white/[0.035] scroll-fade-in">
                <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_25%_0%,rgba(198,249,31,0.10),transparent_34%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

                <div className="relative mb-7 flex items-start gap-5">
                  <div className="inline-flex shrink-0 rounded-md border border-[#c6f91f]/35 bg-[#c6f91f]/5 px-4 py-2 text-xs font-mono font-medium uppercase tracking-widest text-[#c6f91f]">
                    Step 04
                  </div>

                  <div>
                    <h3 className="text-2xl font-geist font-light tracking-tight text-white">
                      Copy &amp; Deploy
                    </h3>
                    <p className="mt-2 max-w-md text-base leading-relaxed tracking-tight text-white/50 font-geist">
                      Copy the optimized prompt block into your favorite LLM or export it for your workflow.
                    </p>
                  </div>
                </div>

                <div className="relative space-y-2">
                  <div className="flex items-center justify-between gap-4 rounded-xl border border-[#c6f91f]/50 bg-[#c6f91f]/5 p-4 shadow-[0_0_24px_rgba(198,249,31,0.08)]">
                    <div className="flex min-w-0 items-center gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center text-[#c6f91f]">✦</div>
                      <div className="min-w-0">
                        <div className="truncate text-base font-mono text-white">Claude 3.5 Sonnet</div>
                        <div className="text-sm font-geist tracking-tight text-white/45">Optimized for React output</div>
                      </div>
                    </div>

                    <button className="inline-flex shrink-0 items-center gap-2 rounded-md bg-[#c6f91f] px-4 py-2.5 text-sm font-geist font-medium tracking-tight text-black transition-colors hover:bg-[#aade17]">
                      Copy Prompt
                    </button>
                  </div>

                  <div className="flex items-center justify-between gap-4 rounded-xl bg-white/[0.035] p-4 ring-1 ring-white/10">
                    <div className="flex min-w-0 items-center gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center text-indigo-300">✦</div>
                      <div className="min-w-0">
                        <div className="truncate text-base font-mono text-white">Gemini 1.5 Pro</div>
                        <div className="text-sm font-geist tracking-tight text-white/45">Optimized for large context</div>
                      </div>
                    </div>

                    <button className="inline-flex shrink-0 rounded-md border border-white/15 bg-white/[0.035] px-4 py-2.5 text-sm font-geist font-medium tracking-tight text-white transition-colors hover:bg-white/10">
                      Copy Prompt
                    </button>
                  </div>

                  <div className="flex items-center justify-between gap-4 rounded-xl bg-white/[0.035] p-4 ring-1 ring-white/10">
                    <div className="flex min-w-0 items-center gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center text-white/85">◎</div>
                      <div className="min-w-0">
                        <div className="truncate text-base font-mono text-white">GPT-4o</div>
                        <div className="text-sm font-geist tracking-tight text-white/45">General purpose layout</div>
                      </div>
                    </div>

                    <button className="inline-flex shrink-0 rounded-md border border-white/15 bg-white/[0.035] px-4 py-2.5 text-sm font-geist font-medium tracking-tight text-white transition-colors hover:bg-white/10">
                      Copy Prompt
                    </button>
                  </div>

                  <div className="flex flex-col gap-3 rounded-xl bg-white/[0.025] p-4 ring-1 ring-white/10 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-3">
                      <span className="text-sm font-mono text-white/65">Export</span>
                      <span className="rounded-md border border-white/10 px-4 py-2 text-sm font-mono text-white/75">.json</span>
                      <span className="rounded-md border border-white/10 px-4 py-2 text-sm font-mono text-white/75">.md</span>
                    </div>

                    <Link to="/library" className="inline-flex items-center gap-2 text-sm font-geist tracking-tight text-white/60 transition-colors hover:text-[#c6f91f]">
                      Open in Prompt Studio →
                    </Link>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
      </SectionFrame>

      {/* 3. PROMPT LIBRARY PREVIEW */}
      <SectionFrame id="library" className="py-20 px-6 bg-transparent relative z-10">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-8 max-w-6xl mx-auto">
          <div className="flex flex-col items-start w-full md:w-1/2">
            <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
              <CharSlideDown text="Curated Vault" delay={0.2} />
            </div>
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter text-white text-balance reveal-section">
               <WordReveal>Prompt Library</WordReveal>
            </h2>
          </div>
          
          <div className="flex flex-col items-start md:items-end w-full md:w-1/2 text-left md:text-right">
            <p className="text-white/50 text-base md:text-lg max-w-md font-geist tracking-tight mb-8 scroll-fade-in text-pretty">
              Curated templates engineered for specific product contexts. Free prompts are fully accessible.
            </p>
            <div className="scroll-fade-in">
              <Link to="/library" className="bg-white/10 text-white border border-white/20 px-6 py-3 hover:bg-white/20 transition-colors font-geist tracking-tight font-medium flex items-center gap-2">
                Browse Entire Library <iconify-icon icon="solar:arrow-right-linear" />
              </Link>
            </div>
          </div>
        </div>

        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {PREVIEW_PROMPTS.map((prompt, index) => (
            <PromptCard key={prompt.id} prompt={prompt} index={index} />
          ))}
        </div>
      </SectionFrame>

      {/* 4. DIFFERENTIATION (Bento Grid) */}
      <SectionFrame id="differentiation" className="py-32 px-6 bg-transparent relative z-10 overflow-hidden">
        {/* Glow Effects */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-[#c6f91f]/5 rounded-full blur-[140px] pointer-events-none"></div>

        <div className="max-w-6xl mx-auto relative z-10">
          
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16">
            <div className="flex flex-col items-start w-full md:w-1/2">
              <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
                <CharSlideDown text="The Advantage" delay={0.2} />
              </div>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter text-white text-balance reveal-section">
                <WordReveal>Built for systems,</WordReveal><br /> <WordReveal>not sketches.</WordReveal>
              </h2>
            </div>
            
            <div className="flex flex-col items-start md:items-end w-full md:w-1/2 text-left md:text-right">
              <p className="text-base md:text-lg text-white/50 text-pretty scroll-fade-in font-geist tracking-tight max-w-md mb-8">
                Why Lumimotion produces production-ready, pixel-perfect results while standard AI prompts generate uninspired, generic layouts.
              </p>
              <div className="scroll-fade-in">
                <Link to="/pricing" className="bg-[#c6f91f] text-black px-6 py-3 text-sm hover:bg-[#aade17] transition-all flex items-center gap-2 font-geist tracking-tight font-medium shadow-[0_0_20px_rgba(198,249,31,0.2)]">
                  Get Full Access <iconify-icon icon="solar:arrow-right-linear" />
                </Link>
              </div>
            </div>
          </div>

          {/* Premium Bento Grid Structure */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 p-6 w-full relative md:auto-rows-[420px]">
  
            <div className="md:col-span-7 border border-white/10 bg-[#05080A] p-6 md:p-8 flex flex-col hover:border-white/20 transition-colors group relative shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] scroll-fade-in">
              <div className="flex-1 w-full relative mb-8 border border-white/10 bg-[#0B0F12] overflow-hidden flex items-center justify-center shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)]">
                <img src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/bc49165b-655c-4598-a8bc-ac2d1370bb45_original.jpg" alt="System Architecture Layout" className="w-full h-full object-cover opacity-60 group-hover:scale-105 group-hover:opacity-90 transition-all duration-700" />
                <div className="absolute inset-0 bg-gradient-to-t from-[#0B0F12] via-transparent to-transparent"></div>
              </div>
              
              <div className="relative z-10 mt-auto">
                <div className="flex items-center gap-2 mb-2">
                  <iconify-icon icon="solar:ghost-linear" class="text-xl text-[#c6f91f]"></iconify-icon>
                  <h3 className="text-xl md:text-2xl font-geist font-light tracking-tighter text-white">No Generic Slop</h3>
                </div>
                <p className="text-sm text-white/40 leading-relaxed max-w-md font-geist tracking-tight">
                  Standard AI generates uninspired layouts. Our structural references force the AI to respect typography hierarchy, negative space, and modern design conventions.
                </p>
              </div>
            </div>

            <div className="md:col-span-5 border border-white/10 bg-[#05080A] p-6 md:p-8 flex flex-col hover:border-white/20 transition-colors group relative shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] scroll-fade-in">
              <div className="flex-1 w-full relative mb-8 flex items-center justify-center bg-[#0B0F12] border border-white/10 shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] overflow-hidden">
                
                <div className="w-full max-w-[260px] border border-white/10 bg-[#05080A] shadow-[0_10px_40px_-10px_rgba(0,0,0,0.8)] relative group-hover:-translate-y-2 transition-transform duration-500 z-10">
                  <div className="flex items-center gap-1.5 px-3 py-2 border-b border-white/5 bg-[#0B0F12]">
                    <div className="w-2 h-2 rounded-none bg-white/20"></div>
                    <div className="w-2 h-2 rounded-none bg-white/20"></div>
                    <div className="w-2 h-2 rounded-none bg-white/20"></div>
                  </div>
                  <div className="p-5 font-mono text-[11px] md:text-xs leading-loose text-white/80">
                    <div><span className="text-[#c6f91f]">"layout"</span>: <span className="text-white">"bento_grid"</span>,</div>
                    <div><span className="text-[#c6f91f]">"spacing"</span>: <span className="text-white">"relaxed"</span>,</div>
                    <div><span className="text-[#c6f91f]">"typography"</span>: {"{"}</div>
                    <div className="pl-4"><span className="text-[#c6f91f]">"family"</span>: <span className="text-white">"Inter"</span>,</div>
                    <div className="pl-4"><span className="text-[#c6f91f]">"tracking"</span>: <span className="text-white">"tight"</span></div>
                    <div>{"}"}</div>
                  </div>
                </div>
              </div>

              <div className="relative z-10 mt-auto">
                <div className="flex items-center gap-2 mb-2">
                  <iconify-icon icon="solar:layers-linear" class="text-xl text-[#c6f91f]"></iconify-icon>
                  <h3 className="text-xl md:text-2xl font-geist font-light tracking-tighter text-white">Structured Parameters</h3>
                </div>
                <p className="text-sm text-white/40 leading-relaxed font-geist tracking-tight">
                  Templates use JSON-like parameter structures that models understand perfectly. Less ambiguity means fewer visual hallucinations.
                </p>
              </div>
            </div>

            <div className="md:col-span-5 border border-white/10 bg-[#05080A] p-6 md:p-8 flex flex-col hover:border-white/20 transition-colors group relative shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] scroll-fade-in">
              <div className="flex-1 w-full relative mb-8 flex items-center justify-center bg-[#0B0F12] border border-white/10 shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] overflow-hidden">
                <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:20px_20px]"></div>
                
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-36 h-24 border border-[#c6f91f]/30 bg-[#c6f91f]/5 flex items-center justify-center group-hover:scale-105 transition-transform duration-500 z-10">
                  
                  <div className="absolute -top-6 left-0 right-0 flex items-center justify-between text-[10px] text-[#c6f91f] font-mono">
                    <div className="w-[1px] h-4 bg-[#c6f91f]/50"></div>
                    <span>256px</span>
                    <div className="w-[1px] h-4 bg-[#c6f91f]/50"></div>
                  </div>
                  
                  <div className="absolute top-0 bottom-0 -right-6 flex flex-col items-center justify-between text-[10px] text-[#c6f91f] font-mono">
                    <div className="w-4 h-[1px] bg-[#c6f91f]/50"></div>
                    <span className="-rotate-90">128px</span>
                    <div className="w-4 h-[1px] bg-[#c6f91f]/50"></div>
                  </div>
                  
                  <div className="w-2 h-2 bg-[#c6f91f] absolute -top-1 -left-1 shadow-[0_0_8px_#c6f91f]"></div>
                  <div className="w-2 h-2 bg-[#c6f91f] absolute -bottom-1 -right-1 shadow-[0_0_8px_#c6f91f]"></div>
                </div>
              </div>

              <div className="relative z-10 mt-auto">
                <div className="flex items-center gap-2 mb-2">
                  <iconify-icon icon="solar:pen-new-round-linear" class="text-xl text-[#c6f91f]"></iconify-icon>
                  <h3 className="text-xl md:text-2xl font-geist font-light tracking-tighter text-white">Designer Crafted</h3>
                </div>
                <p className="text-sm text-white/40 leading-relaxed font-geist tracking-tight">
                  Every system is written and tested by a senior product designer. Variables and structural constraints are tuned for professional output.
                </p>
              </div>
            </div>

            <div className="md:col-span-7 border border-white/10 bg-[#05080A] p-6 md:p-8 flex flex-col hover:border-white/20 transition-colors group relative shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] scroll-fade-in">
              <div className="flex-1 w-full relative mb-8 flex flex-col items-center justify-center bg-[#0B0F12] border border-white/10 shadow-[inset_0_2px_10px_rgba(0,0,0,0.5)] p-6 overflow-hidden">
                
                <div className="w-full max-w-sm flex flex-col gap-4 relative z-10">
                  <div className="flex items-center gap-4">
                    <div className="w-10 h-10 border border-white/10 bg-[#05080A] flex items-center justify-center text-white/60">
                      <iconify-icon icon="solar:copy-linear" class="text-lg"></iconify-icon>
                    </div>
                    
                    <div className="flex-1 h-[1px] bg-gradient-to-r from-white/10 to-[#c6f91f]/50 relative">
                      <div className="absolute top-1/2 right-0 -translate-y-1/2 w-2 h-2 bg-[#c6f91f] shadow-[0_0_12px_#c6f91f]"></div>
                    </div>
                    
                    <div className="w-10 h-10 border border-[#c6f91f]/30 bg-[#c6f91f]/10 flex items-center justify-center text-[#c6f91f]">
                      <iconify-icon icon="solar:magic-stick-3-linear" class="text-lg"></iconify-icon>
                    </div>
                    
                    <div className="flex-1 h-[1px] bg-gradient-to-r from-[#c6f91f]/50 to-white/10 relative">
                      <div className="absolute top-1/2 right-0 -translate-y-1/2 w-2 h-2 bg-white/50"></div>
                    </div>
                    
                    <div className="w-10 h-10 border border-white/10 bg-[#05080A] flex items-center justify-center text-white/60 group-hover:border-[#c6f91f]/50 group-hover:text-[#c6f91f] transition-all duration-700">
                      <iconify-icon icon="solar:rocket-linear" class="text-lg"></iconify-icon>
                    </div>
                  </div>
                  
                  <div className="border border-white/10 bg-[#05080A] p-3 relative overflow-hidden mt-4">
                    <div className="absolute inset-y-0 left-0 bg-[#c6f91f]/10 w-[0%] group-hover:w-full transition-all duration-1000 ease-in-out"></div>
                    <div className="flex items-center justify-between relative z-10">
                      <span className="text-[10px] font-mono text-white/40 uppercase tracking-widest">Status: Generating</span>
                      <span className="text-[10px] font-mono text-[#c6f91f] flex items-center gap-2 uppercase tracking-widest">
                        <span className="w-1.5 h-1.5 bg-[#c6f91f] animate-pulse"></span>
                        Production Ready
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="relative z-10 mt-auto">
                <div className="flex items-center gap-2 mb-2">
                  <iconify-icon icon="solar:clock-circle-linear" class="text-xl text-[#c6f91f]"></iconify-icon>
                  <h3 className="text-xl md:text-2xl font-geist font-light tracking-tighter text-white">Immediate Value</h3>
                </div>
                <p className="text-sm text-white/40 leading-relaxed max-w-md font-geist tracking-tight">
                  Stop spending hours arguing with an LLM to fix padding. Copy the template, fill in your specifics, and get beautifully structured code instantly.
                </p>
              </div>
            </div>

          </div>
        </div>
      </SectionFrame>

      {/* 5. TESTIMONIALS (Asymmetric Bento) */}
      <SectionFrame id="testimonials" className="py-24 md:py-32 px-6 bg-transparent relative z-10">
        <div className="max-w-6xl mx-auto">
          
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16">
            <div className="flex flex-col items-start w-full md:w-1/2">
              <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
                <CharSlideDown text="Wall of Love" delay={0.2} />
              </div>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter text-white text-balance reveal-section">
                 <WordReveal>Trusted by product</WordReveal><br />
                 <WordReveal>builders.</WordReveal>
              </h2>
            </div>
            
            <div className="flex flex-col items-start md:items-end w-full md:w-1/2 text-left md:text-right">
              <p className="text-base md:text-lg text-white/50 text-pretty scroll-fade-in font-geist tracking-tight max-w-md mb-8">
                See how teams are using our structured prompt system to bypass generic AI outputs and ship production-ready UI faster.
              </p>
              <div className="scroll-fade-in">
                <Link to="/library" className="bg-white/10 text-white border border-white/20 px-6 py-3 hover:bg-white/20 transition-colors font-geist tracking-tight font-medium flex items-center gap-2">
                  View Examples <iconify-icon icon="solar:arrow-right-linear" />
                </Link>
              </div>
            </div>
          </div>

          {/* 2/3 1/3 Asymmetric Bento Grid */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-6">
            
            {/* Testimonial 1 */}
            <div className="md:col-span-8 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in">
              <div className="flashlight-content p-8 md:p-10 flex flex-col justify-between relative group overflow-hidden hover:border-white/20 transition-all duration-300">
                <div className="absolute top-0 right-0 w-64 h-64 bg-[#c6f91f]/5 rounded-full blur-[80px] pointer-events-none group-hover:bg-[#c6f91f]/10 transition-colors duration-700"></div>
                
                <div className="relative z-10 mb-8 md:mb-12">
                  <div className="flex gap-1 mb-6 text-[#c6f91f] scroll-fade-in">
                    {[...Array(5)].map((_, i) => <iconify-icon key={i} icon="solar:star-bold" class="text-sm"></iconify-icon>)}
                  </div>
                  <p className="text-lg md:text-2xl text-white font-geist font-light leading-relaxed tracking-tighter max-w-2xl text-pretty scroll-fade-in">
                    "Before Lumimotion, I spent hours arguing with Claude trying to get the spacing right on complex dashboards. These structural prompts act like a straitjacket for the AI, forcing it to output perfect Tailwind layouts on the first try. It's completely changed my workflow."
                  </p>
                </div>

                <div className="relative z-10 flex items-center gap-4 mt-auto scroll-fade-in">
                  <img src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/5866f61c-e537-452b-9d35-053e985d625b_320w.webp" alt="Marcus T." className="w-12 h-12 rounded-full border border-white/20 grayscale opacity-80" />
                  <div>
                    <div className="text-white font-geist font-light tracking-tighter text-sm">Marcus T.</div>
                    <div className="text-white/40 text-xs font-geist tracking-tight">Lead Product Designer @ FinTech Co</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Testimonial 2 */}
            <div className="md:col-span-4 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in">
              <div className="flashlight-content p-8 md:p-10 flex flex-col justify-between relative group hover:border-white/20 transition-all duration-300">
                <div className="relative z-10 mb-8 md:mb-12">
                  <div className="flex gap-1 mb-6 text-[#c6f91f] scroll-fade-in">
                    {[...Array(5)].map((_, i) => <iconify-icon key={i} icon="solar:star-bold" class="text-sm"></iconify-icon>)}
                  </div>
                  <p className="text-base text-white/80 leading-relaxed max-w-sm font-geist tracking-tight scroll-fade-in">
                    "The JSON-like constraints are brilliant. I just paste the template, inject my brand colors, and get a completely custom, usable component instantly. No more generic slop."
                  </p>
                </div>

                <div className="relative z-10 flex items-center gap-4 mt-auto scroll-fade-in">
                  <img src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/461c2bb1-9a06-404e-b80f-18cf9b924a4d_320w.webp" alt="Sarah J." className="w-10 h-10 rounded-full border border-white/20 grayscale opacity-80" />
                  <div>
                    <div className="text-white font-geist font-light tracking-tighter text-sm">Sarah J.</div>
                    <div className="text-white/40 text-xs font-geist tracking-tight">Frontend Engineer</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Testimonial 3 */}
            <div className="md:col-span-4 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in">
              <div className="flashlight-content p-8 md:p-10 flex flex-col justify-between relative group hover:border-white/20 transition-all duration-300">
                <div className="relative z-10 mb-8 md:mb-12">
                  <div className="flex gap-1 mb-6 text-[#c6f91f] scroll-fade-in">
                     {[...Array(5)].map((_, i) => <iconify-icon key={i} icon="solar:star-bold" class="text-sm"></iconify-icon>)}
                  </div>
                  <p className="text-base text-white/80 leading-relaxed max-w-sm font-geist tracking-tight scroll-fade-in">
                    "I was skeptical paying for prompts, but the ROI was immediate. The mobile app views alone saved me two weeks of iterative design work."
                  </p>
                </div>

                <div className="relative z-10 flex items-center gap-4 mt-auto scroll-fade-in">
                  <img src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/bf728e3d-89a4-468d-96e5-d2d55f70e406_320w.webp" alt="David L." className="w-10 h-10 rounded-full border border-white/20 grayscale opacity-80" />
                  <div>
                    <div className="text-white font-geist font-light tracking-tighter text-sm">David L.</div>
                    <div className="text-white/40 text-xs font-geist tracking-tight">Startup Founder</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Testimonial 4 */}
            <div className="md:col-span-8 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in">
              <div className="flashlight-content p-8 md:p-10 flex flex-col justify-between relative group overflow-hidden hover:border-white/20 transition-all duration-300">
                <div className="absolute inset-0 opacity-[0.02] bg-[linear-gradient(rgba(255,255,255,1)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,1)_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none"></div>
                
                <div className="relative z-10 mb-8 md:mb-12">
                  <div className="flex gap-1 mb-6 text-[#c6f91f] scroll-fade-in">
                     {[...Array(5)].map((_, i) => <iconify-icon key={i} icon="solar:star-bold" class="text-sm"></iconify-icon>)}
                  </div>
                  <p className="text-lg md:text-2xl text-white font-geist font-light leading-relaxed tracking-tighter max-w-2xl text-pretty scroll-fade-in">
                    "As a developer with zero design skills, Lumimotion is my cheat code. The prompts are structured so logically that even Gemini Pro outputs stunning, accessible React code. My side projects finally look like they were built by a professional agency."
                  </p>
                </div>

                <div className="relative z-10 flex items-center gap-4 mt-auto scroll-fade-in">
                  <img src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/6e825b87-0682-49e3-98c2-dbdab1f8f9c5_320w.webp" alt="Elena M." className="w-12 h-12 rounded-full border border-white/20 grayscale opacity-80" />
                  <div>
                    <div className="text-white font-geist font-light tracking-tighter text-sm">Elena M.</div>
                    <div className="text-white/40 text-xs font-geist tracking-tight">Full-stack Developer</div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </SectionFrame>

      {/* 6. PRICING */}
      <SectionFrame id="pricing" className="py-24 md:py-32 px-6 bg-transparent relative z-10">
        <div className="max-w-6xl mx-auto">
          
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16">
            <div className="flex flex-col items-start w-full md:w-1/2">
              <div className="inline-flex items-center gap-2 px-3 py-1 border border-[#c6f91f]/30 bg-[#c6f91f]/5 text-xs text-[#c6f91f] mb-6 uppercase tracking-widest font-geist font-semibold overflow-hidden scroll-fade-in">
                 <CharSlideDown text="Unlock All Access" delay={0.2} />
              </div>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-geist font-light tracking-tighter text-white text-balance reveal-section">
                <WordReveal>One time payment.</WordReveal><br />
                <WordReveal>Lifetime access.</WordReveal>
              </h2>
            </div>
            
            <div className="flex flex-col items-start md:items-end w-full md:w-1/2 text-left md:text-right">
              <p className="text-white/50 text-base md:text-lg text-pretty scroll-fade-in font-geist tracking-tight max-w-md mb-8">
                Skip the subscription. Gain instant access to the entire vault of production-ready prompt structures and all future additions.
              </p>
              <div className="scroll-fade-in">
                <Link to="/pricing" className="bg-[#c6f91f] text-black px-6 py-3 text-sm hover:bg-[#aade17] transition-all flex items-center gap-2 font-geist tracking-tight font-medium shadow-[0_0_20px_rgba(198,249,31,0.2)]">
                  Compare Plans <iconify-icon icon="solar:arrow-right-linear" />
                </Link>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8">
            
            <div className="lg:col-span-7 flex flex-col gap-6 lg:gap-8">
              
              <div className="border border-white/10 bg-white/5 backdrop-blur-md p-8 md:p-10 flex flex-col md:flex-row gap-8 items-start hover:border-white/20 transition-all duration-300 scroll-fade-in">
                <div className="w-full md:w-1/2 flex flex-col h-full scroll-fade-in">
                  <h3 className="text-xl font-geist font-light text-white mb-2 tracking-tighter">Standard License</h3>
                  <p className="text-sm text-white/50 mb-8 font-geist tracking-tight">Perfect for solo designers and developers.</p>
                  
                  <div className="flex items-start gap-1 mb-8 md:mb-12">
                    <span className="text-xl text-white/50 mt-1">$</span>
                    <span className="text-5xl font-geist font-light tracking-tighter text-white">29</span>
                    <span className="text-xs text-white/40 self-end mb-2 ml-1 font-geist tracking-tight">/ one-time</span>
                  </div>
                  
                  <Link to="/unlock" className="w-full text-center inline-block bg-white/10 border border-white/20 text-white py-3 text-sm hover:bg-white/20 transition-colors mt-auto font-geist tracking-tight font-medium">
                    Get Standard
                  </Link>
                </div>
                
                <div className="w-full md:w-1/2 flex flex-col gap-4 scroll-fade-in">
                  <div className="text-xs font-semibold uppercase tracking-widest text-white/40 mb-2 font-geist">Includes</div>
                  <ul className="flex flex-col gap-4 text-sm font-geist tracking-tight">
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Access to 42+ structured prompts</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>New templates added monthly</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Use for personal & commercial</span>
                    </li>
                    <li className="flex items-start gap-3 text-white/80">
                      <iconify-icon icon="solar:check-circle-linear" class="text-white/60 text-lg mt-px shrink-0" />
                      <span>Lifetime updates included</span>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="border border-[#c6f91f]/30 bg-[#c6f91f]/10 backdrop-blur-md p-8 md:p-10 flex flex-col md:flex-row gap-8 items-start relative overflow-hidden group scroll-fade-in">
                <div className="absolute top-0 right-0 w-64 h-64 bg-[#c6f91f]/20 rounded-full blur-[80px] pointer-events-none"></div>
                <div className="absolute top-0 right-0 px-3 py-1 bg-[#c6f91f] text-black text-[10px] font-bold uppercase tracking-widest">Most Popular</div>

                <div className="w-full md:w-1/2 flex flex-col h-full relative z-10 scroll-fade-in">
                  <h3 className="text-xl font-geist font-light text-white mb-2 tracking-tighter">Team License</h3>
                  <p className="text-sm text-white/60 mb-8 font-geist tracking-tight">For teams shipping products together.</p>
                  
                  <div className="flex items-start gap-1 mb-8 md:mb-12">
                    <span className="text-xl text-white/50 mt-1">$</span>
                    <span className="text-5xl font-geist font-light tracking-tighter text-white">99</span>
                    <span className="text-xs text-white/40 self-end mb-2 ml-1 font-geist tracking-tight">/ one-time</span>
                  </div>
                  
                  <Link to="/unlock" className="w-full text-center inline-block bg-[#c6f91f] text-black py-3 text-sm hover:bg-[#aade17] transition-colors mt-auto shadow-[0_0_20px_rgba(198,249,31,0.2)] font-geist tracking-tight font-medium">
                    Get Team Access
                  </Link>
                </div>
                
                <div className="w-full md:w-1/2 flex flex-col gap-4 relative z-10 scroll-fade-in">
                  <div className="text-xs font-semibold uppercase tracking-widest text-[#c6f91f] mb-2 font-geist">Everything in Standard, plus:</div>
                  <ul className="flex flex-col gap-4 text-sm font-geist tracking-tight">
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Up to 5 team members</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Shared prompt workspace</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Custom JSON variables export</span>
                    </li>
                    <li className="flex items-start gap-3 text-white">
                      <iconify-icon icon="solar:check-circle-bold-duotone" class="text-[#c6f91f] text-lg mt-px shrink-0" />
                      <span>Priority email support</span>
                    </li>
                  </ul>
                </div>
              </div>

            </div>

            <div className="lg:col-span-5 border border-white/10 bg-white/5 backdrop-blur-md flashlight-target scroll-fade-in h-full">
              <div className="flashlight-content p-8 md:p-10 flex flex-col relative overflow-hidden group h-full">
                <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[120%] h-64 bg-[radial-gradient(ellipse_at_bottom,rgba(255,255,255,0.05)_0%,transparent_70%)] pointer-events-none transition-opacity group-hover:opacity-100 opacity-50"></div>
                
                <div className="w-12 h-12 rounded bg-white/10 border border-white/20 flex items-center justify-center mb-8 relative z-10 scroll-fade-in">
                  <iconify-icon icon="solar:buildings-2-linear" class="text-2xl text-white/70 group-hover:text-white transition-colors"></iconify-icon>
                </div>

                <h3 className="text-2xl font-geist font-light tracking-tighter text-white mb-4 relative z-10 scroll-fade-in">Enterprise Solutions</h3>
                <p className="text-sm text-white/60 leading-relaxed mb-10 relative z-10 text-pretty font-geist tracking-tight scroll-fade-in">
                  Need a dedicated prompt system modeled exactly to your company's internal UI library or design system? We can map our architecture directly to your proprietary components.
                </p>

                <div className="flex flex-col gap-6 mb-10 relative z-10">
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-white/30 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">Dedicated Designer</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">Work directly with our team to map specific variables to your design token structure.</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-white/30 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">CI/CD Integration</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">API access to the generated constraints for seamless automation pipelines.</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-4 items-start scroll-fade-in">
                    <div className="w-[1px] h-full bg-gradient-to-b from-[#c6f91f]/60 to-transparent mt-1" />
                    <div>
                      <h4 className="text-sm font-geist tracking-tight font-medium text-white mb-1">Unlimited Seats</h4>
                      <p className="text-xs text-white/50 leading-relaxed font-geist tracking-tight">Company-wide access and secure enterprise SSO configuration setup.</p>
                    </div>
                  </div>
                </div>

                <Link to="/contact" className="mt-auto border border-white/20 bg-transparent text-white w-full py-3.5 text-sm hover:bg-white/10 hover:border-white/30 transition-all relative z-10 flex items-center justify-center gap-2 font-geist tracking-tight font-medium scroll-fade-in">
                  Contact Sales <iconify-icon icon="solar:arrow-right-linear" />
                </Link>
              </div>
            </div>

          </div>
        </div>
      </SectionFrame>

      <SharedFooter />

    </div>
  )
}