import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2M6V79H761');

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      

<header className="fixed top-0 w-full z-50 bg-white shadow-[0_1px_3px_rgba(0,0,0,0.05)] h-[72px] flex items-center transition-all">
<div className="max-w-7xl mx-auto px-4 w-full flex justify-between items-center">
<a className="flex items-center gap-1 text-xl tracking-tighter font-semibold" href="#">
<span className="text-[#0D1B2A]">Queenshine</span>
<span className="text-[#FFC300]">Electricals</span>
</a>
<a className="hidden md:flex bg-[#FFC300] text-[#0D1B2A] h-12 px-6 rounded-md font-medium items-center justify-center gap-2 hover:bg-[#e6b000] transition-colors focus:ring-2 focus:ring-offset-2 focus:ring-[#FFC300] outline-none" href="tel:1300000000">
<iconify-icon className="text-lg" icon="solar:phone-linear"></iconify-icon>
                Call Now
            </a>
</div>
</header>
<main>

<section className="relative pt-[72px] flex items-center min-h-[85vh] md:min-h-[700px] bg-[#0D1B2A]">

<div className="absolute inset-0 z-0">
<img alt="Modern Australian home with solar panels" className="w-full h-full object-cover" src="https://images.unsplash.com/photo-1613665813446-82a78c468a1d?q=80&amp;w=2058&amp;auto=format&amp;fit=crop"/>
<div className="absolute inset-0 bg-[#0D1B2A]/50 mix-blend-multiply"></div>
</div>
<div className="relative z-10 max-w-7xl mx-auto px-4 w-full py-10 md:py-[60px]">
<div className="max-w-2xl mx-auto md:mx-0 text-center md:text-left">
<h1 className="text-3xl md:text-5xl font-semibold text-white tracking-tight mb-4 leading-tight">
                        Solar Battery Storage for Your Home
                    </h1>
<p className="text-base md:text-lg text-white/90 mb-8 leading-relaxed">
                        Power your home, day and night. Protect your family from blackouts and slash your electricity bills with premium solar battery storage.
                    </p>
<div className="flex flex-col md:flex-row gap-4 mb-10">
<a className="bg-[#FFC300] text-[#0D1B2A] h-12 px-8 rounded-md font-medium w-full md:w-auto flex items-center justify-center hover:bg-[#e6b000] transition-colors" href="#quote">
                            Get a Free Battery Quote
                        </a>
<a className="border border-white/30 bg-white/5 backdrop-blur-sm text-white h-12 px-8 rounded-md font-medium w-full md:w-auto flex items-center justify-center hover:bg-white/10 transition-colors" href="tel:1300000000">
                            Call Us Today
                        </a>
</div>
<div className="flex flex-wrap gap-y-3 gap-x-6 justify-center md:justify-start border-t border-white/10 pt-6">
<div className="flex items-center gap-2 text-white/90 text-sm">
<iconify-icon className="text-[#FFC300] text-lg" icon="solar:check-circle-linear"></iconify-icon>
                            CEC Accredited
                        </div>
<div className="flex items-center gap-2 text-white/90 text-sm">
<iconify-icon className="text-[#FFC300] text-lg" icon="solar:check-circle-linear"></iconify-icon>
                            Rebate Approved
                        </div>
<div className="flex items-center gap-2 text-white/90 text-sm">
<iconify-icon className="text-[#FFC300] text-lg" icon="solar:check-circle-linear"></iconify-icon>
                            Licensed Electricians
                        </div>
<div className="flex items-center gap-2 text-white/90 text-sm">
<iconify-icon className="text-[#FFC300] text-lg" icon="solar:check-circle-linear"></iconify-icon>
                            Queensland Local
                        </div>
</div>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-white">
<div className="max-w-3xl mx-auto px-4 text-center md:text-left">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-6">
                    What is Solar Battery Storage?
                </h2>
<div className="space-y-6 text-gray-600 text-base leading-relaxed">
<p>
                        Solar battery storage is an advanced energy system that captures and stores the excess electricity generated by your solar panels during the day, allowing you to use that free, clean energy at night or during grid blackouts.
                    </p>
<p>
                        When we talk about battery storage for solar, we're talking about true energy independence. Instead of sending your excess daytime solar power back to the grid for a tiny feed-in tariff — only to buy it back at premium rates at night — a home solar battery storage system lets you keep the power you produce. Whether you need a DC-coupled system for a new solar installation or an AC-coupled solar panels battery like the Tesla Powerwall to retrofit your existing panels, Queenshine Electricals designs systems that perfectly match your household's energy demands.
                    </p>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-[#F5F5F5]">
<div className="max-w-5xl mx-auto px-4">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-10 text-center">
                    The Benefits of Adding a Battery
                </h2>
<div className="grid grid-cols-1 md:grid-cols-2 gap-6">

<div className="bg-white p-8 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex flex-col items-start">
<div className="w-12 h-12 bg-[#FFC300]/10 rounded-lg flex items-center justify-center mb-6">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:wad-of-money-linear"></iconify-icon>
</div>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-3 tracking-tight">Slash Your Power Bills</h3>
<p className="text-sm text-gray-600 leading-relaxed">Electricity is most expensive during evening peak 4–8 PM. Your battery auto-discharges during these hours, shielding you from premium grid pricing.</p>
</div>

<div className="bg-white p-8 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex flex-col items-start">
<div className="w-12 h-12 bg-[#FFC300]/10 rounded-lg flex items-center justify-center mb-6">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:bolt-linear"></iconify-icon>
</div>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-3 tracking-tight">Blackout Protection</h3>
<p className="text-sm text-gray-600 leading-relaxed">Queensland's severe summer storms won't leave you in the dark. A battery with Emergency Power Supply keeps your fridge, lights and Wi-Fi running.</p>
</div>

<div className="bg-white p-8 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex flex-col items-start">
<div className="w-12 h-12 bg-[#FFC300]/10 rounded-lg flex items-center justify-center mb-6">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:diploma-linear"></iconify-icon>
</div>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-3 tracking-tight">Claim Government Rebates</h3>
<p className="text-sm text-gray-600 leading-relaxed">We help you secure your maximum solar battery rebate and STC point-of-sale discounts — dramatically speeding up your return on investment.</p>
</div>

<div className="bg-white p-8 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex flex-col items-start">
<div className="w-12 h-12 bg-[#FFC300]/10 rounded-lg flex items-center justify-center mb-6">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:leaf-linear"></iconify-icon>
</div>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-3 tracking-tight">Maximise Clean Energy</h3>
<p className="text-sm text-gray-600 leading-relaxed">Stop relying on coal or gas at night. Run your home 24/7 on pure, zero-emission sunshine you harvested earlier in the day.</p>
</div>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-white">
<div className="max-w-6xl mx-auto px-4">
<div className="text-center max-w-2xl mx-auto mb-12">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-4">
                        How It Works: The Daily Cycle
                    </h2>
<p className="text-base text-gray-600">
                        Your system is fully automated — intelligent software always uses the most cost-effective power source without you lifting a finger.
                    </p>
</div>
<div className="flex flex-col md:flex-row gap-8 relative">

<div className="hidden md:block absolute top-6 left-10 right-10 h-[1px] bg-gray-200 z-0"></div>

<div className="flex-1 relative z-10 flex flex-col items-start md:items-center text-left md:text-center">
<div className="w-12 h-12 rounded-full bg-[#FFC300] text-[#0D1B2A] flex items-center justify-center font-semibold text-lg mb-6 shadow-sm border-[4px] border-white">
                            1
                        </div>
<iconify-icon className="text-gray-400 text-3xl mb-4 md:hidden" icon="solar:sun-2-linear"></iconify-icon>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-2 tracking-tight flex items-center gap-2">
<iconify-icon className="text-gray-400 text-xl hidden md:block" icon="solar:sun-2-linear"></iconify-icon>
                            Morning — Generate
                        </h3>
<p className="text-sm text-gray-600 leading-relaxed">Your solar panels power your morning appliances — coffee makers, toasters and lights.</p>
</div>

<div className="flex-1 relative z-10 flex flex-col items-start md:items-center text-left md:text-center">
<div className="w-12 h-12 rounded-full bg-[#FFC300] text-[#0D1B2A] flex items-center justify-center font-semibold text-lg mb-6 shadow-sm border-[4px] border-white">
                            2
                        </div>
<iconify-icon className="text-gray-400 text-3xl mb-4 md:hidden" icon="solar:battery-charge-linear"></iconify-icon>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-2 tracking-tight flex items-center gap-2">
<iconify-icon className="text-gray-400 text-xl hidden md:block" icon="solar:battery-charge-linear"></iconify-icon>
                            Midday — Store
                        </h3>
<p className="text-sm text-gray-600 leading-relaxed">Surplus energy is redirected to charge your battery to 100% instead of being exported to the grid.</p>
</div>

<div className="flex-1 relative z-10 flex flex-col items-start md:items-center text-left md:text-center">
<div className="w-12 h-12 rounded-full bg-[#FFC300] text-[#0D1B2A] flex items-center justify-center font-semibold text-lg mb-6 shadow-sm border-[4px] border-white">
                            3
                        </div>
<iconify-icon className="text-gray-400 text-3xl mb-4 md:hidden" icon="solar:moon-linear"></iconify-icon>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-2 tracking-tight flex items-center gap-2">
<iconify-icon className="text-gray-400 text-xl hidden md:block" icon="solar:moon-linear"></iconify-icon>
                            Evening — Discharge
                        </h3>
<p className="text-sm text-gray-600 leading-relaxed">As the sun sets and demand spikes, your system instantly switches to stored battery power.</p>
</div>

<div className="flex-1 relative z-10 flex flex-col items-start md:items-center text-left md:text-center">
<div className="w-12 h-12 rounded-full bg-[#FFC300] text-[#0D1B2A] flex items-center justify-center font-semibold text-lg mb-6 shadow-sm border-[4px] border-white">
                            4
                        </div>
<iconify-icon className="text-gray-400 text-3xl mb-4 md:hidden" icon="solar:wallet-linear"></iconify-icon>
<h3 className="text-lg font-semibold text-[#0D1B2A] mb-2 tracking-tight flex items-center gap-2">
<iconify-icon className="text-gray-400 text-xl hidden md:block" icon="solar:wallet-linear"></iconify-icon>
                            VPP — Earn
                        </h3>
<p className="text-sm text-gray-600 leading-relaxed">Join a Virtual Power Plant and earn premium feed-in tariffs when your retailer draws from your battery to stabilise the grid.</p>
</div>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-[#F5F5F5]">
<div className="max-w-5xl mx-auto px-4">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-10 text-center">
                    Why Choose Queenshine Electricals?
                </h2>
<div className="grid grid-cols-1 md:grid-cols-2 gap-6">

<div className="bg-white p-6 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex gap-5">
<div className="shrink-0 mt-1">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:verified-check-linear"></iconify-icon>
</div>
<div>
<h3 className="text-base font-semibold text-[#0D1B2A] mb-2 tracking-tight">CEC Accredited Installers</h3>
<p className="text-sm text-gray-600 leading-relaxed">Fully Clean Energy Council accredited — guaranteeing Australian safety standards and full rebate eligibility.</p>
</div>
</div>

<div className="bg-white p-6 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex gap-5">
<div className="shrink-0 mt-1">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:ruler-pen-linear"></iconify-icon>
</div>
<div>
<h3 className="text-base font-semibold text-[#0D1B2A] mb-2 tracking-tight">No Cookie-Cutter Systems</h3>
<p className="text-sm text-gray-600 leading-relaxed">We analyse your bills, switchboard and future goals to recommend the perfect system size for your home.</p>
</div>
</div>

<div className="bg-white p-6 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex gap-5">
<div className="shrink-0 mt-1">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:shield-check-linear"></iconify-icon>
</div>
<div>
<h3 className="text-base font-semibold text-[#0D1B2A] mb-2 tracking-tight">Premium Tier-1 Hardware</h3>
<p className="text-sm text-gray-600 leading-relaxed">Brand-agnostic and uncompromising — we supply only proven, hyper-safe technologies including Tesla, BYD and Sigenergy.</p>
</div>
</div>

<div className="bg-white p-6 rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 flex gap-5">
<div className="shrink-0 mt-1">
<iconify-icon className="text-[#FFC300] text-2xl" icon="solar:document-text-linear"></iconify-icon>
</div>
<div>
<h3 className="text-base font-semibold text-[#0D1B2A] mb-2 tracking-tight">Done-For-You Paperwork</h3>
<p className="text-sm text-gray-600 leading-relaxed">We handle all compliance paperwork, Energex/Ergon pre-approvals and rebate applications on your behalf.</p>
</div>
</div>
</div>
<div className="mt-10 flex justify-center">
<a className="bg-[#FFC300] text-[#0D1B2A] h-12 px-8 rounded-md font-medium w-full md:w-auto flex items-center justify-center hover:bg-[#e6b000] transition-colors" href="#quote">
                        Book a Free Site Appraisal
                    </a>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-white border-b border-gray-100">
<div className="max-w-7xl mx-auto px-4">
<h2 className="text-lg md:text-xl font-semibold text-[#0D1B2A] tracking-tight mb-8 text-center">
                    Premium Solar Battery Brands We Install
                </h2>
<div className="grid grid-cols-2 md:grid-cols-7 gap-6 items-center justify-items-center mb-8">
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">Fox ESS</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">Solax</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">Sigenergy</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">GoodWe</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">Tesla</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase">BYD</span>
<span className="text-xl md:text-2xl font-semibold tracking-tighter text-gray-300 hover:text-[#0D1B2A] transition-colors cursor-default select-none uppercase col-span-2 md:col-span-1">Duracell</span>
</div>
<p className="text-xs text-gray-400 text-center max-w-lg mx-auto">
                    Every brand we install is Tier-1 rated, warranty-backed and fully compliant with Australian standards.
                </p>
</div>
</section>

<section className="py-10 md:py-[60px] bg-[#FFC300]">
<div className="max-w-3xl mx-auto px-4 text-center">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-4">
                    Claim Your Solar Battery Rebate Today
                </h2>
<p className="text-base text-[#0D1B2A]/80 leading-relaxed mb-8">
                    Eligible Queensland homeowners can access federal STC point-of-sale discounts worth thousands of dollars — automatically deducted from your invoice. Queensland's Battery Booster grants may also apply. As CEC Accredited installers, we manage all the paperwork so you don't have to lift a finger.
                </p>
<a className="bg-[#0D1B2A] text-white h-12 px-8 rounded-md font-medium inline-flex items-center justify-center hover:bg-black transition-colors w-full md:w-auto" href="#quote">
                    Check My Eligibility
                </a>
</div>
</section>

<section className="py-10 md:py-[60px] bg-white">
<div className="max-w-3xl mx-auto px-4">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-8">
                    Frequently Asked Questions
                </h2>
<div className="space-y-1">
<details className="group border-b border-gray-200 py-4">
<summary className="flex justify-between items-center cursor-pointer font-medium text-[#0D1B2A] pr-2">
                            Can I add a battery to my existing solar panels?
                            <iconify-icon className="text-[#FFC300] text-xl transition-transform duration-200 group-open:rotate-45 shrink-0 ml-4" icon="solar:add-circle-linear"></iconify-icon>
</summary>
<p className="pt-4 text-sm text-gray-600 leading-relaxed pr-8">
                            Yes, absolutely. If your inverter is hybrid-ready, we plug in a compatible DC-coupled battery directly. For older inverters, we use an AC-coupled solution like the Tesla Powerwall with its own built-in inverter — no need to replace your entire system.
                        </p>
</details>
<details className="group border-b border-gray-200 py-4">
<summary className="flex justify-between items-center cursor-pointer font-medium text-[#0D1B2A] pr-2">
                            How long does home solar battery storage last?
                            <iconify-icon className="text-[#FFC300] text-xl transition-transform duration-200 group-open:rotate-45 shrink-0 ml-4" icon="solar:add-circle-linear"></iconify-icon>
</summary>
<p className="pt-4 text-sm text-gray-600 leading-relaxed pr-8">
                            Modern batteries last 10–15 years. Our Tier-1 brands use Lithium Iron Phosphate (LFP) or NMC chemistry, engineered for thousands of deep cycles. Tesla, Sigenergy and Duracell all come with a 10-year warranty guaranteeing 60–70% capacity retention.
                        </p>
</details>
<details className="group border-b border-gray-200 py-4">
<summary className="flex justify-between items-center cursor-pointer font-medium text-[#0D1B2A] pr-2">
                            Will a battery power my house during a blackout?
                            <iconify-icon className="text-[#FFC300] text-xl transition-transform duration-200 group-open:rotate-45 shrink-0 ml-4" icon="solar:add-circle-linear"></iconify-icon>
</summary>
<p className="pt-4 text-sm text-gray-600 leading-relaxed pr-8">
                            Yes. Your system uses an Emergency Power Supply to isolate your home from the grid. We can configure Essential Circuit Backup for fridge, lights and Wi-Fi, or Whole Home Backup for larger systems — keeping heavy appliances like AC running even in a full neighbourhood blackout.
                        </p>
</details>
<details className="group border-b border-gray-200 py-4">
<summary className="flex justify-between items-center cursor-pointer font-medium text-[#0D1B2A] pr-2">
                            How do I claim a solar battery rebate?
                            <iconify-icon className="text-[#FFC300] text-xl transition-transform duration-200 group-open:rotate-45 shrink-0 ml-4" icon="solar:add-circle-linear"></iconify-icon>
</summary>
<p className="pt-4 text-sm text-gray-600 leading-relaxed pr-8">
                            Rebates are claimed at point of sale through accredited installers. As CEC Accredited, we automatically calculate and deduct your STC discount from your invoice. We also monitor Queensland's Battery Booster grants and advise you on every rebate your property qualifies for.
                        </p>
</details>
</div>
</div>
</section>

<section className="py-10 md:py-[60px] bg-[#F5F5F5]" id="quote">
<div className="max-w-xl mx-auto px-4">
<div className="text-center mb-8">
<h2 className="text-2xl md:text-3xl font-semibold text-[#0D1B2A] tracking-tight mb-2">
                        Get Your Free Solar Battery Quote Today
                    </h2>
<p className="text-base text-gray-600">
                        No obligation. Our local experts will assess your home's energy needs and recommend the perfect system.
                    </p>
</div>
<div className="bg-white p-6 md:p-8 rounded-2xl shadow-[0_4px_12px_rgba(0,0,0,0.05)] border border-gray-100">
<form action="#" className="space-y-5" method="POST">
<div>
<label className="block text-sm font-medium text-[#0D1B2A] mb-1" htmlFor="name">Full Name</label>
<input className="h-12 w-full border border-gray-200 rounded-md px-4 text-sm focus:outline-none focus:border-[#0D1B2A] focus:ring-1 focus:ring-[#0D1B2A] transition-shadow placeholder-gray-400" id="name" name="name" placeholder="John Doe" required="" type="text"/>
</div>
<div>
<label className="block text-sm font-medium text-[#0D1B2A] mb-1" htmlFor="phone">Phone Number</label>
<input className="h-12 w-full border border-gray-200 rounded-md px-4 text-sm focus:outline-none focus:border-[#0D1B2A] focus:ring-1 focus:ring-[#0D1B2A] transition-shadow placeholder-gray-400" id="phone" name="phone" placeholder="0400 000 000" required="" type="tel"/>
</div>
<div>
<label className="block text-sm font-medium text-[#0D1B2A] mb-1" htmlFor="suburb">Suburb</label>
<input className="h-12 w-full border border-gray-200 rounded-md px-4 text-sm focus:outline-none focus:border-[#0D1B2A] focus:ring-1 focus:ring-[#0D1B2A] transition-shadow placeholder-gray-400" id="suburb" name="suburb" placeholder="e.g. Brisbane" required="" type="text"/>
</div>
<div>
<label className="block text-sm font-medium text-[#0D1B2A] mb-3">Do you have existing solar?</label>
<div className="flex items-center gap-6">
<label className="flex items-center gap-2 cursor-pointer group">
<input checked="" className="peer sr-only" name="existing_solar" type="radio" value="yes"/>
<div className="w-5 h-5 rounded-full border border-gray-300 peer-checked:border-[#0D1B2A] peer-checked:border-[6px] group-hover:border-[#0D1B2A] transition-all"></div>
<span className="text-sm text-gray-700">Yes</span>
</label>
<label className="flex items-center gap-2 cursor-pointer group">
<input className="peer sr-only" name="existing_solar" type="radio" value="no"/>
<div className="w-5 h-5 rounded-full border border-gray-300 peer-checked:border-[#0D1B2A] peer-checked:border-[6px] group-hover:border-[#0D1B2A] transition-all"></div>
<span className="text-sm text-gray-700">No</span>
</label>
</div>
</div>
<button className="w-full h-12 bg-[#FFC300] text-[#0D1B2A] font-semibold rounded-md mt-4 hover:bg-[#e6b000] transition-colors focus:ring-2 focus:ring-offset-2 focus:ring-[#FFC300] outline-none flex justify-center items-center" type="submit">
                            Get My Free Quote
                        </button>
<p className="text-xs text-gray-500 text-center mt-4 flex items-center justify-center gap-1">
<iconify-icon icon="solar:lock-password-linear"></iconify-icon>
                            Your details are safe. We never share your information.
                        </p>
</form>
</div>
</div>
</section>
</main>

<footer className="bg-[#0D1B2A] text-white py-12 md:pb-12 pb-[100px]"> 
<div className="max-w-7xl mx-auto px-4 text-center">
<div className="text-xl tracking-tighter font-semibold mb-6 flex justify-center items-center gap-1">
<span className="text-white">Queenshine</span>
<span className="text-[#FFC300]">Electricals</span>
</div>
<div className="flex flex-col md:flex-row justify-center items-center gap-4 md:gap-8 mb-8 text-sm text-white/80">
<a className="hover:text-white transition-colors flex items-center gap-2" href="tel:1300000000">
<iconify-icon icon="solar:phone-linear"></iconify-icon> 1300 000 000
                </a>
<a className="hover:text-white transition-colors flex items-center gap-2" href="mailto:info@queenshine.com.au">
<iconify-icon icon="solar:letter-linear"></iconify-icon> info@queenshine.com.au
                </a>
</div>
<div className="flex justify-center items-center gap-6 mb-8 text-xs text-white/60">
<a className="hover:text-white transition-colors" href="#">Privacy Policy</a>
<a className="hover:text-white transition-colors" href="#">Terms &amp; Conditions</a>
</div>
<p className="text-xs text-white/50 border-t border-white/10 pt-8">
                © 2025 Queenshine Electricals. All Rights Reserved. CEC Accredited Installer.
            </p>
</div>
</footer>

<div className="fixed bottom-0 w-full z-50 bg-white p-4 shadow-[0_-4px_12px_rgba(0,0,0,0.05)] md:hidden border-t border-gray-100">
<a className="w-full h-12 bg-[#FFC300] text-[#0D1B2A] rounded-md font-semibold flex items-center justify-center gap-2 active:bg-[#e6b000] transition-colors" href="tel:1300000000">
<iconify-icon className="text-lg" icon="solar:phone-linear"></iconify-icon>
            Call Now
        </a>
</div>

    </>
  );
}
