import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    const originalAddEventListener = document.addEventListener;
    const originalWindowAddEventListener = window.addEventListener;
    
    document.addEventListener = function(event, callback, options) {
      if (event === 'DOMContentLoaded') {
        setTimeout(() => {
          try { callback(new Event('DOMContentLoaded')); } catch (e) { console.error(e); }
        }, 0);
      } else {
        originalAddEventListener.call(document, event, callback, options);
      }
    };
    
    window.addEventListener = function(event, callback, options) {
      if (event === 'load') {
        setTimeout(() => {
          try { callback(new Event('load')); } catch (e) { console.error(e); }
        }, 0);
      } else {
        originalWindowAddEventListener.call(window, event, callback, options);
      }
    };
    
    let onloadHandler = null;
    try {
      Object.defineProperty(window, 'onload', {
        set: function(fn) {
          onloadHandler = fn;
          setTimeout(() => {
            try { if (typeof fn === 'function') fn(); } catch (e) { console.error(e); }
          }, 0);
        },
        get: function() { return onloadHandler; },
        configurable: true
      });
    } catch (e) {}
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



window.addEventListener('DOMContentLoaded',()=>{
  lucide.createIcons();
  particlesJS('particles-js',{
    particles:{number:{value:60,density:{enable:true,value_area:1000}},color:{value:"#ffffff"},
    opacity:{value:.12},size:{value:1.5,random:true},line_linked:{enable:false},move:{enable:true,speed:.35}},
    interactivity:{detect_on:"canvas",events:{onhover:{enable:false}}},retina_detect:true});
});

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
    
    return () => {
      document.addEventListener = originalAddEventListener;
      window.addEventListener = originalWindowAddEventListener;
      try { delete window.onload; } catch (e) {}
    };
  }, []);

  return (
    <>
      
<div className="min-h-screen w-full p-6 md:p-10 relative overflow-hidden">
<div className="absolute inset-0 -z-10" id="particles-js"></div>
<section className="relative rounded-3xl p-8 md:p-14 bg-gradient-to-br from-indigo-700 to-violet-900 overflow-hidden ring-1 ring-violet-800/40">

<div aria-hidden="true" className="absolute -left-40 -top-32 h-96 w-96 bg-fuchsia-500/30 blur-3xl rounded-full"></div>

<div className="w-full flex items-center justify-between gap-8 absolute top-4 left-0 px-6 md:px-10">

<a className="font-['Chakra_Petch'] text-white text-xl tracking-tight" href="#">Nebula3D</a>

<nav aria-label="Primary" className="hidden md:flex items-center gap-8 text-sm font-medium">
<a className="flex items-center gap-1 hover:text-white transition animate-left" href="#"><i className="w-4 h-4" data-lucide="home"></i>Home</a>
<a className="flex items-center gap-1 hover:text-white transition animate-left" href="#"><i className="w-4 h-4" data-lucide="image"></i>Gallery</a>
<a className="flex items-center gap-1 hover:text-white transition animate-left" href="#"><i className="w-4 h-4" data-lucide="layers"></i>Blueprints</a>
<a className="flex items-center gap-1 hover:text-white transition animate-left" href="#"><i className="w-4 h-4" data-lucide="users"></i>Community</a>
<a className="flex items-center gap-1 hover:text-white transition animate-left" href="#"><i className="w-4 h-4" data-lucide="phone"></i>Support</a>
</nav>

<button className="border-2 border-white/70 bg-transparent text-sm font-semibold text-white rounded-full pt-2 pr-6 pb-2 pl-6 hover:bg-white/10 transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-white/80">Get Started</button>
</div>

<div className="grid md:grid-cols-2 gap-14 md:mt-24 relative z-10 mt-24 items-center">
<header className="space-y-6 animate-fade">
<h1 className="font-['Chakra_Petch'] text-5xl md:text-6xl leading-tight tracking-tight">Build Infinite<br/>Worlds in Seconds</h1>
<p className="text-slate-300 max-w-md">Nebula3D turns your sketches and prompts into production-ready, fully-textured 3D environments faster than you can say <em>render</em>.</p>
<div className="flex gap-4">
<button id="join-beta-btn"><span className="relative z-10">Join Beta</span></button>
<button id="watch-demo-btn"><span className="relative z-10 flex items-center justify-center gap-2"><i className="w-4 h-4" data-lucide="play"></i>Watch Demo</span></button>
</div>
</header>
<figure className="flex justify-center md:justify-end animate-fade">
<img alt="Futuristic 3D city generated by AI" className="w-full max-w-sm md:max-w-none ring-1 ring-white/10 hover:scale-[1.03] transition-transform duration-300 object-cover rounded-2xl shadow-xl" src="https://images.unsplash.com/photo-1635492491273-455af7728453?w=1080&amp;q=80"/>
</figure>
</div>
</section>

<section className="grid md:grid-cols-3 gap-6 mt-10">
<article className="animate-card bg-emerald-600 text-white rounded-3xl p-8 hover:-translate-y-1.5 hover:shadow-emerald-800/60 transition duration-300 focus-within:outline focus-within:outline-2 focus-within:outline-emerald-300/80">
<header className="space-y-4">
<span className="uppercase text-xs font-medium tracking-widest text-emerald-200/90 flex items-center gap-1"><i className="w-4 h-4" data-lucide="zap"></i>Update</span>
<h3 className="font-semibold text-2xl leading-snug tracking-tight">Real-time Collab just went live</h3>
<p className="text-sm text-emerald-200/90">Edit meshes simultaneously with your team, no refresh required.</p>
</header>
</article>
<article className="animate-card bg-sky-700 text-white rounded-3xl p-8 hover:-translate-y-1.5 hover:shadow-sky-900/60 transition duration-300 focus-within:outline focus-within:outline-2 focus-within:outline-sky-300/80">
<header className="space-y-4">
<span className="uppercase text-xs font-medium tracking-widest text-sky-200/90 flex items-center gap-1"><i className="w-4 h-4" data-lucide="flame"></i>Insights</span>
<h3 className="font-semibold text-2xl leading-snug tracking-tight">Texture generator hits 4K resolution</h3>
<p className="text-sm text-sky-200/90">Sharper maps with zero extra compute consumption.</p>
</header>
</article>
<article className="animate-card bg-pink-600 text-white rounded-3xl p-8 hover:-translate-y-1.5 hover:shadow-pink-900/60 transition duration-300 focus-within:outline focus-within:outline-2 focus-within:outline-pink-300/80">
<div className="flex items-start justify-between">
<header>
<span className="uppercase text-xs font-medium tracking-widest text-pink-200/90 flex items-center gap-1"><i className="w-4 h-4" data-lucide="users"></i>Crew</span>
<h3 className="font-semibold text-2xl tracking-tight mt-3">Top Creators</h3>
</header>
<i className="w-6 h-6 opacity-80" data-lucide="arrow-up-right"></i>
</div>
<div className="border-t border-pink-400/40 mt-6 pt-4 flex -space-x-2">
<img alt="Lucas" className="w-10 h-10 rounded-full ring-2 ring-pink-400" src="https://randomuser.me/api/portraits/men/44.jpg"/>
<img alt="Sofia" className="w-10 h-10 rounded-full ring-2 ring-pink-400" src="https://randomuser.me/api/portraits/women/32.jpg"/>
<img alt="Arjun" className="w-10 h-10 rounded-full ring-2 ring-pink-400" src="https://randomuser.me/api/portraits/men/21.jpg"/>
</div>
</article>
</section>
</div>



    </>
  );
}
