import React, { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    try {
      
try{if(window.parent&&window.parent!==window){window.parent.promotekit_referral="1fd2949a-d22c-431b-92bf-02d4ad04ee24";window.parent.document.cookie="promotekit_referral=1fd2949a-d22c-431b-92bf-02d4ad04ee24;path=/;domain=.aura.build;max-age=31536000"}}catch(e){}



window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2M6V79H761');

    } catch (error) {
      console.error("Error executing template scripts:", error);
    }
  }, []);

  return (
    <>
      
<nav className="sticky top-0 z-50 w-full backdrop-blur-md bg-white/70 border-b border-zinc-200/80">
<div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
<div className="flex items-center gap-2">
<div className="w-8 h-8 bg-zinc-900 text-white rounded-md flex items-center justify-center text-sm font-semibold tracking-tighter shadow-sm">
                    SY
                </div>
<span className="text-sm font-medium tracking-tight text-zinc-900">Song Yi</span>
</div>
<div className="flex items-center gap-4 text-sm font-medium text-zinc-500">
<a className="hover:text-zinc-900 transition-colors" href="#work">Works</a>
<a className="hover:text-zinc-900 transition-colors" href="#contact">Contact</a>
</div>
</div>
</nav>
<header className="sm:pt-32 sm:pb-24 overflow-hidden pt-24 pb-16 relative">
<div className="absolute inset-0 -z-10 h-full w-full bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] opacity-50"></div>
<div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
<div className="flex flex-col items-start max-w-2xl">
<h1 className="sm:text-5xl leading-tight text-3xl font-semibold text-zinc-900 tracking-tight scale-100" style={{maskImage: 'linear-gradient(190deg, transparent, black 0%, black 100%, transparent)', WebkitMaskImage: 'linear-gradient(190deg, transparent, black 0%, black 100%, transparent)'}}>
                    Journalist &amp; <br className="hidden sm:block"/>Content Creator.
                </h1>
<p className="sm:text-lg leading-relaxed text-base text-zinc-500 tracking-tight mt-4">Selected works by Song Yi (宋艺) from China Daily Website. Specializing in video editing, reporting, and visual storytelling. Bridging China and the world through breathing narratives.</p>
<div className="mt-8 flex flex-wrap gap-4 items-center">
<div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white text-sm font-medium text-zinc-800 border border-zinc-200 shadow-sm hover:border-zinc-300 transition-colors" id="contact">
<iconify-icon className="text-zinc-400 text-base" icon="solar:chat-round-line-linear" strokeWidth="1.5"></iconify-icon>
<span className="tracking-tight">WeChat: eroda09</span>
</div>
<div className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-zinc-500">
<iconify-icon className="text-zinc-400 text-base" icon="solar:calendar-linear" strokeWidth="1.5"></iconify-icon>
<span className="tracking-tight">2024 - 2025</span>
</div>
</div>
</div>
</div>
</header>
<main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pb-32" id="work">
<div className="flex items-center justify-between border-b border-zinc-200 pb-4 mb-8">
<h2 className="text-xl font-semibold tracking-tight text-zinc-900">Archive</h2>
<span className="text-xs font-medium text-zinc-500 bg-zinc-100 px-2.5 py-1 rounded-full tracking-tight">Full Archive</span>
</div>
<div className="flex flex-col">
<div className="hidden sm:flex text-xs font-medium text-zinc-400 border-b border-zinc-200 pb-3 mb-2 px-2 tracking-tight uppercase">
<div className="w-28 shrink-0">Date</div>
<div className="flex-1">Title</div>
<div className="w-40 shrink-0 text-right">Role</div>
</div>
<div className="divide-y divide-zinc-100/80">

<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/31/WS6954b2a2a310d6866eb31682.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.31</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Ice and snow tourism: one industry boosting many</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/29/WS69522fc9a310d6866eb3100f.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.29</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">'My life has always been linked to skiing’</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/29/WS6951d7f7a310d6866eb30e22.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.29</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Global business leaders' views on China's economy</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频策划</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/25/WS694cf247a310d6866eb3071f.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.25</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Small sea buckthorn, big industry</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.douyin.com/video/7587303519015701787" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.24</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">新疆阿勒泰，冰雪经济正升温</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/24/WS694b9f44a310d6866eb3045c.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.24</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China's growth moderates mainly due to global cycles, but resilience and opportunity remain, says expert</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/24/WS694b43b5a310d6866eb302c8.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.24</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Six biz events changed Chinese people's life in 2025</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频策划拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/23/WS694a0629a310d6866eb30082.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.23</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">New moves to boost China's economy in 2026</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄 (Contrib)</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/18/WS69438f45a310d6866eb2f4ec.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.12.18</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Justin Yifu Lin: Stronger policy measures likely next year to address bottlenecks</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202512/06/WS69335f4aa310d6866eb2d267.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.26</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Valvoline identifies growth opportunities in China's new five-year plan</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/21/WS6920079ba310d6866eb2abc0.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.21</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China's remarkable progress in institutional opening-up</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/13/WS6915a5efa310d6866eb2958f.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.13</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Haier gives home appliances 'smart eyes’</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/12/WS6914420aa310d6866eb2921b.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.12</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Xiaomi architect: We aim to deliver proactive service across human-car-home ecosystem</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/11/WS6912ad01a310fc20369a46ad.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.11</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Straight to Wuzhen: Chinese medical enterprise safeguards maternal and infant health</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/11/WS69143b19a310d6866eb291f9.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.11</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">2025 WIC Wuzhen Summit: AI making agricultural know-how simpler, cheaper and targeted</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字深度 (Contrib)</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/11/WS69130158a310fc20369a47bc.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.11</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Six Little Dragons: A microcosm of China's innovation ecology</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字深度新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/09/WS691028aba310fc20369a4058.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">World Bank expert: AI technology can aid farmers</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/09/WS69105973a310fc20369a40a4.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">UN official on China's agri development</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/09/WS690ff0d6a310fc20369a3ff7.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Andy Palmer: West can learn from China's long-term planning</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/04/WS690967f3a310f215074b8da0.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.04</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China's high-quality growth set to spark global investor interest: UK economist</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202511/03/WS69081593a310f215074b8a3a.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.11.03</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">A decade of commitment: Reuniting in Wuzhen to discuss the future of a shared cyberspace</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> AI视频制作</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/31/WS690473f6a310f735438b8167.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.31</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China hits 865m IPv6 users</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/30/WS6902ba2ea310f735438b7b02.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.30</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Get ready for the 2025 WIC Wuzhen Summit</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:gallery-linear"></iconify-icon> 图表</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/29/WS69017f15a310f735438b78b4.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.29</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Tech start-ups to gather at WIC for AI dialogue</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/20/WS68f5e5d6a310f735438b5f1c.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.20</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Powering up! Nuclear plant to diversify energy production during next 5 years</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/16/WS68f04e45a310f735438b54a2.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.16</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">UAE minister: China a dynamic global economic powerhouse</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/14/WS68edee45a310f735438b4e49.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.14</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Decoupling not inevitable outcome of US trade dispute with China</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/13/WS68ec70cba310f735438b4a60.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.13</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">'Dual circulation' helping China weather external challenges</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202510/11/WS68e9fac4a310f735438b4650.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.10.11</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China sees surge in travel, consumption during holidays</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> AI视频制作</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202509/27/WS68d76383a3108622abca342b.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.09.27</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">不拆封就能杀菌？黑科技了解一下</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202509/14/WS68c6893fa3108622abca0a5e.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.09.14</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">When Australia is too delicious to miss</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202509/12/WS68c378f3a3108622abca0611.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.09.12</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Come and check out the 2025 CIFTIS!</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202509/11/WS68c29594a3108622abca047b.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.09.11</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Top themes at CIFTIS 2025</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202508/30/WS68b27443a3108622abc9df8b.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.08.30</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Tianjin sets sail for future</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> AI视频制作</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202508/24/WS68aab44ca310851ffdb4fc31.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.08.24</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Chinese artist wins landmark international copyright case</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202507/25/WS68835016a310ad07b5d920fa.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.25</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">世界互联网大会副理事长：寻求AI生成与人类创作间的平衡</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202507/25/WS68832d92a310ad07b5d9204c.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.25</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">赵厚麟：世界互联网大会为各国创造数字合作平台</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202507/24/WS6882167fa310ad07b5d91cf7.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.24</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">周鸿祎：未来每个人都是AI智能体的老板</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200 relative overflow-hidden" href="https://www.chinadaily.com.cn/a/202507/18/WS6879c1a9a310ad07b5d90ad8.html" target="_blank"><div className="absolute right-0 top-0 bottom-0 w-1 bg-zinc-900 rounded-r-lg opacity-10"></div><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.18</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Nvidia CEO: China has three unique advantages for humanoid robots<span className="block text-xs text-zinc-400 font-normal mt-1 flex items-center gap-1"><iconify-icon icon="solar:star-linear"></iconify-icon> 全网总互动量超7000</span></div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://mapp.api.weibo.cn/fx/8051e86d7653ed253c7130241b58cfee.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.16</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">黄仁勋：#中国具备发展人形机器人的独特优势#</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://mapp.api.weibo.cn/fx/f8fee85c0950c1e61b5a8db51539d8ae.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.16</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">专访黄仁勋：中国AI发展速度令人震惊</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:document-text-linear"></iconify-icon> 文字新闻</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200 relative overflow-hidden" href="https://www.chinadaily.com.cn/a/202507/16/WS6877a9e0a310ad07b5d904ed.html" target="_blank"><div className="absolute right-0 top-0 bottom-0 w-1 bg-zinc-900 rounded-r-lg opacity-10"></div><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.16</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Nvidia CEO: Chinese cars are unfortunately not available in the US<span className="block text-xs text-zinc-400 font-normal mt-1 flex items-center gap-1"><iconify-icon icon="solar:star-linear"></iconify-icon> 全网总互动量超7300</span></div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200 relative overflow-hidden" href="https://www.chinadaily.com.cn/a/202507/16/WS6877a9bba310ad07b5d904e9.html" target="_blank"><div className="absolute right-0 top-0 bottom-0 w-1 bg-zinc-900 rounded-r-lg opacity-10"></div><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.16</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Nvidia CEO: China is moving incredibly fast at AI<span className="block text-xs text-zinc-400 font-normal mt-1 flex items-center gap-1"><iconify-icon icon="solar:star-linear"></iconify-icon> FB 49万次播放，全网总互动量超13,000</span></div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://cn.chinadaily.com.cn/a/202507/09/WS686e4a3aa3106af2b3c73474.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">专家：上海合作组织搭建合作平台、引领发展潮流</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://cn.chinadaily.com.cn/a/202507/09/WS686e4a21a3106af2b3c73472.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">中国社科院专家：在天津见证中国发展与贡献</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202507/09/WS686e1445a31000e9a573b0df.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.09</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China and Russia: Cities building stronger ties</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://cn.chinadaily.com.cn/a/202507/08/WS686cf95ca3106af2b3c73102.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.08</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">莫斯科国际合作中心顾问：中俄城市合作互动频繁</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:mic-linear"></iconify-icon> 视频采访</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202507/08/WS686cdf4ba31000e9a573ad4d.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.07.08</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Russian professor: Tianjin Port an example for rest of world</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/28/WS685f1dc2a31000e9a57390f0.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.28</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Expert: China's consumption efforts benefit global economy</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/26/WS685d1a2ca310a04af22c8b70.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.26</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">I drank bus exhaust</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频编导剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/26/WS685d00e2a310a04af22c8af2.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.26</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">美企CEO:夏季达沃斯对联接全球市场意义非凡</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/26/WS685c9e99a310a04af22c88de.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.26</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Colombian diplomat: China a trusted trade partner</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/23/WS6858fad5a310a04af22c7e71.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.23</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Zimbabwe Foreign Minister : Xi shaping a new reality across Africa</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/20/WS6854d88da310a04af22c7783.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.20</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Kenyan official: Zero-tariff treatment 'lifeline' for Africa</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/20/WS685491c7a310a04af22c7584.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.20</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">肯尼亚航空高管：中国航空业发展值得非洲借鉴</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/15/WS684e5250a310a04af22c64f2.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.15</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China-Africa expo: Highlights that wowed visitors</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/14/WS684d1abea310a04af22c640e.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.14</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Expo captures booming China-Africa trade</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202506/14/WS684cff5ba310a04af22c6402.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.06.14</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Dukan CSO: We source the best products from China</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202505/29/WS6837b26da310a04af22c2204.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.05.29</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Wujiang: Watertown's cool-tech</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频编导剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202505/23/WS68302929a310a04af22c136b.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.05.23</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Hainan's new moves in opening-up</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频采访拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202505/15/WS6825587ba310a04af22bf8a3.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.05.15</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China a key trade hub, vital partner for Argentina: expert</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202505/08/WS681c2419a310a04af22be1bf.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.05.08</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">China's consumption booms during May Day holiday</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> AI视频制作</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202504/30/WS6811973ea310a04af22bd0e0.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.04.30</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">Turning crisis into opportunity: How China responds to US tariff impact</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频拍摄剪辑</span></div></a>
<a className="group flex flex-col sm:flex-row sm:items-center py-4 px-2 -mx-2 rounded-lg hover:bg-white hover:shadow-sm hover:ring-1 hover:ring-zinc-200/50 transition-all duration-200" href="https://www.chinadaily.com.cn/a/202504/29/WS68102476a310a04af22bcbb4.html" target="_blank"><div className="text-xs text-zinc-400 font-mono w-28 shrink-0 mb-2 sm:mb-0">2025.04.29</div><div className="flex-1 text-sm font-medium text-zinc-700 group-hover:text-zinc-900 tracking-tight transition-colors">'Baking' success in Taicang</div><div className="w-full sm:w-40 shrink-0 flex sm:justify-end mt-3 sm:mt-0"><span className="inline-flex items-center gap-1.5 rounded bg-zinc-50 px-2 py-1 text-xs font-medium text-zinc-600 ring-1 ring-inset ring-zinc-500/10"><iconify-icon icon="solar:videocamera-linear"></iconify-icon> 视频编导剪辑</span></div></a>
</div></div></main>
    </>
  );
}
