import React from "react";

// Auto-generated by Aura to keep the project runnable after a missing local component import.
export function Integrations() {
  return null;
}

export default Integrations;
